#!/bin/bash


export CFLAGS=-"O2"
export CXXFLAGS="-O2"

URL=http://liba52.sourceforge.net/files/a52dec-0.7.4.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build


./configure --prefix=/usr \
            --mandir=/usr/share/man \
            --enable-shared \
            --disable-static \
            CFLAGS="${CFLAGS:--g -O2} $([ $(uname -m) = x86_64 ] && echo -fPIC)"

make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
cp liba52/a52_internal.h /pkgs/$PACKAGE/usr/include/a52dec
cd /pkgs
cp -rpv /pkgs/$PACKAGE/* /



sudo echo "glibc" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


