#!/bin/bash
#NLFS
set -e
export CFLAGS=-"O2"
export CXXFLAGS="-O2"
PKG_VER=1.0.4
URL=https://www.freedesktop.org/software/appstream/releases/AppStream-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=appstream

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir abuild
cd abuild

meson setup --prefix=/usr --buildtype=release -Dapidocs=false -Dqt=true ..

ninja


# Install
sudo  DESTDIR=/pkgs/$PACKAGE ninja install
sudo ninja install
cd /pkgs



sudo echo "xmlb glib librsvg libyaml" > /pkgs/$PACKAGE/depends
sudo echo "gperf libstemmer qt6"> /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


