#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

PKG_VER=2.0.20
URL=https://github.com/asciidoctor/asciidoctor/archive/v$PKG_VER/asciidoctor-$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

gem build asciidoctor.gemspec




# Install
mkdir -p /pkgs/$PACKAGE/usr/bin /pkgs/$PACKAGE/usr/share/man/man1
gem install asciidoctor-$PKG_VER.gem -n /pkgs/$PACKAGE/usr/bin &&

install -vm644 man/asciidoctor.1 /pkgs/$PACKAGE/usr/share/man/man1
cd /pkgs



sudo echo "ruby asciidoc" > /pkgs/$PACKAGE/depends
sudo echo "ruby" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


