#!/bin/bash
set -e
export CFLAGS=-"O2"
export CXXFLAGS="-O2"
PKG_VER=20101122
URL=https://ftp.gnu.org/gnu/aspell/aspell-$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

./configure --prefix=/usr 


make -j22


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
ln -svfn aspell-0.60 /pkgs/$PACKAGE/usr/lib/aspell &&

install -v -m755 -d /pkgs/$PACKAGE/usr/share/doc/aspell-$PKG_VER/aspell{,-dev}.html &&

install -v -m644 manual/aspell.html/* \
    /pkgs/$PACKAGE/usr/share/doc/aspell-$PKG_VER/aspell.html &&

install -v -m644 manual/aspell-dev.html/* \
    /pkgs/$PACKAGE/usr/share/doc/aspell-$PKG_VER/aspell-dev.html
mkdir -p /pkgs/$PACKAGE/usr/bin
install -v -m 755 scripts/ispell /pkgs/$PACKAGE/usr/bin/
install -v -m 755 scripts/spell /usr/bin/

# Install english spell check
cd /blfs/builds
wget https://ftp.gnu.org/gnu/aspell/dict/en/aspell6-en-2020.12.07-0.tar.bz2
tar xf aspell6-en-2020.12.07-0.tar.bz2

cd aspell6-en-2020.12.07-0
./configure
make
make DESTDIR=/pkgs/$PACKAGE install



cd /pkgs



sudo echo "which" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


