#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"
PKG_VER=1.87.0
URL=https://github.com/boostorg/boost/releases/download/boost-$PKG_VER/boost-$PKG_VER-b2-nodocs.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=boost-$PKG_VER
PACKAGE=boost

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
./bootstrap.sh --prefix=/pkgs/boost/usr --with-python=python3 &&
./b2 stage -j16 threading=multi link=shared




# Install
./b2 install threading=multi link=shared
cd /pkgs



sudo echo "which icu" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished
cp -rpv $PACKAGE/* /

cd /blfs/builds
sudo rm -r $DIR


