#!/bin/bash
URL=https://boostorg.jfrog.io/artifactory/main/release/1.80.0/source/boost_1_80_0.tar.bz2
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=boost

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

./bootstrap.sh --prefix=/pkgs/boost/usr --with-python=python3 &&
./b2 stage -j16 threading=multi link=shared


make -j16


# Install
./b2 install threading=multi link=shared
cd /pkgs



sudo echo "which icu" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished
cp -rpv $PACKAGE/* /

cd /blfs/builds
sudo rm -r $DIR


