#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"
PKG_VER=1_87_0
PKG_VER_REFORMAT=$(echo $PKG_VER | sed 's/_/\./g')
URL=https://boostorg.jfrog.io/artifactory/main/release/$PKG_VER_REFORMAT/source/boost_$PKG_VER.tar.bz2
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=boost

# Get Package

cd /blfs/builds
wget $URL
wget https://www.linuxfromscratch.org/patches/blfs/svn/boost-$PKG_VER-upstream_fixes-1.patch
tar -xvf $TAR
cd $DIR

# Build
patch -Np1 < ../boost-$PKG_VER-upstream_fixes-1.patch
./bootstrap.sh --prefix=/pkgs/boost/usr --with-python=python3 &&
./b2 stage -j16 threading=multi link=shared




# Install
./b2 install threading=multi link=shared
cd /pkgs



sudo echo "which icu" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished
cp -rpv $PACKAGE/* /

cd /blfs/builds
sudo rm -r $DIR


