#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


PKG_VER=3.12.3
MAJOR=$(echo $PKG_VER | sed 's|.[^.]*$||g')
URL=https://download.gnome.org/sources/brasero/$MAJOR/brasero-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
# GCC 14 patch
wget https://www.linuxfromscratch.org/patches/blfs/12.2/brasero-3.12.3-upstream_fixes-1.patch
tar -xvf $TAR
cd $DIR

# Build
patch -Np1 < ../brasero-3.12.3-upstream_fixes-1.patch
./configure --prefix=/usr                \
            --enable-compile-warnings=no \
            --enable-cxx-warnings=no  


make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "gst-plugins-base itstool libcanberra libnotify gobject-introspection tinysparql totem-pl-parser dvdrw-tools gvfs" > /pkgs/$PACKAGE/depends
sudo echo "intltool" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


