#!/bin/bash
URL=https://github.com/containers/bubblewrap/releases/download/v0.6.2/bubblewrap-0.6.2.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir build &&
cd    build &&

meson --prefix=/usr --buildtype=release .. &&


ninja -j16


# Install
ninja install && DESTDIR=/pkgs/$PACKAGE ninja install
cd /pkgs
sudo  $PACKAGE


sudo echo "" > /pkgs/$PACKAGE/depends
sudo rm -r /pkgs/$PACKAGE/blfs
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


