#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


PKG_VER=1.37.0
URL=https://busybox.net/downloads/busybox-$PKG_VER.tar.bz2
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build


make defconfig

make -j16


# Install
sudo make CONFIG_PREFIX=/blfs/builds/$DIR/installed install
mkdir -p /pkgs/$PACKAGE/usr/bin/
cp /blfs/builds/$DIR/installed/usr/bin/busybox /pkgs/$PACKAGE/usr/bin
cd /pkgs



sudo echo "" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


