#!/bin/bash
URL=https://github.com/lfs-book/make-ca/releases/download/v1.10/make-ca-1.10.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=ca-certificates

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build



# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
install -vdm755 /pkgs/$PACKAGE/etc/ssl/local
cd /pkgs



sudo echo "p11-kit" > /pkgs/$PACKAGE/depends
sudo echo "/usr/sbin/make-ca -g --force" > /pkgs/$PACKAGE/postinst
sudo echo "make coreutils" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished

# Install on host
cp -rpv /pkgs/$PACKAGE/* /

cd /blfs/builds
sudo rm -r $DIR


