#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


PKG_VER=1.12
URL=https://github.com/lfs-book/make-ca/releases/download/v$PKG_VER/make-ca-$PKG_VER.tar.xz
URL2=https://src.fedoraproject.org/rpms/ca-certificates/raw/rawhide/f/update-ca-trust
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=ca-certificates

# Get Package

cd /blfs/builds
wget $URL
wget $URL2
tar -xvf $TAR
cd $DIR

# Build


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
mkdir -p /pkgs/$PACKAGE/usr/bin
cp /blfs/builds/update-ca-trust /pkgs/$PACKAGE/usr/bin/
install -vdm755 /pkgs/$PACKAGE/etc/ssl/local
cd /pkgs



sudo echo "p11-kit" > /pkgs/$PACKAGE/depends
sudo echo "/usr/sbin/make-ca -g --force" > /pkgs/$PACKAGE/postinst
sudo echo "make coreutils" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished

# Install on host
cp -rpv /pkgs/$PACKAGE/* /

cd /blfs/builds
sudo rm -r $DIR


