#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


PKG_VER=1.14
URL=https://github.com/lfs-book/make-ca/archive/v$PKG_VER/make-ca-$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=ca-certificates

# Get Package

cd /blfs/builds
wget $URL
wget $URL2
tar -xvf $TAR
cd $DIR

# Build


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
mkdir -p /pkgs/$PACKAGE/usr/bin
install -vdm755 /pkgs/$PACKAGE/etc/ssl/local
mkdir -p /pkgs/$PACKAGE/etc/ssl/certs/
ln -svf /etc/pki/tls/certs/ca-bundle.crt /pkgs/$PACKAGE/etc/ssl/certs/ca-certificates.crt
cd /pkgs



sudo echo "p11-kit" > /pkgs/$PACKAGE/depends
sudo echo "/usr/sbin/make-ca -g --force" > /pkgs/$PACKAGE/postinst
sudo echo "make coreutils" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished

# Install on host
cp -rpv /pkgs/$PACKAGE/* /

cd /blfs/builds
sudo rm -r $DIR


