#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

PKG_VER=0.10.7
URL=https://github.com/lu-zero/cargo-c/archive/v$PKG_VER/cargo-c-$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build


export CFLAGS+=' -ffat-lto-objects'
cargo build --release

# Install
mkdir -p /pkgs/$PACKAGE/usr/bin
cp target/release/{cargo-cbuild,cargo-cinstall,cargo-ctest} /pkgs/$PACKAGE/usr/bin
cd /pkgs



sudo echo "rustc" > /pkgs/$PACKAGE/depends
sudo echo "rustc" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


