#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

set -e

PKG_VER=7.1
URL=https://www.samba.org/ftp/linux-cifs/cifs-utils/cifs-utils-$PKG_VER.tar.bz2
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

./configure --prefix=/usr --sbindir=/usr/sbin


make -j16


# Install
sudo mkdir -p /pkgs/$PACKAGE
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs
# Legacy program doesn't use $PREFIX/sbin for some reason
mv /pkgs/$PACKAGE/sbin/* /pkgs/$PACKAGE/usr/sbin/

sudo echo "mitkrb samba talloc keyutils" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


