#!/bin/bash
URL=https://download.gnome.org/sources/clutter-gtk/1.8/clutter-gtk-1.8.4.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build


./configure --prefix=/usr 
make -j20


# Install
make install && DESTDIR=/pkgs/$PACKAGE make install
cd /pkgs


sudo echo "clutter gtk3" > /pkgs/$PACKAGE/depends
sudo rm -r /pkgs/$PACKAGE/blfs
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


