#!/bin/bash
URL=https://github.com/xXTeraXx/cross-sh-tucana
DIR=cross-sh-tucana
set -e
# Get Package

cd /blfs/builds
git clone $URL
cd $DIR

# Build aarch64
bash setup.sh
bash build_toolchain.sh
bash package.sh

# Cleanup and prepare for next

cd /blfs/builds
sudo rm -r $DIR

# Get Package

cd /blfs/builds
git clone $URL
cd $DIR

# Build riscv64
bash setup.sh
sed -i 's/arm64/riscv64/g' toolchain.conf
sed -i 's/aarch64/riscv64/g' toolchain.conf
bash build_toolchain.sh
bash package.sh

# Cleanup and prepare for next

cd /blfs/builds
sudo rm -r $DIR

# Get Package

cd /blfs/builds
git clone $URL
cd $DIR

# Build armhf (32)
bash setup.sh
sed -i 's/arm64/arm/g' toolchain.conf
sed -i 's/aarch64-linux-gnu/arm-linux-gnueabihf/g' toolchain.conf
bash build_toolchain.sh
bash package.sh
# Cleanup 

cd /blfs/builds
sudo rm -r $DIR

