#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

#ARCH_PKG=cryptsetup
#ARCH_VAR=pkgver
PKG_VER=2.7.4
MAJOR=$(echo $PKG_VER | sed 's|.[^.]*$||g')
URL=https://www.kernel.org/pub/linux/utils/cryptsetup/v$MAJOR/cryptsetup-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

./configure --prefix=/usr \
            --disable-ssh-token


make -j22


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "json-c lvm popt" > /pkgs/$PACKAGE/depends
sudo echo "asciidoctor" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


