#!/bin/bash
export CFLAGS=-"O2"
export CXXFLAGS="-O2"

URL=https://github.com/OpenPrinting/cups/releases/download/v2.4.2/cups-2.4.2-source.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=cups-2.4.2
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

useradd -c "Print Service User" -d /var/spool/cups -g lp -s /bin/false -u 9 lp
groupadd -g 19 lpadmin
sed -i 's#@CUPS_HTMLVIEW@#firefox#' desktop/cups.desktop.in
./configure --libdir=/usr/lib            \
            --disable-systemd            \
            --with-rcdir=/tmp/cupsinit   \
            --with-system-groups=lpadmin \
            --with-docdir=/usr/share/cups/doc-2.4.2



make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
rm -r /pkgs/$PACKAGE/tmp
cd /pkgs



sudo echo "" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


