#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"
PKG_VER=2.4.5
URL=https://github.com/OpenPrinting/cups/releases/download/v$PKG_VER/cups-$PKG_VER-source.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=cups-$PKG_VER
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

useradd -c "Print Service User" -d /var/spool/cups -g lp -s /bin/false -u 9 lp
groupadd -g 19 lpadmin
sed -i 's#@CUPS_HTMLVIEW@#firefox#' desktop/cups.desktop.in
./configure --libdir=/usr/lib            \
            --disable-systemd            \
            --with-rcdir=/tmp/cupsinit   \
            --with-system-groups=lpadmin \
            --with-docdir=/usr/share/cups/doc-2.4.2



make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
rm -r /pkgs/$PACKAGE/tmp
cd /pkgs



sudo echo "gnutls colord dbus libusb pam xdg-utils avahi" > /pkgs/$PACKAGE/depends
sudo echo "useradd -c "Print Service User" -d /var/spool/cups -g lp -s /bin/false -u 9 lp && groupadd -g 19 lpadmin && gtk-update-icon-cache -qtf /usr/share/icons/hicolor" > /pkgs/$PACKAGE/postinst
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


