#!/bin/bash
URL=https://curl.se/download/curl-7.87.0.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

./configure --prefix=/usr                           \
            --disable-static                        \
            --with-openssl                          \
            --enable-threaded-resolver              \
            --with-ca-path=/etc/ssl/certs 


make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install

install -v -d -m755 /pkgs/curl/usr/share/doc/curl-7.84.0 &&
cp -v -R docs/*     /pkgs/curl/usr/share/doc/curl-7.84.0
cd /pkgs



sudo echo "" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


