#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"
PKG_VER=8.10.0
URL=https://curl.se/download/curl-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

./configure --prefix=/usr                           \
            --disable-static                        \
            --with-openssl                          \
            --enable-threaded-resolver              \
            --with-ca-path=/etc/ssl/certs \
            --disable-ldap \
            --disable-ldaps

make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install

install -v -d -m755 /pkgs/curl/usr/share/doc/curl &&
cp -v -R docs/*     /pkgs/curl/usr/share/doc/curl
cd /pkgs



sudo echo "nghttp2" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


