#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

URL=https://github.com/ddccontrol/ddccontrol/archive/0.6.0.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=ddccontrol-$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=ddccontrol

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
./autogen.sh
./configure --prefix=/usr --disable-gnome-applet


make -j20


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
mv /pkgs/$PACKAGE/usr/etc/dbus-1/* /pkgs/$PACKAGE/usr/share/dbus-1
cd /pkgs



sudo echo "ddccontrol-db pciutils" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished



cd /blfs/builds
sudo rm -r $DIR


