#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

PKG_VER=20240304
URL=https://github.com/ddccontrol/ddccontrol-db/archive/refs/tags/$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=ddccontrol-db-$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=ddccontrol-db
set -e
# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
./autogen.sh
./configure --prefix=/usr


make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "" > /pkgs/$PACKAGE/depends
sudo echo "intltool check perl-xml-parser" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


