#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


PKG_VER=5.0
URL=https://www.docbook.org/xml/$PKG_VER/docbook-$PKG_VER.zip
ZIP=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $ZIP | sed 's|.zip||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')
set -e
# Get Package

cd /blfs/builds
wget $URL
mkdir -p $DIR
cd $DIR
unzip ../$ZIP

# Build

install -v -d -m755 /pkgs/$PACKAGE/usr/share/xml/docbook/xml-dtd-$PKG_VER &&
install -v -d -m755 /pkgs/$PACKAGE/etc/xml &&
chown -R root:root . &&
cp -v -af docbook.cat *.dtd ent/ *.mod \
    /pkgs/$PACKAGE/usr/share/xml/docbook/xml-dtd-$PKG_VER

if [ ! -e /pkgs/$PACKAGE/etc/xml/docbook ]; then
    xmlcatalog --noout --create /pkgs/$PACKAGE/etc/xml/docbook
fi &&
xmlcatalog --noout --add "public" \
    "-//OASIS//DTD DocBook XML V$PKG_VER//EN" \
    "http://www.oasis-open.org/docbook/xml/$PKG_VER/docbookx.dtd" \
    /pkgs/$PACKAGE/etc/xml/docbook &&
xmlcatalog --noout --add "public" \
    "-//OASIS//DTD DocBook XML CALS Table Model V$PKG_VER//EN" \
    "file:////usr/share/xml/docbook/xml-dtd-$PKG_VER/calstblx.dtd" \
    /pkgs/$PACKAGE/etc/xml/docbook &&
xmlcatalog --noout --add "public" \
    "-//OASIS//DTD XML Exchange Table Model 19990315//EN" \
    "file:////usr/share/xml/docbook/xml-dtd-$PKG_VER/soextblx.dtd" \
    /pkgs/$PACKAGE/etc/xml/docbook &&
xmlcatalog --noout --add "public" \
    "-//OASIS//ELEMENTS DocBook XML Information Pool V$PKG_VER//EN" \
    "file:////usr/share/xml/docbook/xml-dtd-$PKG_VER/dbpoolx.mod" \
    /pkgs/$PACKAGE/etc/xml/docbook &&
xmlcatalog --noout --add "public" \
    "-//OASIS//ELEMENTS DocBook XML Document Hierarchy V$PKG_VER//EN" \
    "file:////usr/share/xml/docbook/xml-dtd-$PKG_VER/dbhierx.mod" \
    /pkgs/$PACKAGE/etc/xml/docbook &&
xmlcatalog --noout --add "public" \
    "-//OASIS//ELEMENTS DocBook XML HTML Tables V$PKG_VER//EN" \
    "file:////usr/share/xml/docbook/xml-dtd-$PKG_VER/htmltblx.mod" \
    /pkgs/$PACKAGE/etc/xml/docbook &&
xmlcatalog --noout --add "public" \
    "-//OASIS//ENTITIES DocBook XML Notations V$PKG_VER//EN" \
    "file:////usr/share/xml/docbook/xml-dtd-$PKG_VER/dbnotnx.mod" \
    /pkgs/$PACKAGE/etc/xml/docbook &&
xmlcatalog --noout --add "public" \
    "-//OASIS//ENTITIES DocBook XML Character Entities V$PKG_VER//EN" \
    "file:////usr/share/xml/docbook/xml-dtd-$PKG_VER/dbcentx.mod" \
    /pkgs/$PACKAGE/etc/xml/docbook &&
xmlcatalog --noout --add "public" \
    "-//OASIS//ENTITIES DocBook XML Additional General Entities V$PKG_VER//EN" \
    "file:////usr/share/xml/docbook/xml-dtd-$PKG_VER/dbgenent.mod" \
    /pkgs/$PACKAGE/etc/xml/docbook &&
xmlcatalog --noout --add "rewriteSystem" \
    "http://www.oasis-open.org/docbook/xml/$PKG_VER" \
    "file:////usr/share/xml/docbook/xml-dtd-$PKG_VER" \
    /pkgs/$PACKAGE/etc/xml/docbook &&
xmlcatalog --noout --add "rewriteURI" \
    "http://www.oasis-open.org/docbook/xml/$PKG_VER" \
    "file:////usr/share/xml/docbook/xml-dtd-$PKG_VER" \
    /pkgs/$PACKAGE/etc/xml/docbook


if [ ! -e /pkgs/$PACKAGE/etc/xml/catalog ]; then
    xmlcatalog --noout --create /pkgs/$PACKAGE/etc/xml/catalog
fi &&
xmlcatalog --noout --add "delegatePublic" \
    "-//OASIS//ENTITIES DocBook XML" \
    "file:////etc/xml/docbook" \
    /pkgs/$PACKAGE/etc/xml/catalog &&
xmlcatalog --noout --add "delegatePublic" \
    "-//OASIS//DTD DocBook XML" \
    "file:////etc/xml/docbook" \
    /pkgs/$PACKAGE/etc/xml/catalog &&
xmlcatalog --noout --add "delegateSystem" \
    "http://www.oasis-open.org/docbook/" \
    "file:////etc/xml/docbook" \
    /pkgs/$PACKAGE/etc/xml/catalog &&
xmlcatalog --noout --add "delegateURI" \
    "http://www.oasis-open.org/docbook/" \
    "file:////etc/xml/docbook" \
    /pkgs/$PACKAGE/etc/xml/catalog



for DTDVERSION in 4.1.2 4.2 4.3 4.4
do
  xmlcatalog --noout --add "public" \
    "-//OASIS//DTD DocBook XML V$DTDVERSION//EN" \
    "http://www.oasis-open.org/docbook/xml/$DTDVERSION/docbookx.dtd" \
    /pkgs/$PACKAGE/etc/xml/docbook
  xmlcatalog --noout --add "rewriteSystem" \
    "http://www.oasis-open.org/docbook/xml/$DTDVERSION" \
    "file:////usr/share/xml/docbook/xml-dtd-$PKG_VER" \
    /pkgs/$PACKAGE/etc/xml/docbook
  xmlcatalog --noout --add "rewriteURI" \
    "http://www.oasis-open.org/docbook/xml/$DTDVERSION" \
    "file:////usr/share/xml/docbook/xml-dtd-$PKG_VER" \
    /pkgs/$PACKAGE/etc/xml/docbook
  xmlcatalog --noout --add "delegateSystem" \
    "http://www.oasis-open.org/docbook/xml/$DTDVERSION/" \
    "file:////etc/xml/docbook" \
    /pkgs/$PACKAGE/etc/xml/catalog
  xmlcatalog --noout --add "delegateURI" \
    "http://www.oasis-open.org/docbook/xml/$DTDVERSION/" \
    "file:////etc/xml/docbook" \
    /pkgs/$PACKAGE/etc/xml/catalog
done


cd /pkgs



sudo echo "libxml2 sgml-common" > /pkgs/$PACKAGE/depends
sudo echo "libxml2 sgml-common unzip" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


