#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

#HOLD_TUCANA
PKG_VER=1.10.0
URL=https://doxygen.nl/files/doxygen-$PKG_VER.src.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=doxygen-$PKG_VER
PACKAGE=doxygen

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
mkdir build
cd build
grep -rl '^#!.*python$' | xargs sed -i '1s/python/&3/'

cmake -G "Unix Makefiles"         \
      -DCMAKE_BUILD_TYPE=Release  \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -Wno-dev ..


make -j22


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


