#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


PKG_VER=2.7.0
URL=https://duktape.org/duktape-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')
set -e
# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
sed -i 's/-Os/-O2/' Makefile.sharedlibrary




make -f Makefile.sharedlibrary INSTALL_PREFIX=/usr -j20


# Install
make -f Makefile.sharedlibrary INSTALL_PREFIX=/usr install
make DESTDIR=/pkgs/$PACKAGE -f Makefile.sharedlibrary INSTALL_PREFIX=/usr install
cd /pkgs



sudo echo "glibc" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


