#!/bin/bash
URL=https://download.gnome.org/sources/evince/42/evince-42.3.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/day18/gnome
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir build &&
cd    build &&

export CPPFLAGS="-I/opt/texlive/2022/include" &&
export LDFLAGS="$LDFLAGS -L/opt/texlive/2022/lib"


meson --prefix=/usr          \
      --buildtype=release    \
      -Dgtk_doc=false        \
      --wrap-mode=nodownload \
      ..                     &&


ninja -j16


# Install
sudo porg -lp $PACKAGE "ninja install"
cd /gnome
sudo ./dir.sh $PACKAGE


sudo echo "adwaita-icon-theme gsettings-desktop-schemas gtk3 itstool libhandy libxml2 openjpeg gnome-keyring gobject-introspection libarchive libsecret poppler cups gnome-desktop" > /pkgs/gnome42/$PACKAGE/depends
sudo echo "glib-compile-schemas /usr/share/glib-2.0/schemas" > /pkgs/gnome42/$PACKAGE/depends
sudo rm -r /pkgs/gnome42/$PACKAGE/blfs
sudo tar -cvpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished/gnome42


cd /blfs/day18/gnome
sudo rm -r $DIR


