#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


PKG_VER=7.1
URL=https://ffmpeg.org/releases/ffmpeg-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
wget https://www.linuxfromscratch.org/patches/blfs/svn/ffmpeg-$PKG_VER-chromium_method-1.patch
tar -xvf $TAR
cd $DIR

# Build

# Upstream fix for x265-4.1
sed -e 's/X265_BUILD >= 210/(&) \&\& (X265_BUILD < 213)/' \
     -i libavcodec/libx265.c

patch -Np1 -i ../ffmpeg-$PKG_VER-chromium_method-1.patch

./configure --prefix=/usr        \
            --enable-gpl         \
            --enable-version3    \
            --disable-static     \
            --enable-shared      \
            --disable-debug      \
            --enable-libass      \
            --enable-libaom      \
            --enable-libfreetype \
            --enable-libmp3lame  \
            --enable-libopus     \
            --enable-libtheora   \
            --enable-libvorbis   \
            --enable-libvpx      \
            --enable-libx264     \
            --enable-vulkan      \
            --enable-libx265     \
            --enable-gnutls      \
            --docdir=/usr/share/doc/ffmpeg


make -j16
gcc tools/qt-faststart.c -o tools/qt-faststart


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
install -v -m755    tools/qt-faststart /pkgs/$PACKAGE/usr/bin &&
install -v -m755 -d           /pkgs/$PACKAGE/usr/share/doc/ffmpeg &&
install -v -m644    doc/*.txt /pkgs/$PACKAGE/usr/share/doc/ffmpeg
cd /pkgs

sudo cp -rpv $PACKAGE/* /

sudo echo "libass fdk-aac freetype2 lame libtheora libvorbis libvpx opus x264 x265 nasm yasm alsa-lib libva libvdpau sdl2 fontconfig fribidi libaom" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


