#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


PKG_VER=1.14.10
URL=https://github.com/flatpak/flatpak/releases/download/$PKG_VER/flatpak-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build


NOCONFIGURE=1 ./autogen.sh
./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --without-system-dbus-proxy


make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "gnupg glib libsoup libxml2 dconf systemd libarchive gpgme fuse2 ostree json-glib appstream-glib ostree libseccomp libxslt docbook-xml docbook-xsl gtk-doc dconf p11-kit avahi xdg-desktop-portal malcontent" > /pkgs/$PACKAGE/depends
sudo echo "pyparsing" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


