#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"
set -e
PKG_VER=1.4.0rc1
URL=https://fltk.org/pub/fltk/$PKG_VER/fltk-$PKG_VER-source.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=fltk-$PKG_VER
PACKAGE=fltk


# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
sed -i -e '/cat./d' documentation/Makefile  

autoconf -ri
./configure --prefix=/usr    \
            --enable-shared 

make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE docdir=/usr/share/doc/fltk-$PKG_VER install
sudo make docdir=/usr/share/doc/fltk-$PKG_VER install
cd /pkgs



sudo echo "xorg-libs hicolor-icons libjpeg-turbo libpng" > /pkgs/$PACKAGE/depends
sudo tar -cvpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


