#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"
set -e
#TAG_OVERRIDE
PKG_VER=1.3.8
URL=https://github.com/fltk/fltk/archive/refs/tags/release-$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=fltk-release-$PKG_VER
PACKAGE=fltk

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
sed -i -e '/cat./d' documentation/Makefile  


./configure --prefix=/usr    \
            --enable-shared 

make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE docdir=/usr/share/doc/fltk-$PKG_VER install
sudo make docdir=/usr/share/doc/fltk-$PKG_VER install
cd /pkgs



sudo echo "xorg-libs hicolor-icons libjpeg-turbo libpng" > /pkgs/$PACKAGE/depends
sudo tar -cvpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


