#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

URL=https://www.freedesktop.org/software/fontconfig/release/fontconfig-2.14.2.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

./configure --prefix=/usr        \
	    --sysconfdir=/etc    \
	    --localstatedir=/var \
	    -disable-docs       \


make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install

install -v -dm755 \
/pkgs/$PACKAGE/usr/share/{man/man{1,3,5},doc/fontconfig/fontconfig-devel} &&
install -v -m644 fc-*/*.1         /pkgs/$PACKAGE/usr/share/man/man1 &&
install -v -m644 doc/*.3          /pkgs/$PACKAGE/usr/share/man/man3 &&
install -v -m644 doc/fonts-conf.5 /pkgs/$PACKAGE/usr/share/man/man5 &&
install -v -m644 doc/fontconfig-devel/* \
  /pkgs/$PACKAGE/usr/share/doc/fontconfig/fontconfig-devel &&
install -v -m644 doc/*.{pdf,sgml,txt,html} \
  /pkgs/$PACKAGE/usr/share/doc/fontconfig


sudo make install
cd /pkgs



sudo echo "freetype2" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


