#!/bin/bash
#NLFS
export CFLAGS=-"O2"
export CXXFLAGS="-O2"
PKG_VER=2.10.0
URL=https://github.com/FreeRDP/FreeRDP/releases/download/$PKG_VER/freerdp-$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
wget https://github.com/FreeRDP/FreeRDP/commit/aa2cb9aa.patch
tar -xvf $TAR
cd $DIR

# Build
patch -Np1 < ../aa2cb9aa.patch
mkdir build
cd build

cmake -DCMAKE_INSTALL_PREFIX=/usr -Wno-dev -DWITH_DSP_FFMPEG=ON -DWITH_FFMPEG=ON -DWITH_JPEG=ON ..



make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "xorg pulseaudio alsa-lib icu libjpeg-turbo ffmpeg libusb cups libxkbcommon" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


