#!/bin/bash
#NLFS
export CFLAGS=-"O2"
export CXXFLAGS="-O2"
PKG_VER=3.5.1
URL=https://github.com/freerdp/freerdp/archive/$PKG_VER/freerdp-$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=FreeRDP-$PKG_VER
PACKAGE=freerdp

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
mkdir build
cd build

cmake -DCMAKE_INSTALL_PREFIX=/usr -Wno-dev -DWITH_DSP_FFMPEG=ON -DWITH_FFMPEG=ON -DWITH_JPEG=ON ..



make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "xorg pulseaudio alsa-lib icu libjpeg-turbo ffmpeg libusb cups libxkbcommon sdl2_ttf" > /pkgs/$PACKAGE/depends
sudo echo "pkcs11-helper"

sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


