#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

URL=https://src.fedoraproject.org/repo/pkgs/fuse/fuse-2.9.9.tar.gz/sha512/3d82fafd04f2924299bb09d2bb144935fa004a43fb9a6568e2e1cc5a60fded2efa1711029a0d7f12b3e6e4501f7217f2ee3545646d89da8dece083cb390f23e2/fuse-2.9.9.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')2
set -e
# Get Package

cd /blfs/builds
wget $URL
wget https://raw.githubusercontent.com/xXTeraXx/Tucana/main/mercury/patches/fuse2.patch
tar -xvf $TAR
cd $DIR

# Build
autoreconf -i
patch -Np1 < ../fuse2.patch
./configure --prefix=/usr


make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "fuse3" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


