#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"
set -e

PKG_VER=2.42.10
MAJOR=$(echo $PKG_VER | sed 's|.[^.]*$||g')
URL=https://download.gnome.org/sources/gdk-pixbuf/$MAJOR/gdk-pixbuf-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir build
cd build

meson --prefix=/usr -Dgtk_doc=false --buildtype=release -Ddocs=false ..

ninja


# Install
sudo  DESTDIR=/pkgs/$PACKAGE ninja install
sudo ninja install
cd /pkgs



sudo echo "glib libjpeg-turbo libpng shared-mime-info librsvg libtiff gobject-introspection
" > /pkgs/$PACKAGE/depends
sudo echo "gdk-pixbuf-query-loaders --update-cache" > /pkgs/$PACKAGE/postinst
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


