#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


PKG_VER=0.2.5
MAJOR=$(echo $PKG_VER | sed 's|.[^.]*$||g')
URL=https://download.gnome.org/sources/gfbgraph/$MAJOR/gfbgraph-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build


./configure --prefix=/usr --disable-static --enable-gtk-doc

make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE libgfbgraphdocdir=/usr/share/doc/gfbgraph-$PKG_VER install
sudo make libgfbgraphdocdir=/usr/share/doc/gfbgraph-$PKG_VER install
cd /pkgs



sudo echo "gnome-online-accounts rest gobject-introspection" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


