#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

URL=https://download.gimp.org/pub/gimp/v2.10/gimp-2.10.34.tar.bz2
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

./configure --prefix=/usr --sysconfdir=/etc --disable-python


make -j22


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "gegl gexiv2 glib-networking gtk2 harfbuzz libjpeg-turbo libmypaint librsvg libtiff lcms mypaintbrushes poppler-data dbus-glib ghostscript iso-codes libgudev xdg-utils alsa-lib gvfs" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


