#!/bin/bash
URL=https://download.gnome.org/sources/glib/2.74/glib-2.74.3.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir build
cd build

meson --prefix=/usr       \
      --buildtype=release \
      -Dman=true          \
      ..     


ninja


# Install
sudo  DESTDIR=/pkgs/$PACKAGE ninja install
sudo ninja install
cd /pkgs

mkdir -p /pkgs/glib/usr/share/doc/glib-2.72.3 &&
cp -r ../docs/reference/{gio,glib,gobject} /pkgs/glib/usr/share/doc/glib-2.72.3


sudo echo "pcre base" > /pkgs/$PACKAGE/depends
echo "if [ -e /usr/include/glib-2.0 ]; then
    rm -rf /usr/include/glib-2.0.old &&
    mv -vf /usr/include/glib-2.0{,.old}
fi" > /pkgs/$PACKAGE/preinst
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


