#!/bin/bash
URL=https://download.gnome.org/sources/gnome-terminal/3.44/gnome-terminal-3.44.1.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/day18/gnome
wget $URL
tar -xvf $TAR
cd $DIR

# Build
sed -i -r 's:"(/system):"/org/gnome\1:g' src/external.gschema.xml
mkdir build &&
cd    build &&


meson --prefix=/usr --buildtype=release .. && 


ninja -j16


# Install
sudo porg -lp $PACKAGE "ninja install"
cd /gnome
sudo ./dir.sh $PACKAGE


sudo echo "dconf gnome-shell gsettings-desktop-schemas itstool vte pcre2" > /pkgs/gnome42/$PACKAGE/depends
sudo rm -r /pkgs/gnome42/$PACKAGE/blfs
sudo tar -cvpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished/gnome42


cd /blfs/day18/gnome
sudo rm -r $DIR


