#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"
PKG_VER=3.8.7.1
#MAJOR=$(echo $PKG_VER | sed 's|.[^.]*$||g')
MAJOR=$(echo $PKG_VER | grep -o -E "3\.[0-9]+") 
URL=https://www.gnupg.org/ftp/gcrypt/gnutls/v$MAJOR/gnutls-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=gnutls-$(echo $PKG_VER | grep -Eo "3.\[0-9]+\.[0-9]+")
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

./configure --prefix=/usr \
            --disable-rpath \
            --with-default-trust-store-pkcs11="pkcs11:"


make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "nettle libunistring libtasn1" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


