#!/bin/bash
URL=https://gstreamer.freedesktop.org/src/gstreamer/gstreamer-1.20.3.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/day22
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir build &&
cd    build &&


meson  --prefix=/usr       \
       --buildtype=release \
       -Dgst_debug=false   \
       -Dpackage-name="GStreamer 1.20.3 Tucana" &&


ninja


# Install
sudo porg -lp $PACKAGE "ninja install"
cd /pkgs
sudo ./dir.sh $PACKAGE

sudo echo "rm -rf /usr/bin/gst-* /usr/{lib,libexec}/gstreamer-1.0" > /pkgs/$PACKAGE/prerm
sudo echo "rm -rf /usr/bin/gst-* /usr/{lib,libexec}/gstreamer-1.0" > /pkgs/$PACKAGE/preupdate
sudo echo "glib gobject-introspection" > /pkgs/$PACKAGE/depends
sudo tar -cvpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/day22
sudo rm -r $DIR

