#!/bin/bash
PKG_VER=1.22.0
URL=https://gstreamer.freedesktop.org/src/gstreamer/gstreamer-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir build &&
cd    build &&


meson  --prefix=/usr       \
       --buildtype=release \
       -Dgst_debug=false   \
       -Dpackage-name="GStreamer $PKG_VER For Tucana" &&


ninja


# Install
DESTDIR=/pkgs/$PACKAGE ninja install
ninja install
cd /pkgs


sudo echo "rm -rf /usr/bin/gst-* /usr/{lib,libexec}/gstreamer-1.0" > /pkgs/$PACKAGE/prerm
sudo echo "rm -rf /usr/bin/gst-* /usr/{lib,libexec}/gstreamer-1.0" > /pkgs/$PACKAGE/preupdate
sudo echo "glib gobject-introspection" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR

