#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

URL=https://download.gnome.org/sources/gtk+/2.24/gtk+-2.24.33.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=gtk2

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build


sed -e 's#l \(gtk-.*\).sgml#& -o \1#' \
    -i docs/{faq,tutorial}/Makefile.in      &&

./configure --prefix=/usr --sysconfdir=/etc

make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "atk gdk-pixbuf pango hicolor-icons" > /pkgs/$PACKAGE/depends
sudo echo "gtk-query-immodules-2.0 --update-cache" > /pkgs/$PACKAGE/postinst
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


