#!/bin/bash
URL=https://download.gnome.org/sources/gtk+/3.24/gtk+-3.24.36.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=gtk3

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
mkdir build
cd build
meson setup --prefix=/usr           \
            --buildtype=release     \
            ..
ninja

# Install
DESTDIR=/pkgs/$PACKAGE ninja install
ninja install
cd /pkgs



sudo echo "at-spi2-core gdk-pixbuf libepoxy pango wayland sassc" > /pkgs/$PACKAGE/depends
echo "gtk-query-immodules-3.0 --update-cache && glib-compile-schemas /usr/share/glib-2.0/schemas" > /pkgs/$PACKAGE/postinst
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


