#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

#ARCH_PKG=gtk3
#ARCH_VAR=pkgver
PKG_VER=3.24.43
MAJOR=$(echo $PKG_VER | sed 's|.[^.]*$||g')
URL=https://download.gnome.org/sources/gtk+/$MAJOR/gtk+-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=gtk3

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
mkdir build
cd build
meson setup --prefix=/usr           \
            --buildtype=release     \
            ..
ninja

# Install
DESTDIR=/pkgs/$PACKAGE ninja install
ninja install
cd /pkgs



sudo echo "tinysparql gdk-pixbuf libepoxy adwaita hicolor-icons libxkbcommon sassc at-spi2-core gdk-pixbuf libepoxy pango wayland sassc" > /pkgs/$PACKAGE/depends
echo "gtk-query-immodules-3.0 --update-cache && glib-compile-schemas /usr/share/glib-2.0/schemas" > /pkgs/$PACKAGE/postinst
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


