#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


PKG_VER=1.54.1
MAJOR=$(echo $PKG_VER | sed 's|.[^.]*$||g')
URL=https://download.gnome.org/sources/gvfs/$MAJOR/gvfs-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir build &&
cd    build &&


meson --prefix=/usr       \
      --buildtype=release \
      -Dfuse=true        \
      -Dgphoto2=false     \
      -Dafc=false         \
      -Dbluray=false      \
      -Dnfs=false         \
      -Dmtp=true         \
      -Dsmb=true         \
      -Ddnssd=false       \
      -Donedrive=false \
      -Dgoa=true \
      -Dgoogle=false 


ninja


# Install
DESTDIR=/pkgs/gvfs ninja install
cd /pkgs


sudo echo "gcr-4 dbus glib libusb libsecret gcr gtk3 libcdio libgdata libgudev libsoup systemd udisks libarchive dbus-glib libmtp fuse3 libsoup3" > /pkgs/$PACKAGE/depends
sudo echo "samba" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


