#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

set -e
PKG_VER=10.1.0
URL=https://github.com/harfbuzz/harfbuzz/releases/download/$PKG_VER/harfbuzz-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir build
cd build



meson setup --prefix=/usr        \
      --buildtype=release  \
      -Dgraphite2=enabled \
      -Dcpp_std=c++17   \
      ..

ninja


# Install
sudo  DESTDIR=/pkgs/$PACKAGE ninja install
sudo ninja install
cd /pkgs



sudo echo "glib graphite2 cairo" > /pkgs/$PACKAGE/depends
sudo echo "freetype2 cairo git glib graphite2 icu meson ninja" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


