#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

URL=https://github.com/harfbuzz/harfbuzz/releases/download/7.2.0/harfbuzz-7.2.0.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir build
cd build



meson --prefix=/usr        \
      --buildtype=release  \
      -Dgraphite2=enabled \
      -Dcairo=disabled

ninja


# Install
sudo  DESTDIR=/pkgs/$PACKAGE ninja install
sudo ninja install
cd /pkgs



sudo echo "glib graphite2" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


