#!/bin/bash
export CFLAGS=-"O2"
export CXXFLAGS="-O2"

URL=https://github.com/vcrhonek/hwdata/archive/refs/tags/v0.367.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=hwdata-0.367
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

./configure --prefix=/usr --disable-blacklist


make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


