#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


PKG_VER=1.5.31
URL=https://github.com/ibus/ibus/releases/download/$PKG_VER/ibus-$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
SAVE_DIST_FILES=1 NOCONFIGURE=1 ./autogen.sh
sed -i 's@/desktop/ibus@/org/freedesktop/ibus@g' \
    data/dconf/org.freedesktop.ibus.gschema.xml
./configure \
            --prefix=/usr              \
            --sysconfdir=/etc          \
            --disable-python2          \
            --disable-emoji-dict       \
            --disable-unicode-dict     \

rm -f tools/main.c 

make -j20


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make DESTDIR=/pkgs/$PACKAGE install-pkgconfigDATA
sudo make install
sudo make install-pkgconfigDATA
cd /pkgs



sudo echo "dconf iso-codes vala gtk2 gtk3 libnotify gtk4 gobject-introspection dbus-python pygobject3" > /pkgs/$PACKAGE/depends
echo "libdbusmenu" > /pkgs/$PACKAGE/make-depends
sudo echo "gtk-query-immodules-3.0 --update-cache" > /pkgs/$PACKAGE/postinst
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


