#!/bin/bash

PKG_VER=75.1
MAJOR=$(echo $PKG_VER | sed 's/\./-/g')
REFORMAT=$(echo $PKG_VER | sed 's/\./_/g')
URL=https://github.com/unicode-org/icu/releases/download/release-$MAJOR/icu4c-$REFORMAT-src.tgz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=icu
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

cd source
./configure --prefix=/usr


make -j22


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "libgcc" > /pkgs/$PACKAGE/depends
sudo echo "python clang" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


