#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

#TAG_OVERRIDE
PKG_VER=7.1.1-36
URL=https://github.com/ImageMagick/ImageMagick/archive/refs/tags/$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=ImageMagick-$PKG_VER
PACKAGE=imagemagick

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

./configure --prefix=/usr     \
            --sysconfdir=/etc \
            --enable-hdri     \
            --with-modules    \
            --with-perl       \
            --disable-static \


make -j20


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "xorg-libs lcms jasper libjpeg-turbo libpng libraw librsvg openjpeg libtool libheif" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


