#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"
#CURRENCY_TAG_OVERRIDE

PKG_VER=23.2.4
URL=https://github.com/intel/media-driver/archive/refs/tags/intel-media-$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=media-driver-$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=intel-media-driver

# Get Package

cd /blfs/builds
wget $URL
wget  https://www.linuxfromscratch.org/patches/blfs/svn/intel-media-driver-$PKG_VER-upstream_fixes-1.patch
tar -xvf $TAR
cd $DIR

# Build
patch -Np1 -i ../intel-media-driver-$PKG_VER-upstream_fixes-1.patch
mkdir build &&
cd    build &&

cmake -DCMAKE_INSTALL_PREFIX=/usr   \
      -DINSTALL_DRIVER_SYSCONF=OFF  \
      -DBUILD_TYPE=Release          \
      -DMEDIA_BUILD_FATAL_WARNINGS=OFF \
      -Wno-dev ..


make -j22


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "libva intel-gmmlib" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


