#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

set -e
# Last Validated Version 102.4

PKG_VER=102.15.1esr
REFORMAT=$(echo $PKG_VER | sed 's/esr//g')
URL=https://archive.mozilla.org/pub/firefox/releases/${PKG_VER}/source/firefox-${PKG_VER}.source.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=firefox-$REFORMAT
PACKAGE=js102

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
mkdir obj &&
cd    obj &&

sh ../js/src/configure.in --prefix=/usr            \
                          --with-intl-api          \
                          --with-system-zlib       \
                          --with-system-icu        \
                          --disable-jemalloc       \
                          --disable-debug-symbols  \
                          --enable-readline    
make -j20


# Install

make DESTDIR=/pkgs/$PACKAGE install
rm /pkgs/$PACKAGE/usr/lib/*.ajs
sudo echo "libgcc readline bash zlib icu" > /pkgs/$PACKAGE/depends
sudo echo "libgcc readline bash zlib autoconf213 clang llvm python3 rust zip git" > /pkgs/$PACKAGE/depends
cd /pkgs/$PACKAGE
sudo rm -rf root blfs
cd ..
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished
sudo cp -rpv /pkgs/$PACKAGE/* /


cd /blfs/builds
sudo rm -r $DIR


