#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

set -e

PKG_VER=0.3.1
URL=https://github.com/ksnip/kColorPicker/archive/refs/tags/v$PKG_VER/kColorPicker-$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=kColorPicker-$PKG_VER
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g'  |  tr '[:upper:]' '[:lower:]')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir build &&
cd    build &&

cmake -DCMAKE_INSTALL_PREFIX=/usr \
      -DCMAKE_BUILD_TYPE=Release         \
      -DBUILD_TESTING=OFF                \
      -DBUILD_SHARED_LIBS=ON \
      -DBUILD_WITH_QT6=ON \
      -Wno-dev .. &&


make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "kf6" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


