#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


PKG_VER=1.6.3
URL=http://deb.debian.org/debian/pool/main/k/keyutils/keyutils_$PKG_VER.orig.tar.gz
TAR=keyutils_$PKG_VER.orig.tar.gz
DIR=keyutils-$PKG_VER
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
sed -i 's:$(LIBDIR)/$(PKGCONFIG_DIR):/usr/lib/pkgconfig:' Makefile 



make -j16


# Install
sudo make NO_ARLIB=1 LIBDIR=/usr/lib BINDIR=/usr/bin SBINDIR=/usr/sbin DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "mitkrb" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


