#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"
#NLFS
PKG_VER=0.38.1
URL=https://github.com/kovidgoyal/kitty/releases/download/v$PKG_VER/kitty-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package
go env -w GO111MODULE=on
cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

python3 setup.py build


make -j16


# Install
python3 setup.py linux-package
mkdir -p /pkgs/$PACKAGE/usr
sudo cp -rpv linux-package/* /pkgs/$PACKAGE/usr/
cd /pkgs



sudo echo "xxhash librsync xorg freetype2 wayland" > /pkgs/$PACKAGE/depends
sudo echo "simde go ttf-nerd-fonts-symbols" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


