#!/bin/bash
URL=https://github.com/kovidgoyal/kitty/releases/download/v0.25.2/kitty-0.25.2.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

python3 setup.py build


make -j16


# Install
python3 setup.py linux-package
mkdir -p /pkgs/$PACKAGE/usr
sudo cp -rpv linux-package/* /pkgs/$PACKAGE/usr/
cd /pkgs



sudo echo "librsync xorg freetype2 wayland" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


