#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


PKG_VER=3.100
URL=https://downloads.sourceforge.net/lame/lame-$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

./configure --prefix=/usr --enable-mp3rtp --disable-static


make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE pkghtmldir=/usr/share/doc/lame-$PKG_VER install
sudo make pkghtmldir=/usr/share/doc/lame-$PKG_VER install
cd /pkgs



sudo echo "nasm libsndfile" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


