#!/bin/bash
set -e
export CFLAGS=-"O2"
export CXXFLAGS="-O2"
PKG_VER=1.6.0
MAJOR=$(echo $PKG_VER | sed 's|.[^.]*$||g')
URL=https://download.gnome.org/sources/libadwaita/$MAJOR/libadwaita-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build



mkdir build &&
cd    build &&


meson setup --prefix=/usr --buildtype=release .. &&


ninja


# Install
ninja install && DESTDIR=/pkgs/$PACKAGE ninja install
cd /pkgs


sudo echo "gtk4 vala appstream" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


