#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"
#ARCH_PKG=libaccounts-qt
#ARCH_VAR=pkgver
PKG_VER=1.17
URL=https://gitlab.com/accounts-sso/libaccounts-qt/-/archive/VERSION_$PKG_VER/libaccounts-qt-VERSION_$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=libaccounts-qt

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

qmake6 PREFIX=/usr LIBDIR=/usr/lib




make -j22


# Install
sudo make INSTALL_ROOT=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "libaccounts-glib glib qt6" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


