#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"
#ARCH_PKG=libaccounts-glib
#ARCH_VAR=pkgver
PKG_VER=1.27
URL=https://gitlab.com/accounts-sso/libaccounts-glib/-/archive/VERSION_$PKG_VER/libaccounts-glib-VERSION_$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=libaccounts-glib

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir build
cd build

meson setup -Dprefix=/usr --buildtype=release

ninja


# Install
sudo  DESTDIR=/pkgs/$PACKAGE ninja install
sudo ninja install
cd /pkgs



sudo echo "glib sqlite libxml2" > /pkgs/$PACKAGE/depends
sudo echo "pygobject3 python-packaging vala check gobject-introspection gtk-doc" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


