#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

# Uncomment Glibc 2.36 below

PKG_VER=3.7.7
URL=https://github.com/libarchive/libarchive/releases/download/v$PKG_VER/libarchive-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
# Glibc 2.36
./configure --prefix=/usr --disable-static


make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sed -i "s/iconv //" /pkgs/$PACKAGE/usr/lib/pkgconfig/libarchive.pc
cp -rpv /pkgs/$PACKAGE/* /
cd /pkgs



sudo echo "libxml2" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


