#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"
set -e

PKG_VER=2.1.0
URL=https://ftp.gnu.org/gnu/libcdio/libcdio-$PKG_VER.tar.bz2
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
wget https://ftp.gnu.org/gnu/libcdio/libcdio-paranoia-10.2+2.0.1.tar.bz2
tar -xvf $TAR
cd $DIR

# Build
./configure --prefix=/usr --disable-static
make -j20


tar -xf ../libcdio-paranoia-10.2+2.0.1.tar.bz2 &&
cd libcdio-paranoia-10.2+2.0.1 &&

./configure --prefix=/usr --disable-static 


make -j16


# Install
cd ../

sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
pwd
cd "libcdio-paranoia-10.2+2.0.1"
make DESTDIR=/pkgs/$PACKAGE install
cd /pkgs



sudo echo "" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


