#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"
PKG_VER=1.10.3
URL=https://www.gnupg.org/ftp/gcrypt/libgcrypt/libgcrypt-$PKG_VER.tar.bz2
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

./configure --prefix=/usr


make -j16



make -C doc html                                                       &&
makeinfo --html --no-split -o doc/gcrypt_nochunks.html doc/gcrypt.texi &&
makeinfo --plaintext       -o doc/gcrypt.txt           doc/gcrypt.texi


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install

install -v -dm755   /pkgs/$PACKAGE/usr/share/doc/libgcrypt-1.10.1 &&
install -v -m644    README doc/{README.apichanges,fips*,libgcrypt*} \
                    /pkgs/$PACKAGE/usr/share/doc/libgcrypt-1.10.1 &&

install -v -dm755   /pkgs/$PACKAGE/usr/share/doc/libgcrypt-1.10.1/html &&
install -v -m644 doc/gcrypt.html/* \
                    /pkgs/$PACKAGE/usr/share/doc/libgcrypt-1.10.1/html &&
install -v -m644 doc/gcrypt_nochunks.html \
                    /pkgs/$PACKAGE/usr/share/doc/libgcrypt-1.10.1      &&
install -v -m644 doc/gcrypt.{txt,texi} \
                    /pkgs/$PACKAGE/usr/share/doc/libgcrypt-1.10.1

cd /pkgs



sudo echo "libgpg-error" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


# Method 2 Install
cp -rpv $PACKAGE/* /

cd /blfs/builds
sudo rm -r $DIR


