#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

URL=https://github.com/strukturag/libheif/releases/download/v1.15.1/libheif-1.15.1.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')
set -e
# Get Package
go env -w GO111MODULE=off
cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

./autogen.sh
./configure --prefix=/usr --enable-static=no


make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "ffmpeg libde265" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


