#!/bin/bash
URL=https://download.gnome.org/sources/libhandy/1.6/libhandy-1.6.3.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')
set -e

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir build &&
cd    build &&


meson --prefix=/usr --buildtype=release ..

ninja


# Install
ninja install && DESTDIR=/pkgs/$PACKAGE ninja install
cd /pkgs


sudo echo "vala gtk3" > /pkgs/$PACKAGE/depends
sudo rm -rf /pkgs/$PACKAGE/blfs
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


