#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "
PKG_VER=2.0.3
URL=https://downloads.sourceforge.net/libmng/libmng-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build


./configure --prefix=/usr --disable-static

make -j22


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
install -v -m755 -d        /pkgs/$PACKAGE/usr/share/doc/libmng &&
install -v -m644 doc/*.txt /pkgs/$PACKAGE/usr/share/doc/libmng
sudo make install
cd /pkgs



sudo echo "lcms libjpeg-turbo" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


