#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

GNOME_MAJOR=43
GNOME_MINOR=0

PKG_VER=1.3.0
MAJOR=$(echo $PKG_VER | sed 's|.[^.]*$||g')
URL=https://download.gnome.org/sources/libshumate/$MAJOR/libshumate-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
dot -c
mkdir build &&
cd    build &&

meson setup --prefix=/usr --buildtype=release --wrap-mode=nodownload ..


ninja 


# Install
ninja install
DESTDIR=/pkgs/$PACKAGE ninja install
cd /pkgs


sudo echo "gtk4 libsoup3 sqlite" > /pkgs/$PACKAGE/depends
sudo echo "protobuf-c json-glib librsvg" > /pkgs/$PACKAGE/make-depends
sudo echo "glib-compile-schemas /usr/share/glib-2.0/schemas" > /pkgs/$PACKAGE/postinst
sudo rm -rf /pkgs/$PACKAGE/blfs
sudo tar -cvpzf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


