#!/bin/bash
set -e
URL=https://github.com/CanonicalLtd/lightdm/releases/download/1.32.0/lightdm-1.32.0.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

getent passwd lightdm > /dev/null

if [ $? -eq 0 ]; then
    :
else
  groupadd -g 65 lightdm       &&
  useradd  -c "Lightdm Daemon" \
           -d /var/lib/lightdm \
           -u 65 -g lightdm    \
           -s /bin/false lightdm
fi

# Get Package

cd /blfs/builds
wget $URL
wget https://github.com/Xubuntu/lightdm-gtk-greeter/releases/download/lightdm-gtk-greeter-2.0.8/lightdm-gtk-greeter-2.0.8.tar.gz
wget https://www.linuxfromscratch.org/blfs/downloads/systemd/blfs-systemd-units-20220720.tar.xz
tar -xvf $TAR
cd $DIR

# Build
./configure --prefix=/usr                 \
            --libexecdir=/usr/lib/lightdm \
            --localstatedir=/var          \
            --sbindir=/usr/bin            \
            --sysconfdir=/etc             \
            --disable-static              \
            --disable-tests               \
            --with-greeter-user=lightdm   \
            --with-greeter-session=lightdm-gtk-greeter \
            --docdir=/usr/share/doc/lightdm-1.32.0



make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
mkdir -p /pkgs/$PACKAGE/usr/bin
cp tests/src/lightdm-session /pkgs/$PACKAGE/usr/bin                         &&
sed -i '1 s/sh/bash --login/' /pkgs/$PACKAGE//usr/bin/lightdm-session        &&
rm -rf /etc/init                                              &&
install -v -dm755 -o lightdm -g lightdm /pkgs/$PACKAGE/var/lib/lightdm      &&
install -v -dm755 -o lightdm -g lightdm /pkgs/$PACKAGE/var/lib/lightdm-data &&
install -v -dm755 -o lightdm -g lightdm /pkgs/$PACKAGE/var/cache/lightdm    &&
install -v -dm770 -o lightdm -g lightdm /pkgs/$PACKAGE/var/log/lightdm


tar -xf ../lightdm-gtk-greeter-2.0.8.tar.gz &&
cd lightdm-gtk-greeter-2.0.8 &&

./configure --prefix=/usr                 \
            --libexecdir=/usr/lib/lightdm \
            --sbindir=/usr/bin            \
            --sysconfdir=/etc             \
            --with-libxklavier            \
            --enable-kill-on-sigterm      \
            --disable-libido              \
            --disable-libindicator        \
            --disable-static              \
            --disable-maintainer-mode     \
            --docdir=/usr/share/doc/lightdm-gtk-greeter-2.0.8 &&
make

make DESTDIR=/pkgs/$PACKAGE install

tar -xf /blfs/builds/blfs-systemd-units-20220720.tar.xz
cd blfs-systemd-units-20220720
make DESTDIR=/pkgs/$PACKAGE install-lightdm



cd /pkgs



sudo echo "exo libgcrypt itstool gobject-introspection vala libxklavier accounts-service inetutils" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished

sudo cp -rpv /pkgs/$PACKAGE/* /


cd /blfs/builds
sudo rm -r $DIR


