#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"
PKG_VER=20230515
URL=https://cdn.kernel.org/pub/linux/kernel/firmware/linux-firmware-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
wget https://src.fedoraproject.org/rpms/linux-firmware/raw/rawhide/f/0001-Add-support-for-compressing-firmware-in-copy-firmwar.patch
tar -xvf $TAR
cd $DIR

# Build
patch -Np1 < ../0001-Add-support-for-compressing-firmware-in-copy-firmwar.patch

# no building required


# Install
sudo make DESTDIR=/pkgs/$PACKAGE FIRMWAREDIR=/usr/lib/firmware installcompress
sudo make install
cd /pkgs



sudo echo "linux-tucana" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


