#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


PKG_VER=0.9.31
URL=https://github.com/LMDB/lmdb/archive/LMDB_$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=lmdb-$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=lmdb

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

cd libraries/liblmdb &&
make  -j36               &&
sed -i 's| liblmdb.a||' Makefile



# Install
sudo make prefix=/usr DESTDIR=/pkgs/$PACKAGE install
cd /pkgs



sudo echo "" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished
sudo cp -rpv /pkgs/$PACKAGE/* /

cd /blfs/builds
sudo rm -r $DIR


