#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"
set -e

PKG_VER=4.99.3
URL=https://github.com/lsof-org/lsof/archive/refs/tags/$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=lsof-$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=lsof

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

autoreconf -fiv
./configure --prefix=/usr

make -j16


# Install
mkdir -p /pkgs/$PACKAGE/usr/share/man/man8
mkdir -p /pkgs/$PACKAGE/usr/bin
install -vD -m4755 -o root -g root lsof /pkgs/$PACKAGE/usr/bin &&

cd /pkgs



sudo echo "" > /pkgs/$PACKAGE/depends
sudo echo "groff" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


