#!/bin/bash
URL=https://github.com/lsof-org/lsof/releases/download/4.95.0/lsof_4.95.0.linux.tar.bz2
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=lsof

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

./Configure -n linux


make -j16


# Install
mkdir -p /pkgs/$PACKAGE/usr/share/man/man8
mkdir -p /pkgs/$PACKAGE/usr/bin
install -vD -m4755 -o root -g root lsof /pkgs/$PACKAGE/usr/bin &&
install -vD lsof.8 /pkgs/$PACKAGE/usr/share/man/man8

cd /pkgs



sudo echo "" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


