#!/bin/bash
export CFLAGS=-"O2"
export CXXFLAGS="-O2"

URL=https://github.com/lz4/lz4/archive/refs/tags/v1.9.4.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=lz4-1.9.4
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build



make -j22


# Install
sudo make PREFIX=/usr DESTDIR=/pkgs/$PACKAGE install
sudo make PREFIX=/usr install
cd /pkgs



sudo echo "" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


