#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"
set -e
#ARCH_PKG=mariadb
#ARCH_VAR=pkgver
PKG_VER=11.6.2
URL=https://rsync.osuosl.org/pub/mariadb/mariadb-$PKG_VER/source/mariadb-$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')
BLFS_SYSTEMD_VER=20241211
# Get Package


cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir build &&
cd    build &&

cmake -DCMAKE_BUILD_TYPE=Release                      \
      -DCMAKE_INSTALL_PREFIX=/usr                     \
      -DINSTALL_DOCDIR=share/doc/mariadb-$PKG_VER       \
      -DINSTALL_DOCREADMEDIR=share/doc/mariadb-$PKG_VER \
      -DINSTALL_MANDIR=share/man                      \
      -DINSTALL_MYSQLSHAREDIR=share/mariadb             \
      -DINSTALL_MYSQLTESTDIR=share/mariadb/test         \
      -DINSTALL_PLUGINDIR=lib/mariadb/plugin            \
      -DINSTALL_SBINDIR=sbin                          \
      -DINSTALL_SCRIPTDIR=bin                         \
      -DINSTALL_SQLBENCHDIR=share/mariadb/bench         \
      -DINSTALL_SUPPORTFILESDIR=share/mariadb           \
      -DMYSQL_DATADIR=/srv/mariadb                      \
      -DMYSQL_UNIX_ADDR=/run/mariadb/mariadb.sock       \
      -DWITH_EXTRA_CHARSETS=complex                   \
      -DWITH_EMBEDDED_SERVER=ON                       \
      -DSKIP_TESTS=ON                                 \
      -DTOKUDB_OK=0                                   \
      .. 


make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
cd /pkgs

install -v -dm 755 /pkgs/$PACKAGE/etc/mariadb &&
cat > /pkgs/$PACKAGE/etc/mariadb/my.cnf << "EOF"
# Begin /etc/mariadb/my.cnf

# The following options will be passed to all MySQL clients
[client]
#password       = your_password
port            = 3306
socket          = /run/mariadb/mariadb.sock

# The MySQL server
[mariadb]
port            = 3306
socket          = /run/mariadb/mariadb.sock
datadir         = /srv/mariadb
skip-external-locking
key_buffer_size = 16M
max_allowed_packet = 1M
sort_buffer_size = 512K
net_buffer_length = 16K
myisam_sort_buffer_size = 8M

# Don't listen on a TCP/IP port at all.
skip-networking

# required unique id between 1 and 2^32 - 1
server-id       = 1

# Uncomment the following if you are using BDB tables
#bdb_cache_size = 4M
#bdb_max_lock = 10000

# InnoDB tables are now used by default
innodb_data_home_dir = /srv/mariadb
innodb_log_group_home_dir = /srv/mariadb
# All the innodb_xxx values below are the default ones:
innodb_data_file_path = ibdata1:12M:autoextend
# You can set .._buffer_pool_size up to 50 - 80 %
# of RAM but beware of setting memory usage too high
innodb_buffer_pool_size = 128M
innodb_log_file_size = 48M
innodb_log_buffer_size = 16M
innodb_flush_log_at_trx_commit = 1
innodb_lock_wait_timeout = 50

[mariadbdump]
quick
max_allowed_packet = 16M

[mariadb]
no-auto-rehash
# Remove the next comment character if you are not familiar with SQL
#safe-updates

[isamchk]
key_buffer = 20M
sort_buffer_size = 20M
read_buffer = 2M
write_buffer = 2M

[myisamchk]
key_buffer_size = 20M
sort_buffer_size = 20M
read_buffer = 2M
write_buffer = 2M

[mariadbhotcopy]
interactive-timeout

# End /etc/mariadb/my.cnf
EOF
cp -rpv /pkgs/$PACKAGE/* /
# Install systemd unit
cd /blfs/builds
wget https://www.linuxfromscratch.org/blfs/downloads/systemd/blfs-systemd-units-$BLFS_SYSTEMD_VER.tar.xz
tar -xvf blfs-systemd-units-$BLFS_SYSTEMD_VER.tar.xz
cd blfs-systemd-units-$BLFS_SYSTEMD_VER
make DESTDIR=/pkgs/mariadb install-mariadb
# Done
cd /pkgs

sudo rm -rf /pkgs/$PACKAGE/usr/share/mariadb/test
rm /pkgs/$PACKAGE/usr/lib/*.a

sudo echo "bzip2 libxml2 lz4 systemd" > /pkgs/$PACKAGE/depends
sudo echo 'groupadd -g 40 mariadb &&
useradd -c "MariaDB Server" -d /srv/mariadb -g mariadb -s /bin/false -u 40 mariadb' > /pkgs/$PACKAGE/postinst
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished

# Install onto host
sudo cp -rpv /pkgs/mariadb/* /

cd /blfs/builds
sudo rm -r $DIR


