#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


PKG_VER=24.3.1
URL=https://archive.mesa3d.org/mesa-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')
set -e
# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
export CFLAGS="-O2"
export CXXFLAGS="-O2"
mkdir build
cd build

meson setup --prefix=/usr   \
      --buildtype=release     \
    -Dplatforms=x11,wayland \
    -Dgallium-drivers=r300,r600,radeonsi,nouveau,virgl,svga,swrast,i915,iris,crocus,zink,d3d12 \
    -Dvulkan-drivers=amd,intel,intel_hasvk,swrast,virtio \
    -Dvulkan-layers=device-select,intel-nullhw,overlay \
    -Degl=enabled \
    -Dgallium-extra-hud=true \
    -Dgallium-nine=true \
    -Dgallium-va=enabled \
    -Dgallium-vdpau=enabled \
    -Dgallium-xa=enabled \
    -Drust_std=2021 \
    -Dgbm=enabled \
    -Dgles1=disabled \
    -Dgles2=enabled \
    -Dglvnd=true \
    -Dglx=dri \
    -Dlibunwind=enabled \
    -Dllvm=enabled \
    -Dlmsensors=enabled \
    -Dosmesa=true \
    -Dshared-glapi=enabled \
    -Dmicrosoft-clc=disabled \
    -Dvideo-codecs=h264dec,h264enc,h265dec,h265enc,vc1dec \
      ..             


ninja


# Install
sudo  DESTDIR=/pkgs/$PACKAGE ninja install
sudo ninja install
install -v -dm755 /pkgs/$PACKAGE/usr/share/doc/mesa
cp -rfv ../docs/*  /pkgs/$PACKAGE/usr/share/doc/mesa
cd /pkgs



sudo echo "wayland-protocols libva libglvnd llvm libvdpau libdrm mako xorg-libs libvulkan lm-sensors" > /pkgs/$PACKAGE/depends
sudo echo "pyyaml libunwind wayland-protocols libva llvm glslang vulkan-headers libvulkan libvdpau libdrm mako xorg-libs glslang meson lm-sensors zstd libdrm cmake python-ply libclc rust-bindgen cbindgen" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


