#!/bin/bash
URL=https://archive.mesa3d.org/mesa-22.2.3.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')
set -e
# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir build
cd build


meson --prefix=/usr   \
      --buildtype=release     \
      -Dplatforms=x11,wayland \
      -Dgallium-drivers=auto  \
      -Dglx=dri               \
      -Dvalgrind=disabled     \
      -Dlibunwind=disabled    \
      -Dvulkan-drivers=amd,intel,swrast \
      -Dvulkan-layers=device-select,intel-nullhw,overlay \
      ..             


ninja


# Install
sudo  DESTDIR=/pkgs/$PACKAGE ninja install
sudo ninja install
install -v -dm755 /pkgs/$PACKAGE/usr/share/doc/mesa
cp -rfv ../docs/*  /pkgs/$PACKAGE/usr/share/doc/mesa
cd /pkgs



sudo echo "wayland-protocols libva llvm libvdpau libdrm mako xorg-libs libvulkan" > /pkgs/$PACKAGE/depends
sudo echo "wayland-protocols libva llvm libvdpau libdrm mako xorg-libs glslang meson lm-sensors zstd libdrm cmake" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


