#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


PKG_VER=9.0.0
URL=https://archive.mesa3d.org/demos/$PKG_VER/mesa-demos-$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=mesa-utils

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir build
cd build

meson --prefix=/usr -Dgles1=disabled ..

ninja


# Install
mkdir -p /pkgs/$PACKAGE/usr/bin
DESTDIR=$PWD/temp ninja install
sudo cp $PWD/temp/usr/bin/glxinfo /pkgs/$PACKAGE/usr/bin
sudo cp $PWD/temp/usr/bin/glxgears /pkgs/$PACKAGE/usr/bin
cd /pkgs



sudo echo "mesa" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


