#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "
PKG_VER=1.26.2
URL=https://nginx.org/download/nginx-$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
# attempting to clone debian and arch's locations
# all credit to arch for these options
./configure \
    --prefix=/etc/nginx \
    --conf-path=/etc/nginx/nginx.conf \
    --sbin-path=/usr/bin/nginx \
    --pid-path=/run/nginx.pid \
    --lock-path=/run/lock/nginx.lock \
    --user=http \
    --group=http \
    --http-log-path=/var/log/nginx/access.log \
    --error-log-path=stderr \
    --http-client-body-temp-path=/var/lib/nginx/client-body \
    --http-proxy-temp-path=/var/lib/nginx/proxy \
    --http-fastcgi-temp-path=/var/lib/nginx/fastcgi \
    --http-scgi-temp-path=/var/lib/nginx/scgi \
    --http-uwsgi-temp-path=/var/lib/nginx/uwsgi \
    --with-cc-opt="$CFLAGS $CPPFLAGS" \
    --with-ld-opt="$LDFLAGS" \
    --with-compat \
    --with-debug \
    --with-file-aio \
    --with-http_addition_module \
    --with-http_auth_request_module \
    --with-http_dav_module \
    --with-http_degradation_module \
    --with-http_flv_module \
    --with-http_gunzip_module \
    --with-http_gzip_static_module \
    --with-http_mp4_module \
    --with-http_random_index_module \
    --with-http_realip_module \
    --with-http_secure_link_module \
    --with-http_slice_module \
    --with-http_ssl_module \
    --with-http_stub_status_module \
    --with-http_sub_module \
    --with-http_v2_module \
    --with-http_v3_module \
    --with-pcre-jit \
    --with-stream \
    --with-stream_realip_module \
    --with-stream_ssl_module \
    --with-stream_ssl_preread_module \
    --with-threads




make -j22


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
mkdir -p /pkgs/$PACKAGE/var/lib/nginx
install -dm700 /pkgs/$PACKAGE/var/lib/nginx/proxy

chmod -R 755 /pkgs/$PACKAGE/var/log/nginx

mkdir -p /pkgs/$PACKAGE/usr/share/nginx
mv /pkgs/$PACKAGE/etc/nginx/html /pkgs/$PACKAGE/usr/share/nginx
rm -r /pkgs/$PACKAGE/run
install -Dm644 objs/nginx.8 /pkgs/$PACKAGE/usr/share/man/man8/nginx.8
rm /pkgs/$PACKAGE/etc/nginx/*.default

mkdir -p /pkgs/$PACKAGE/usr/lib/systemd/system
cat > /pkgs/$PACKAGE/usr/lib/systemd/system/nginx.service << EOF
[Unit]
Description=An HTTP web server, reverse proxy, content cache, load balancer, TCP/UDP proxy server,
After=network-online.target remote-fs.target nss-lookup.target
Wants=network-online.target

[Service]
type=forking
PIDFile=/run/nginx.pid
ExecStart=/usr/bin/nginx
ExecReload=/usr/bin/nginx -s reload
Restart=on-failure
KillSignal=SIQQUIT

[Install]
WantedBy=multi-user.target

EOF

cd /pkgs

echo 'groupadd -g 26 http &&
useradd -c "nginx user" -d /usr/share/nginx -g http \
        -s /bin/false -u 26 http' > /pkgs/$PACKAGE/postinst


sudo echo "glib pcre zlib openssl" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


