#!/bin/bash
URL=https://github.com/jp9000/obs-studio/archive/29.0.2.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=obs-studio-$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')
set -e

# Get Package
# Arch patch
cd /blfs/builds
wget https://raw.githubusercontent.com/archlinux/svntogit-community/packages/obs-studio/trunk/ignore_unused_submodules.patch
wget $URL
tar -xvf $TAR
cd $DIR

# Build
patch -Np1 < ../ignore_unused_submodules.patch
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr \
    -DENABLE_BROWSER=OFF \
    -DENABLE_VLC=OFF \
    -DENABLE_NEW_MPEGTS_OUTPUT=OFF \
    -DENABLE_AJA=OFF \
    -Wno-dev ..



make -j20


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "qt5 ffmpeg luajit llvm xorg" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


