#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"
PKG_VER=30.2.2
set -e
URL=https://github.com/obsproject/obs-studio/archive/refs/tags/$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=obs-studio-$PKG_VER
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget https://raw.githubusercontent.com/archlinux/svntogit-community/packages/obs-studio/trunk/ignore_unused_submodules.patch
wget https://src.fedoraproject.org/rpms/obs-studio/raw/rawhide/f/obs-studio-fix-incompatible-pointer-type.patch
wget $URL
tar -xvf $TAR
cd $DIR

# Build

patch -Np1 < ../ignore_unused_submodules.patch
patch -Np1 < ../obs-studio-fix-incompatible-pointer-type.patch
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr \
    -DENABLE_BROWSER=OFF \
    -DENABLE_VLC=OFF \
    -DENABLE_NEW_MPEGTS_OUTPUT=OFF \
    -DENABLE_AJA=OFF \
    -DENABLE_VST=OFF \
    -DENABLE_QSV11=OFF \
    -DENABLE_WEBRTC=OFF \
    -DCALM_DEPRECATION=on \
    -Wno-dev ..


make -j22


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "qt6 ffmpeg luajit llvm xorg" > /pkgs/$PACKAGE/depends
sudo echo "swig" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


