#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"
PKG_VER=31.0.0
set -e
URL=https://github.com/obsproject/obs-studio/releases/download/$PKG_VER/OBS-Studio-$PKG_VER-Sources.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=obs-studio-$PKG_VER-sources
PACKAGE=obs-studio

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build


mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr \
    -DENABLE_BROWSER=OFF \
    -DENABLE_VLC=OFF \
    -DENABLE_NEW_MPEGTS_OUTPUT=OFF \
    -DENABLE_AJA=OFF \
    -DENABLE_WEBSOCKET=OFF \
    -DENABLE_VST=OFF \
    -DENABLE_QSV11=OFF \
    -DENABLE_WEBRTC=OFF \
    -DCALM_DEPRECATION=on \
    -Wno-dev ..


make -j22


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "uthash qt6 ffmpeg luajit llvm xorg" > /pkgs/$PACKAGE/depends
sudo echo "swig" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


