#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"
set -e
PKG_VER=2.4.0
URL=https://github.com/uclouvain/openjpeg/archive/v$PKG_VER/openjpeg-$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build



mkdir -v build &&
cd       build &&

cmake -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DBUILD_STATIC_LIBS=OFF ..


make -j22


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install

pushd ../doc &&
  for man in man/man?/* ; do
      install -v -D -m 644 $man /pkgs/$PACKAGE/usr/share/$man
  done
popd

cd /pkgs

cp -rpv /pkgs/$PACKAGE/* /

sudo echo "" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


