#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"
PKG_VER=2.6.6
URL=https://www.openldap.org/software/download/OpenLDAP/openldap-release/openldap-$PKG_VER.tgz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tgz||g')
PACKAGE=openldap
PACKAGE1=openldap-client
PACKAGE2=slapd
set -e
# Client
# Get Package

cd /blfs/builds
wget $URL
wget  https://www.linuxfromscratch.org/patches/blfs/svn/openldap-$PKG_VER-consolidated-1.patch
tar -xvf $TAR
cd $DIR

# Build
autoconf

patch -Np1 -i ../openldap-$PKG_VER-consolidated-1.patch &&
./configure --prefix=/usr     \
            --sysconfdir=/etc \
            --disable-static  \
            --enable-dynamic  \
            --enable-versioning=yes  \
            --disable-debug   \
            --disable-slapd \


make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE1 install
sudo make install
cd /pkgs



sudo echo "glibc pam cyrus-sasl" > /pkgs/$PACKAGE1/depends
sudo echo "" > /pkgs/$PACKAGE1/make-depends
sudo tar -cvzpf $PACKAGE1.tar.xz $PACKAGE1
sudo cp $PACKAGE1.tar.xz /finished


cd /blfs/builds
cd $DIR

# Cleanup
make distclean -j20

# Build the Server

autoconf &&

./configure --prefix=/usr         \
            --sysconfdir=/etc     \
            --localstatedir=/var  \
            --libexecdir=/usr/lib \
            --disable-static      \
            --enable-versioning=yes \
            --disable-debug       \
            --with-tls=openssl    \
            --with-cyrus-sasl     \
            --enable-dynamic      \
            --enable-crypt        \
            --enable-spasswd      \
            --enable-slapd        \
            --enable-modules      \
            --enable-rlookups     \
            --enable-backends=mod \
            --disable-sql         \
            --disable-wt          \
            --enable-overlays=mod

make depend -j20
make -j20

# Install
sudo make DESTDIR=/pkgs/$PACKAGE2 install
sudo echo "mariadb cyrus-sasl pam coreutils iproute2" > /pkgs/$PACKAGE2/depends
sudo echo "groff" > /pkgs/$PACKAGE2/make-depends
sudo echo "" > /pkgs/$PACKAGE2/make-depends
cd /pkgs

sudo tar -cvzpf $PACKAGE2.tar.xz $PACKAGE2
sudo cp $PACKAGE2.tar.xz /finished

cd /blfs/builds/
rm -rf $DIR
# Meta
cd /pkgs
mkdir -p $PACKAGE/var/cache/mercury/meta-pkgs
# Most of the time you only need the client
echo "openldap-client" > $PACKAGE/var/cache/mercury/meta-pkgs/openldap
echo "openldap-client" > $PACKAGE/depends
tar -cvzpf $PACKAGE.tar.xz $PACKAGE
cp $PACKAGE.tar.xz /finished
