#!/bin/bash
#NLFS
export CFLAGS=-"O2"
export CXXFLAGS="-O2"
#TAG_OVERRIDE
#ARCH_PKG=openal
#ARCH_VAR=pkgver
PKG_VER=1.24.0
URL=https://github.com/kcat/openal-soft/archive/refs/tags/$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=openal-soft-$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=openal

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir build
cd build

cmake -DCMAKE_INSTALL_PREFIX=/usr ..


make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "libgcc" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


