#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"
PKG_VER=3.6
URL=https://ftp.gnu.org/gnu/parted/parted-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

./configure --prefix=/usr --disable-static &&

make -j22
make -C doc html                                       &&
makeinfo --html      -o doc/html       doc/parted.texi &&
makeinfo --plaintext -o doc/parted.txt doc/parted.texi

# Install
sudo make DESTDIR=/pkgs/$PACKAGE install

install -v -m755 -d /usr/share/doc/parted-$PKG_VER/html &&
install -v -m644    doc/html/* \
                    /usr/share/doc/parted-$PKG_VER/html &&
install -v -m644    doc/{FAT,API,parted.{txt,html}} \
                    /usr/share/doc/parted-$PKG_VER
sudo make install
cd /pkgs



sudo echo "lvm" > /pkgs/$PACKAGE/depends
sudo echo "texinfo" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


