#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


PKG_VER=27.2
URL=https://github.com/protocolbuffers/protobuf/releases/download/v$PKG_VER/protobuf-$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir build
cd build


cmake -DCMAKE_INSTALL_PREFIX=/usr      \
      -DCMAKE_BUILD_TYPE=Release       \
      -DCMAKE_SKIP_INSTALL_RPATH=ON    \
      -Dprotobuf_BUILD_TESTS=OFF       \
      -Dprotobuf_ABSL_PROVIDER=package \
      -Dprotobuf_BUILD_LIBUPB=OFF      \
      -Dprotobuf_BUILD_SHARED_LIBS=ON  \
      -Dutf8_range_ENABLE_INSTALL=OFF  \
      -G Ninja ..

ninja


# Install
sed 's/utf8_range//' -i *.pc
sudo  DESTDIR=/pkgs/$PACKAGE ninja install
sudo ninja install
cd /pkgs



sudo echo "abseil-cpp" > /pkgs/$PACKAGE/depends
sudo echo "cmake" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


