#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"
PKG_VER=3.5.6
URL=https://github.com/MeVisLab/pythonqt/archive/refs/tags/v$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=pythonqt-$PKG_VER
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build


qmake-qt5 PYTHON_VERSION=$(python -c 'import sys; print(".".join(sys.version.split(".")[:2]))')

make -j22


# Install
sudo make INSTALL_ROOT=/pkgs/$PACKAGE/usr install

mkdir -p /pkgs/$PACKAGE/usr/include/PythonQt/{gui,extensions/PythonQt_QtAll}
cp -p src/*.h /pkgs/$PACKAGE/usr/include/PythonQt
cp -rp src/gui/*.h /pkgs/$PACKAGE/usr/include/PythonQt/gui
cp extensions/PythonQt_QtAll/*.h /pkgs/$PACKAGE/usr/include/PythonQt/extensions/PythonQt_QtAll/

mkdir -p /pkgs/$PACKAGE/usr/lib
cp -a lib/*.so /pkgs/$PACKAGE/usr/lib/
cd /pkgs



sudo echo "python qt5" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


