#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"
PKG_VER=3.4.2
URL=https://github.com/MeVisLab/pythonqt/archive/refs/tags/v$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=pythonqt-$PKG_VER
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build


qmake-qt5 PYTHON_VERSION=$(python -c 'import sys; print(".".join(sys.version.split(".")[:2]))')

make -j22


# Install
sudo make INSTALL_ROOT=/pkgs/$PACKAGE/usr install
sudo make install
cd /pkgs



sudo echo "python qt5" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


