#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"
#ARCH_PKG=qt5-base
#ARCH_VAR=_basever
PKG_VER=5.15.14
URL=https://download.qt.io/archive/qt/5.15/$PKG_VER/single/qt-everywhere-opensource-src-$PKG_VER.tar.xz
TAR=qt-everywhere-opensource-src-$PKG_VER.tar.xz
DIR=qt-everywhere-src-$PKG_VER
PACKAGE=qt5
# Get Package
set -e
cd /blfs/builds
wget https://raw.githubusercontent.com/xXTeraXx/Tucana/main/mercury/patches/qt-5.15.14-kde.patch
wget https://raw.githubusercontent.com/xXTeraXx/Tucana/main/mercury/patches/qt-gcc14.patch
wget $URL
tar -xvf $TAR
cd $DIR

# Build

patch -Np1 -i ../qt-5.15.14-kde.patch
patch -Np1 -i ../qt-gcc14.patch
mkdir -pv qtbase/.git
sed -e "/pragma once/a#include <cstdint>"                                      \
    -i qtlocation/src/3rdparty/mapbox-gl-native/include/mbgl/util/geometry.hpp \
       qtlocation/src/3rdparty/mapbox-gl-native/include/mbgl/util/string.hpp   \
       qtlocation/src/3rdparty/mapbox-gl-native/src/mbgl/gl/stencil_mode.hpp
sed -e "/c++1z/s;^CONFIG;#CONFIG;" \
    -e "s;c++14;c++17;"            \
    -i qtlocation/src/3rdparty/mapbox-gl-native/mapbox-gl-native.pro
./configure -prefix /usr                              \
            -sysconfdir /etc/xdg                      \
            -confirm-license                          \
            -opensource                               \
            -dbus-linked                              \
            -openssl-linked                           \
            -system-harfbuzz                          \
            -system-sqlite                            \
            -nomake examples                          \
            -no-rpath                                 \
            -journald                                 \
            -skip qtwebengine                         \
            -archdatadir    /usr/lib/qt5                \
            -bindir         /usr/bin                    \
            -plugindir      /usr/lib/qt5/plugins        \
            -importdir      /usr/lib/qt5/imports        \
            -headerdir      /usr/include/qt5            \
            -datadir        /usr/share/qt5              \
            -docdir         /usr/share/doc/qt5          \
            -translationdir /usr/share/qt5/translations \
            -examplesdir    /usr/share/doc/qt5/examples
make -j20



# Install


make INSTALL_ROOT=/pkgs/$PACKAGE install

# Remove the references to the build directory in the perl files
find /pkgs/$PACKAGE/usr/ -name \*.prl \
   -exec sed -i -e '/^QMAKE_PRL_BUILD_DIR/d' {} \;

# Create the .desktop files


install -v -dm755 /pkgs/$PACKAGE/usr/share/pixmaps/                  &&

install -v -Dm644 qttools/src/assistant/assistant/images/assistant-128.png \
                  /pkgs/$PACKAGE/usr/share/pixmaps/assistant-qt5.png &&

install -v -Dm644 qttools/src/designer/src/designer/images/designer.png \
                  /pkgs/$PACKAGE/usr/share/pixmaps/designer-qt5.png  &&

install -v -Dm644 qttools/src/linguist/linguist/images/icons/linguist-128-32.png \
                  /pkgs/$PACKAGE/usr/share/pixmaps/linguist-qt5.png  &&

install -v -Dm644 qttools/src/qdbus/qdbusviewer/images/qdbusviewer-128.png \
                  /pkgs/$PACKAGE/usr/share/pixmaps/qdbusviewer-qt5.png &&

install -dm755 /pkgs/$PACKAGE/usr/share/applications &&

cat > /pkgs/$PACKAGE/usr/share/applications/assistant-qt5.desktop << EOF
[Desktop Entry]
Name=Qt5 Assistant
Comment=Shows Qt5 documentation and examples
Exec=/usr/bin/assistant
Icon=assistant-qt5.png
Terminal=false
Encoding=UTF-8
Type=Application
Categories=Qt;Development;Documentation;
EOF

cat > /pkgs/$PACKAGE/usr/share/applications/designer-qt5.desktop << EOF
[Desktop Entry]
Name=Qt5 Designer
GenericName=Interface Designer
Comment=Design GUIs for Qt5 applications
Exec=/usr/bin/designer
Icon=designer-qt5.png
MimeType=application/x-designer;
Terminal=false
Encoding=UTF-8
Type=Application
Categories=Qt;Development;
EOF

cat > /pkgs/$PACKAGE/usr/share/applications/linguist-qt5.desktop << EOF
[Desktop Entry]
Name=Qt5 Linguist
Comment=Add translations to Qt5 applications
Exec=/usr/bin/linguist
Icon=linguist-qt5.png
MimeType=text/vnd.trolltech.linguist;application/x-linguist;
Terminal=false
Encoding=UTF-8
Type=Application
Categories=Qt;Development;
EOF

cat > /pkgs/$PACKAGE/usr/share/applications/qdbusviewer-qt5.desktop << EOF
[Desktop Entry]
Name=Qt5 QDbusViewer
GenericName=D-Bus Debugger
Comment=Debug D-Bus applications
Exec=/usr/bin/qdbusviewer
Icon=qdbusviewer-qt5.png
Terminal=false
Encoding=UTF-8
Type=Application
Categories=Qt;Development;Debugger;
EOF



# End Creation of .desktop files

# Add the -qt5 executables

for file in moc uic rcc qmake lconvert lrelease lupdate; do
  ln -sfrvn /usr/bin/$file /pkgs/$PACKAGE/usr/bin/$file-qt5
done
   
cd /pkgs 
   
sudo echo xorg-libs alsa-lib make-ca cups glib gst-plugins-base harfbuzz icu jasper libjpeg-turbo libmng libpng libtiff libwebp libxkbcommon mesa mtdev pcre2 sqlite wayland xcb-util-image xcb-util-keysyms xcb-util-wm ibus bluez libinput pciutils pulseaudio sdl2 > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished

# Method 2 Install
cp -rpv $PACKAGE/* /

cd /blfs/builds
sudo rm -r $DIR




