#!/bin/bash
PKG_VER=5.15.12
URL=https://anduin.linuxfromscratch.org/BLFS/qtwebengine/qtwebengine-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=qtwebengine
export QT5DIR=/usr
# Get Package
set -e
cd /blfs/builds
wget  https://www.linuxfromscratch.org/patches/blfs/svn/qtwebengine-$PKG_VER-build_fixes-1.patch
wget https://www.linuxfromscratch.org/patches/blfs/svn/qtwebengine-$PKG_VER-ffmpeg5_fixes-1.patch
												
wget $URL
tar -xvf $TAR
cd $DIR

# Build

ln -svf /usr/bin/python{2,}
patch -Np1 -i ../qtwebengine-$PKG_VER-build_fixes-1.patch
patch -Np1 -i ../qtwebengine-$PKG_VER-ffmpeg5_fixes-1.patch
mkdir -pv .git src/3rdparty/chromium/.git

sed -e '/^MODULE_VERSION/s/5.*/5.15.7/' -i .qmake.conf

find -type f -name "*.pr[io]" |
  xargs sed -i -e 's|INCLUDEPATH += |&$$QTWEBENGINE_ROOT/include |'
  

sed -e '/link_pulseaudio/s/false/true/' \
    -i src/3rdparty/chromium/media/media_options.gni

sed -e 's/\^(?i)/(?i)^/' \
    -i src/3rdparty/chromium/tools/metrics/ukm/ukm_model.py &&
sed -e "s/'rU'/'r'/" \
    -i src/3rdparty/chromium/tools/grit/grit/util.py
    
sed -i 's/NINJAJOBS/NINJA_JOBS/' src/core/gn_run.pro

mkdir build &&
cd    build &&
qmake .. -- -system-ffmpeg -webengine-icu &&
make -j16




# Install
make install 
make INSTALL_ROOT=/pkgs/$PACKAGE install
find $QT5DIR/ -name \*.prl \
   -exec sed -i -e '/^QMAKE_PRL_BUILD_DIR/d' {} \;
export QT5DIR=/pkgs/qtwebengine/usr
find $QT5DIR/ -name \*.prl \
   -exec sed -i -e '/^QMAKE_PRL_BUILD_DIR/d' {} \;
rm -v /usr/bin/python
cd /pkgs


sudo echo "nodejs nss pciutils qt5 alsa-lib pulseaudio ffmpeg icu libxml2 libwebp libxslt opus libevent mitkrb" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


