#!/bin/bash
set -e
bash gnome/tracker-miners
bash gnome/evolution-data-server
bash boost
bash gnome/tracker
#bash firefox
bash js102
bash harfbuzz
bash qt5
bash qtwebengine
bash freerdp
bash libical
bash nodejs
bash samba
bash kde/kf5
bash kde/phonon
bash avahi
bash grantlee
bash kde/kde
bash kde/libdbusmenu-qt
bash gnmome/gjs
bash gnome/folks
bash lightdm
bash falkon
bash libportal
bash upower
bash gnome/vte
bash gnome/libgweather
bash gnome/yelp
