#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


PKG_VER=1.83.0
URL=https://static.rust-lang.org/dist/rustc-$PKG_VER-src.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=rustc
set -e
# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
cat << EOF > config.toml
# credit to LFS
# tell x.py to not keep printing an annoying warning
change-id = 131075

# see config.toml.example for more possible options
# See the 8.4 book for an example using shipped LLVM
# e.g. if not installing clang, or using a version before 10.0
[llvm]
# by default, rust will build for a myriad of architectures
targets = "X86"

# When using system llvm prefer shared libraries
link-shared = true

download-ci-llvm = false

[build]
# omit docs to save time and space (default is to build them)
docs = false

# install cargo as well as rust
extended = true


# Do not query new versions of dependencies online.
locked-deps = true

tools = ["cargo", "clippy", "rustdoc", "rustfmt"]

vendor = true


[install]
prefix = "/usr"
docdir = "share/doc/rustc"

[rust]
channel = "stable"
rpath = false
codegen-tests = false

[target.x86_64-unknown-linux-gnu]
# NB the output of llvm-config (i.e. help options) may be
# dumped to the screen when config.toml is parsed.
llvm-config = "/usr/bin/llvm-config"

[target.i686-unknown-linux-gnu]
# NB the output of llvm-config (i.e. help options) may be
# dumped to the screen when config.toml is parsed.
llvm-config = "/usr/bin/llvm-config"


EOF

# Fix build with llvm 19
sed '/CondBitmap/,/^}/s/LLVM_VERSION.*/& \&\& LLVM_VERSION_LT(19, 0)/' \
        -i compiler/rustc_llvm/llvm-wrapper/RustWrapper.cpp &&

rm -v tests/coverage/mcdc/{cond*,if,inline*,nest*,non_*}.rs

export RUSTFLAGS="$RUSTFLAGS -C link-args=-lffi" &&
python3 ./x.py build --exclude src/tools/miri




# Install

export LIBSSH2_SYS_USE_PKG_CONFIG=1 &&
DESTDIR=${PWD}/install python3 ./x.py install &&
unset LIBSSH2_SYS_USE_PKG_CONFIG

chown -R root:root install
mkdir -p /pkgs/rustc/
cp -a install/* /pkgs/rustc

# Host install method 2 
cp -a install/* /



cd /pkgs



sudo echo "curl gcc clang libssh2" > /pkgs/$PACKAGE/depends
sudo echo "llvm curl libssh2 cmake gcc clang" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


