#!/bin/bash
export CFLAGS=-"O2"
export CXXFLAGS="-O2"

URL=https://git.sr.ht/~kennylevinsen/seatd/archive/0.7.0.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=seatd-$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir build
cd build

meson --prefix=/usr \
   --buildtype=plain \
   -Dexamples="disabled" \
   -Dserver="enabled" \
   -Dlibseat-logind="systemd"  ..

ninja 


# Install
sudo DESTDIR=/pkgs/$PACKAGE  ninja install
sudo ninja install
cd /pkgs



sudo echo "" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


