#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

URL=https://sourceware.org/ftp/docbook-tools/new-trials/SOURCES/sgml-common-0.6.3.tgz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tgz||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
wget https://www.linuxfromscratch.org/patches/blfs/svn/sgml-common-0.6.3-manpage-1.patch
tar -xvf $TAR
cd $DIR

# Build
patch -Np1 -i ../sgml-common-0.6.3-manpage-1.patch
autoreconf -i
./configure --prefix=/usr --sysconfdir=/etc

make -j20


# Install
sudo make docdir=/usr/share/doc DESTDIR=/pkgs/$PACKAGE install
install-catalog --add /pkgs/$PACKAGE/etc/sgml/sgml-ent.cat \
    /pkgs/$PACKAGE/usr/share/sgml/sgml-iso-entities-8879.1986/catalog &&

install-catalog --add /pkgs/$PACKAGE/etc/sgml/sgml-docbook.cat \
    /pkgs/$PACKAGE/etc/sgml/sgml-ent.cat
cd /pkgs



sudo echo "glibc" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


