#!/bin/bash
#NLFS
export CFLAGS=-"O2"
export CXXFLAGS="-O2"

URL=https://github.com/gabime/spdlog/archive/refs/tags/v1.11.0.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=spdlog-1.11.0
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr -DINSTALL_LIBDIR=/usr/lib -DBUILD_SHARED_LIBS=on ..


make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "fmt" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


