#!/bin/bash
#NLFS

export CFLAGS=-"O2"
export CXXFLAGS="-O2"
PKG_VER="2024.1"
URL=https://github.com/KhronosGroup/SPIRV-Tools/archive/refs/tags/v$PKG_VER/SPIRV-Tools-$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=SPIRV-Tools-$PKG_VER
PACKAGE=spirv-tools


# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib  -DSPIRV-Headers_SOURCE_DIR=/usr -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=None -DSPIRV_WERROR=off ..


make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "libgcc spirv-headers" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


