#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

URL=https://github.com/KhronosGroup/SPIRV-LLVM-Translator/archive/v18.1.1/SPIRV-LLVM-Translator-18.1.1.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=spirv-llvm-translator

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir build
cd build

cmake -D CMAKE_INSTALL_PREFIX=/usr               \
      -D CMAKE_BUILD_TYPE=Release                \
      -D BUILD_SHARED_LIBS=ON                    \
      -D CMAKE_SKIP_INSTALL_RPATH=ON             \
      -D LLVM_EXTERNAL_SPIRV_HEADERS_SOURCE=/usr \
      -G Ninja ..

ninja


# Install
sudo  DESTDIR=/pkgs/$PACKAGE ninja install
sudo ninja install
cd /pkgs



sudo echo "libxml2 llvm spirv-tools" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


