#!/bin/bash
export CFLAGS=-"O2"
export CXXFLAGS="-O2"

URL=https://github.com/plougher/squashfs-tools/archive/refs/tags/4.5.1.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=squashfs-tools-4.5.1
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

cd squashfs-tools

make -j16


# Install
sudo make INSTALL_PREFIX=/pkgs/$PACKAGE/usr install
sudo make install
cd /pkgs



sudo echo "" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


