#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

PKG_VER=8.6.14
URL=https://cytranet.dl.sourceforge.net/project/tcl/Tcl/$PKG_VER/tk$PKG_VER-src.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=tk$PKG_VER
PACKAGE=tk

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
cd unix

./configure \
		--prefix=/usr \
		--mandir=/usr/share/man \
		--enable-threads \
		--disable-rpath \
		--enable-64bit

make -j22


# Install
sudo make INSTALL_ROOT=/pkgs/$PACKAGE install
ln -s libtk${PKG_VER%.*}.so /pkgs/$PACKAGE/usr/lib
cd /pkgs
# Remove references to build directory (Credit Arch Linux & LFS)
sed -e "s#/blfs/builds/$DIR/tk$PKG_VER/unix#/usr/lib#" \
	-e "s#/blfs/builds/$DIR/tk$PKG_VER#/usr/include#" \
	-i /pkgs/$PACKAGE/usr/lib/tkConfig.sh



sudo echo "tcl" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


