#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

PKG_VER=1.22.0
URL=https://nlnetlabs.nl/downloads/unbound/unbound-$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')
BLFS_SYSTEMD_VER=20241211

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

./configure --prefix=/usr     \
            --sysconfdir=/etc \
            --disable-static  \
            --with-pidfile=/run/unbound.pid &&


make -j22


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
# Install systemd unit
cd /blfs/builds
wget https://www.linuxfromscratch.org/blfs/downloads/systemd/blfs-systemd-units-$BLFS_SYSTEMD_VER.tar.xz
tar -xvf blfs-systemd-units-$BLFS_SYSTEMD_VER.tar.xz
cd blfs-systemd-units-$BLFS_SYSTEMD_VER
make DESTDIR=/pkgs/$PACKAGE install-unbound
# Done
cd /pkgs



sudo echo "libevent nettle" > /pkgs/$PACKAGE/depends
sudo echo 'groupadd -g 88 unbound &&
useradd -c "Unbound DNS Resolver" -d /var/lib/unbound -u 88 \
        -g unbound -s /bin/false unbound
	unbound-anchor' > /pkgs/$PACKAGE/postinst
cp -rpv /pkgs/$PACKAGE/* /
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished

cd /blfs/builds
sudo rm -r $DIR


