#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


PKG_VER=2.12
URL=https://dotat.at/prog/unifdef/unifdef-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build


make -j16


# Install
mkdir -p /pkgs/$PACKAGE/usr/bin
mkdir -p /pkgs/$PACKAGE/usr/share/man/man1
install -m 0755 unifdef /pkgs/$PACKAGE/usr/bin/
install -m 0755 unifdefall.sh /pkgs/$PACKAGE/usr/bin/unifdefall
install -m 0644 unifdefall.sh /pkgs/$PACKAGE/usr/share/man/man1/

cd /pkgs



sudo echo "" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


