#!/bin/bash
export CFLAGS=-"O2"
export CXXFLAGS="-O2"

URL=https://downloads.sourceforge.net/infozip/unzip60.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=unzip

# Get Package

cd /blfs/builds
wget $URL
wget https://www.linuxfromscratch.org/patches/blfs/svn/unzip-6.0-consolidated_fixes-1.patch
tar -xvf $TAR
cd $DIR

# Build


patch -Np1 -i ../unzip-6.0-consolidated_fixes-1.patch

make -f unix/Makefile generic -j20


# Install
make prefix=/pkgs/$PACKAGE/usr MANDIR=/pkgs/$PACKAGE/usr/share/man/man1 \
 -f unix/Makefile  install
cd /pkgs



sudo echo "" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


