#!/bin/bash
URL=https://gitlab.freedesktop.org/upower/upower/-/archive/v0.99.19/upower-v0.99.19.tar.bz2
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/day18/gnome
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir build &&
cd    build &&

meson --prefix=/usr       \
      --buildtype=release \
      -Dgtk-doc=false     \
      -Dman=false         \
      ..                   && 


ninja -j16


# Install
sudo porg -lp $PACKAGE "LC_ALL=C ninja install"
cd /gnome
sudo ./dir.sh $PACKAGE


sudo echo "libgudev libusb polkit gobject-introspection" > /pkgs/gnome42/$PACKAGE/depends
sudo echo "systemctl enable upower" > /pkgs/gnome42/$PACKAGE/postinst
sudo rm -r /pkgs/gnome42/$PACKAGE/blfs
sudo tar -cvpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished/gnome42


cd /blfs/day18/gnome
sudo rm -r $DIR


