#!/bin/bash
#NLFS
export CFLAGS=-"O2"
export CXXFLAGS="-O2"


PKG_VER=11.0
URL=https://releases.pagure.org/virt-viewer/virt-viewer-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
wget https://raw.githubusercontent.com/xXTeraXx/Tucana/main/mercury/patches/virt-viewer.patch
tar -xvf $TAR
cd $DIR

# Build
patch -Np1 < ../virt-viewer.patch
mkdir build
cd build

meson --prefix=/usr ..

ninja


# Install
sudo  DESTDIR=/pkgs/$PACKAGE ninja install
sudo ninja install
cd /pkgs



sudo echo "spice-gtk vte" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


