#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"
PKG_VER=3.0.21
URL=https://download.videolan.org/vlc/$PKG_VER/vlc-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')
set -e
# Get Package

cd /blfs/builds
wget $URL
wget https://www.linuxfromscratch.org/patches/blfs/svn/vlc-3.0.21-taglib-1.patch
wget https://www.linuxfromscratch.org/patches/blfs/svn/vlc-3.0.21-fedora_ffmpeg7-1.patch
tar -xvf $TAR
cd $DIR

# Build
patch -Np1 -i vlc-3.0.21-taglib-1.patch
patch -Np1 -i vlc-3.0.21-fedora_ffmpeg7-1.patch

export LUAC=/usr/bin/luac5.2                   &&
export LUA_LIBS="$(pkg-config --libs lua52)"   &&
export CPPFLAGS="$(pkg-config --cflags lua52)" &&

BUILDCC=gcc ./configure --prefix=/usr --disable-libva   \


make -j16


# Install
sudo make  docdir=/usr/share/doc/vlc DESTDIR=/pkgs/$PACKAGE install
sudo make docdir=/usr/share/doc/vlc  install
cd /pkgs



sudo echo "qt5 alsa-lib dbus libssh2 v4l-utils libpng libtheora libva libvorbis opus x264 ffmpeg pulseaudio" > /pkgs/$PACKAGE/depends
sudo echo "lua5.2 lua a52dec" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


