#!/bin/bash
export CFLAGS=-"O2"
export CXXFLAGS="-O2"

URL=https://download.videolan.org/vlc/3.0.18/vlc-3.0.18.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')
set -e
# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build


export LUAC=/usr/bin/luac5.2                   &&
export LUA_LIBS="$(pkg-config --libs lua52)"   &&
export CPPFLAGS="$(pkg-config --cflags lua52)" &&

BUILDCC=gcc ./configure --prefix=/usr    \


make -j16


# Install
sudo make  docdir=/usr/share/doc/vlc-3.0.17.4 DESTDIR=/pkgs/$PACKAGE install
sudo make docdir=/usr/share/doc/vlc-3.0.17.4  install
cd /pkgs



sudo echo "qt5 alsa-lib dbus libssh2 v4l-utils libpng libtheora libva libvorbis opus x264 ffmpeg pulseaudio" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


