#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

URL=https://github.com/KhronosGroup/Vulkan-Headers.git
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=Vulkan-Headers
PACKAGE=vulkan-headers
set -e 
# Get Package

cd /blfs/builds
git clone $URL
cd $DIR

# Build

mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr ..


make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm  -r $DIR
