#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

PKG_VER=1.3.285
URL=https://github.com/KhronosGroup/Vulkan-Headers/archive/refs/tags/v$PKG_VER/Vulkan-Headers-$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=Vulkan-Headers-$PKG_VER
PACKAGE=vulkan-headers
set -e 
# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr ..


make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "" > /pkgs/$PACKAGE/depends
sudo echo "cmake" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm  -r $DIR
