#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

set -e
PKG_VER=2.42.1
URL=https://webkitgtk.org/releases/webkitgtk-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
export CFLAGS+=' -g1'
export CXXFLAGS+=' -g1'

mkdir build1 &&
cd    build1 &&

cmake -DCMAKE_BUILD_TYPE=Release  \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DCMAKE_SKIP_RPATH=ON       \
      -DPORT=GTK                  \
      -DUSE_JPEGXL=OFF            \
      -DLIB_INSTALL_DIR=/usr/lib  \
      -DUSE_LIBHYPHEN=OFF         \
      -DENABLE_GAMEPAD=OFF        \
      -DENABLE_MINIBROWSER=ON     \
      -DUSE_AVIF=OFF \
      -DUSE_SOUP2=ON              \
      -DUSE_WPE_RENDERER=ON       \
      -Wno-dev -G Ninja ..        &&

ninja


# Install
ninja install
DESTDIR=/pkgs/$PACKAGE ninja install
cd /pkgs


#Strip binaries
pushd .
cd /pkgs/$PACKAGE/usr/lib
strip $(file * | grep ELF | sed 's/:.*//')
popd

sudo echo "cairo woff2 gst-plugins-base gst-plugins-bad gtk3 icu lcms libgudev libsecret libsoup libwebp mesa openjpeg ruby sqlite which wpebackend-foo enchant geoclue gobject-introspection hicolor-icons libnotify wayland xdg-dbus-proxy" > /pkgs/$PACKAGE/depends
sudo echo "unifdef gi-docgen" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


