#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"
PKG_VER=0.5.5
URL=https://gitlab.freedesktop.org/pipewire/wireplumber/-/archive/$PKG_VER/wireplumber-$PKG_VER.tar.bz2
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir build
cd build

meson setup --prefix=/usr --buildtype=release -Dsystem-lua=true .. 

ninja


# Install
sudo  DESTDIR=/pkgs/$PACKAGE ninja install
sudo ninja install
cd /pkgs



sudo echo "pipewire glib systemd lua" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


