#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


PKG_VER=0.8.3
URL=https://github.com/Cyan4973/xxHash/archive/refs/tags/v$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=xxHash-$PKG_VER
PACKAGE=xxhash

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build




make


# Install
sudo make DESTDIR=/pkgs/$PACKAGE prefix=/usr install
sudo make prefix=/usr install
cd /pkgs



sudo echo "glibc" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


