#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

PKG_VER=0.8.0
URL=https://github.com/jbeder/yaml-cpp/archive/refs/tags/$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=yaml-cpp-$PKG_VER
PACKAGE=yamlcpp

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr -Wno-dev -DBUILD_SHARED_LIBS=ON  -DYAML_BUILD_SHARED_LIBS=ON  -DCMAKE_BUILD_TYPE=Release ..


make -j22


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


