#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "

PKG_VER=4.44.6
URL=https://github.com/mikefarah/yq/archive/refs/tags/v$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=yq-$PKG_VER
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

go mod vendor
go build .


# Install
install -Dt /pkgs/$PACKAGE/usr/bin yq
install -Dt /pkgs/$PACKAGE/usr/share/licenses/$PACKAGE LICENSE
cd /pkgs



sudo echo "" > /pkgs/$PACKAGE/depends
sudo echo "go" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished
cp -rpv /pkgs/$PACKAGE/* /

cd /blfs/builds
sudo rm -r $DIR


