#!/bin/bash
URL=https://downloads.sourceforge.net/infozip/zip30.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=zip

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

make -f unix/Makefile generic_gcc -j20


# Install
make prefix=/pkgs/$PACKAGE/usr MANDIR=/usr/share/man/man1 -f unix/Makefile install
make prefix=/usr MANDIR=/usr/share/man/man1 -f unix/Makefile install
cd /pkgs



sudo echo "" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


