#!/bin/bash
export CFLAGS=-"O2"
export CXXFLAGS="-O2"

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

URL=https://poppler.freedesktop.org/poppler-23.0.4.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
wget https://poppler.freedesktop.org/poppler-data-0.4.11.tar.gz
tar -xvf $TAR
cd $DIR

# Build



mkdir build
cd build
cmake  -DCMAKE_BUILD_TYPE=Release   \
       -DCMAKE_INSTALL_PREFIX=/usr  \
       -DTESTDATADIR=$PWD/testfiles \
       -DENABLE_UNSTABLE_API_ABI_HEADERS=ON \
       ..   




make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install



tar -xf ../../poppler-data-0.4.11.tar.gz &&
cd poppler-data-0.4.11
make prefix=/usr install
make prefix=/usr DESTDIR=/pkgs/$PACKAGE install

cd /pkgs



sudo echo "fontconfig boost cairo lcms libjpeg-turbo libpng nss openjpeg gdk-pixbuf libtiff curl" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


