#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

PKG_VER=2.3.9
URL=https://download.kde.org/stable/qca/$PKG_VER/qca-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

sed -i 's@cert.pem@certs/ca-bundle.crt@' CMakeLists.txt

mkdir build
cd build


cmake -D CMAKE_INSTALL_PREFIX=/usr \
      -D CMAKE_BUILD_TYPE=Release                \
      -D QCA_MAN_INSTALL_DIR:PATH=/usr/share/man \
      -D QCA_INSTALL_IN_QT_PREFIX=ON \
      -D QT6=ON \
      -D BUILD_TESTS=OFF \
      -G Ninja \
      ..



ninja
# Install
sudo DESTDIR=/pkgs/$PACKAGE ninja install
sudo ninja install
cd /pkgs



sudo echo "ca-certificates qt6 which" > /pkgs/$PACKAGE/depends
sudo echo "cmake" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


