#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

URL=https://www.x.org/pub/individual/lib/libXxf86dga-1.1.6.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

./configure --disable-static --prefix=/usr --sysconfdir=/etc --localstatedir=/var \
  --with-appdefaultdir=/etc/X11/app-defaults --docdir=/usr/share/doc/$PACKAGE


make -j20


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "libX11" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


