#!/bin/bash
bash -e plasma-activities
bash -e  kglobalacceld
bash -e  libksysguard
bash -e  kwayland
bash -e  plasma-activities
bash -e  plasma-activities-stats
bash -e  libplasma
bash -e  kdecoration
bash -e  libkscreen
bash -e  breeze
bash -e  breeze-gtk
bash -e  layer-shell-qt
bash -e  kscreenlocker
bash -e  oxygen
bash -e  kinfocenter
bash -e  kwin
bash -e  plasma5support
bash -e  plasma-workspace
bash -e  plasma-disks
bash -e  bluedevil
bash -e  kde-gtk-config
bash -e  kmenuedit
bash -e  kscreen
bash -e  kwallet-pam
bash -e  kwayland-integration
bash -e  kwrited
bash -e  milou
bash -e  plasma-nm
bash -e  plasma-pa
bash -e  plasma-workspace-wallpapers
bash -e  polkit-kde-agent-1
bash -e  powerdevil
bash -e  plasma-desktop
bash -e  kdeplasma-addons
bash -e  kgamma
bash -e  ksshaskpass
bash -e  plasma-sdk
bash -e  sddm-kcm
bash -e  discover
bash -e  kactivitymanagerd
bash -e  plasma-integration
bash -e  xdg-desktop-portal-kde
bash -e  drkonqi
bash -e  plasma-vault
bash -e  plasma-browser-integration
bash -e  kde-cli-tools
bash -e  systemsettings
bash -e  plasma-thunderbolt
bash -e  plasma-firewall
bash -e  plasma-systemmonitor
bash -e  qqc2-breeze-style
bash -e  ksystemstats
bash -e  oxygen-sounds
