#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

PACKAGE=kwin
PKG_VER=6.1.3
URL=https://download.kde.org/stable/plasma/$PKG_VER/$PACKAGE-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')


# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build



mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr \
      -DCMAKE_BUILD_TYPE=Release         \
      -DBUILD_TESTING=OFF                \
      -Wno-dev ..





make -j22


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "breeze plasma-activities kauth kcmutils kcolorscheme kconfig kconfigwidgets kcoreaddons kcrash kdbusaddons kdeclarative kdecoration kglobalaccel kglobalacceld kguiaddons ki18n kidletime kirigami kitemmodels knewstuff knotifications kpackage kquickcharts kscreenlocker kservice ksvg kwayland kwidgetsaddons kwindowsystem kxmlgui lcms libdisplay-info libdrm libei libepoxy libinput libpipewire libX11 libxcb libxcvt libXi libxkbcommon mesa pipewire libplasma qt6 wayland xcb-util-cursor xcb-util-keysyms xcb-util-wm" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


