#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

PACKAGE=plasma-desktop
PKG_VER=6.2.3
URL=https://download.kde.org/stable/plasma/$PKG_VER/$PACKAGE-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')


# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build



mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr \
      -DCMAKE_BUILD_TYPE=Release         \
      -DBUILD_TESTING=OFF                \
      -Wno-dev ..





make -j22


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "attica baloo icu kauth kbookmarks kcmutils kcodecs kcompletion kconfig kconfigwidgets kcoreaddons kcrash kdbusaddons kdeclarative kglobalaccel kguiaddons ki18n kiconthemes kio kirigami kirigami-addons kitemmodels kitemviews kjobwidgets kmenuedit knewstuff knotifications knotifyconfig kpackage kpipewire krunner kservice ksvg kwidgetsaddons kwindowsystem kxmlgui libcanberra libksysguard libX11 libxcb libXcursor libXi libxkbcommon libxkbfile libplasma plasma-activities plasma-activities-stats plasma-workspace plasma5support polkit-kde-agent-1 powerdevil qt6 sdl2 solid sonnet systemsettings wayland xcb-util-keysyms xdg-user-dirs bluedevil glib ibus kscreen libaccounts-qt packagekit-qt plasma-nm plasma-pa" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


