#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

PACKAGE=plasma-workspace
PKG_VER=6.2.0
URL=https://download.kde.org/stable/plasma/$PKG_VER/$PACKAGE-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')


# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build



mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr \
      -DCMAKE_BUILD_TYPE=Release         \
      -DBUILD_TESTING=OFF                \
      -Wno-dev ..





make -j22


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "accounts-service appstream fontconfig freetype2 glibc icu plasma-activities plasma-activities-stats kactivitymanagerd karchive kauth kbookmarks kcmutils kcolorscheme kcompletion kconfig kconfigwidgets kcoreaddons kcrash kde-cli-tools kdeclarative kded kdbusaddons kglobalaccel kguiaddons kholidays ki18n kiconthemes kidletime kio kio-extras kio-fuse kirigami kirigami-addons kitemmodels kjobwidgets knewstuff knotifications knotifyconfig kpackage kparts kpipewire krunner kquickcharts kscreenlocker kservice kstatusnotifieritem ksvg ksystemstats ktexteditor ktextwidgets kuserfeedback kwallet kwayland kwidgetsaddons kwin kwindowsystem kxmlgui layer-shell-qt libcanberra libICE libkexiv2 libksysguard libplasma libqalculate libSM libX11 libxau libxcb libXcursor libXfixes libXft libXtst milou phonon plasma5support prison qcoro qt6 solid wayland xcb-util xcb-util-image xwayland zlib baloo plasma-workspace-wallpapers plasma-integration xdg-desktop-portal-gtk" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


