#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

set -e
# Last Validated Version 102.4

PKG_VER=102.15.1esr
REFORMAT=$(echo $PKG_VER | sed 's/esr//g')
URL=https://archive.mozilla.org/pub/firefox/releases/${PKG_VER}/source/firefox-${PKG_VER}.source.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=firefox-$REFORMAT
PACKAGE=js102

# Get Package

cd /blfs/builds
wget $URL
wget https://src.fedoraproject.org/rpms/mozjs102/raw/rawhide/f/Replace-distutils.LooseVersion-with-looseversion.LooseVersion.patch
tar -xvf $TAR
cd $DIR

# Build


(for i in $(find -name six.py); do
   ln -sfv /usr/lib/python3.12/site-packages/six.py $i
   [ $? = 0 ] || exit $?
 done)

patch -Np1 < ../Replace-distutils.LooseVersion-with-looseversion.LooseVersion.patch
# Thanks to fedora for the python 3.12 patches
	
mkdir third_party/python/looseversion
	
ln -s /usr/lib/python3.12/site-packages/looseversion/__init__.py third_party/python/looseversion/looseversion.py
	
echo "vendored:third_party/python/looseversion" >>  python/sites/mach.txt

mkdir obj &&
cd    obj &&

sh ../js/src/configure.in --prefix=/usr            \
                          --with-intl-api          \
                          --with-system-zlib       \
                          --with-system-icu        \
                          --disable-jemalloc       \
                          --disable-debug-symbols  \
                          --enable-readline    
make -j20


# Install

make DESTDIR=/pkgs/$PACKAGE install
rm /pkgs/$PACKAGE/usr/lib/*.ajs
sudo echo "libgcc readline bash zlib icu" > /pkgs/$PACKAGE/depends
sudo echo "libgcc readline bash zlib autoconf213 clang llvm python3 rust zip git" > /pkgs/$PACKAGE/depends
cd /pkgs/$PACKAGE
sudo rm -rf root blfs
cd ..
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished
sudo cp -rpv /pkgs/$PACKAGE/* /


cd /blfs/builds
sudo rm -r $DIR


