#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

cd /blfs/day22
wget https://archive.mozilla.org/pub/firefox/releases/91.11.0esr/source/firefox-91.11.0esr.source.tar.xz
tar -xvf firefox-91.11.0esr.source.tar.xz
cd firefox-91.11.0

#Build
mkdir obj &&
cd    obj &&

CC=gcc CXX=g++ \
sh ../js/src/configure.in --prefix=/usr            \
                          --with-intl-api          \
                          --with-system-zlib       \
                          --with-system-icu        \
                          --disable-jemalloc       \
                          --disable-debug-symbols  \
                          --enable-readline        &&
make -j16

#install
sudo porg -lp js91 "make install &&
rm -v /usr/lib/libjs_static.ajs &&
sed -i '/@NSPR_CFLAGS@/d' /usr/bin/js91-config"

cd /pkgs
sudo ./dir.sh js91

sudo echo "icu rustc which" > /pkgs/js91/depends
sudo tar -cvf js91.tar.xz js91

cd /blfs/day22
sudo rm -r firefox-91.10.0esr


