#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

set -e
# To update change the commit in pkg-tar
#URL=https://github.com/xXTeraXx/Tucana/releases/download/v2.0/mercury-pkg-2.0.tar.xz
TAR=mercury.tar.xz
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=mercury

# Get Package
bash pkg-tar/mercury
cd /blfs/builds
tar -xvf $TAR
cd $DIR

# Build


# Change install path in Git version, repo is handled by the install script

# Allow postinstalls to be run
echo "postinst"
sed -i 's|#postinst|postinst|g' *

#Change install location
sed -i 's|INSTALL_PATH=.*|INSTALL_PATH=/|' *

# Install
mkdir -p /pkgs/$PACKAGE/usr/bin
cp -pv * /pkgs/$PACKAGE/usr/bin

cd /pkgs



sudo echo "wget bash coreutils" > /pkgs/$PACKAGE/depends
sudo echo "wget base" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


