#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

PACKAGE=cinnamon-desktop
PKG_VER=5.8.0
URL=https://github.com/linuxmint/$PACKAGE/archive/$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$PACKAGE-$PKG_VER

# Get Package

cd /blfs/builds
wget $URL
wget https://gitlab.archlinux.org/archlinux/packaging/packages/cinnamon-desktop/-/raw/main/config.patch
tar -xvf $TAR
cd $DIR

# Build

mkdir build
cd build

meson setup --prefix=/usr --buildtype=release

ninja


# Install
sudo  DESTDIR=/pkgs/$PACKAGE ninja install
sudo ninja install
cd /pkgs



sudo echo "accounts-service gtk3 pulseaudio libxkbfile" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


