#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

PACKAGE=muffin
PKG_VER=6.2.0
URL=https://github.com/linuxmint/$PACKAGE/archive/$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$PACKAGE-$PKG_VER

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir cbuild
cd cbuild

meson setup --prefix=/usr --buildtype=release

ninja


# Install
sudo  DESTDIR=/pkgs/$PACKAGE ninja install
sudo ninja install
cd /pkgs



sudo echo "xwayland cinnamon-desktop gobject-introspection graphene libcanberra libinput libSM libxkbcommon pipewire startup-notification zenity" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


