#!/bin/bash
set -e
ROOT="$(pwd)"
mkdir -p /gnome-logs
build() {
  echo "Building $1"
  bash -e $ROOT/$1 &> /gnome-logs/$1.log

}
build "gcr"
build "gcr-4"
build "gsettings-desktop-schemas"
build "yelp-xsl"
build "baobab"
build "gjs"
build "gnome-color-manager"
build "gnome-autoar"
build "gnome-desktop"
build "gnome-menus"
build "gnome-video-effects"
build "gnome-online-accounts"
build "libwnck"
build "libcloudproviders"
build "evolution-data-server"
build "grilo"

# Desktop
build "dconf"
build "dconf-editor"
build "gnome-backgrounds"
build "gnome-keyring"
build "gexiv2"
build "gnome-terminal"
build "nautilus"
build "gnome-bluetooth"
build "gnome-keyring"
build "gnome-settings-daemon"
build "tecla"
build "gnome-control-center"
build "mutter"
build "gnome-shell"
build "gnome-shell-extensions"
build "gnome-session"
build "gnome-tweaks"
build "gnome-user-docs"
build "yelp"
build "loupe"
build "gdm"
build "gnome-calculator"
build "gnome-screenshot"
build "gnome-logs"
build "epiphany"
build "evolution"
build "evince"
build "gnome-power-manager"
build "gnome-software"
build "gnome-disk-utility"
build "gnome-system-monitor"
build "file-roller"
build "gnome-nettool"
build "snapshot"
build "eog"
build "chrome-gnome-shell"
build "gnome-weather"
build "gnome-console"

