#!/bin/bash
set -e
ROOT="$(pwd)"
build() {
  echo "Building $1"
  bash -e $ROOT/$1

}
build "gcr"
build "gcr-4"
build "gsettings-desktop-schemas"
build "libsecret"
build "rest"
build "totem-pl-parser"
build "vte"
build "vte4"
build "yelp-xsl"
build "gconf"
build "geocode-glib"
build "gjs"
build "gnome-autoar"
build "gnome-desktop"
build "gnome-menus"
build "gnome-video-effects"
build "gnome-online-accounts"
build "grillo"
build "libchamplain"
build "libgdata"
build "libgee"
build "libgtop"
build "libgweather"
build "libpeas"
build "libshumate"
build "libwnck"
build "evolution-data-server"
build "tracker"
build "tracker-miners"
build "gsound"

# Desktop
build "dconf"
build "dconf-editor"
build "gnome-backgrounds"
build "gexiv2"
build "nautilus"
build "gnome-bluetooth"
build "gnome-keyring"
build "gnome-settings-daemon"
build "tecla"
build "gnome-control-center"
build "mutter"
build "gnome-shell"
build "gnome-shell-extensions"
build "gnome-session"
build "gnome-tweaks"
build "gnome-user-docs"
build "yelp"
build "loupe"
build "gdm"
build "gnome-software"
