#!/bin/bash
GNOME_MAJOR=43
GNOME_MINOR=0
# Is in alpha?
#URL=https://download.gnome.org/sources/cheese/$GNOME_MAJOR/cheese-$GNOME_MAJOR.$GNOME_MINOR.tar.xz
URL=https://download.gnome.org/sources/cheese/$GNOME_MAJOR/cheese-$GNOME_MAJOR.alpha.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir build &&
cd    build &&


meson --prefix=/usr --buildtype=release -Dgtk_doc=true ..


ninja 


# Install
ninja install
DESTDIR=/pkgs/$PACKAGE ninja install
cd /pkgs


sudo echo "clutter-gst clutter-gtk gnome-desktop gst-plugins-bad gst-plugins-good v4l-utils libcanberra libgudev gnome-video-effects gobject-introspection vala cogl appstream-glib" > /pkgs/$PACKAGE/depends
sudo echo "glib-compile-schemas /usr/share/glib-2.0/schemas" > /pkgs/$PACKAGE/postinst
sudo rm -rf /pkgs/$PACKAGE/blfs
sudo tar -cvpzf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


