#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

GNOME_MAJOR=44
GNOME_MINOR=2
URL=https://download.gnome.org/sources/eog/$GNOME_MAJOR/eog-$GNOME_MAJOR.$GNOME_MINOR.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir build &&
cd    build &&

meson --prefix=/usr --buildtype=release ..

ninja -j16


# Install
ninja install && DESTDIR=/pkgs/$PACKAGE ninja install
cd /pkgs


sudo echo "adwaita-icon-theme exempi gnome-desktop itstool libjpeg-turbo libpeas shared-mime-info gobject-introspection lcms libexif librsvg gtk-doc libportal libheif" > /pkgs/$PACKAGE/depends
sudo rm -r /pkgs/$PACKAGE/blfs
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


