#!/bin/bash
set -e
GNOME_MAJOR=44
GNOME_MINOR=1
URL=https://download.gnome.org/sources/evince/$GNOME_MAJOR/evince-$GNOME_MAJOR.$GNOME_MINOR.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir build &&
cd    build &&



export CPPFLAGS="-I/opt/texlive/2022/include" &&
export LDFLAGS="$LDFLAGS -L/opt/texlive/2022/lib"
meson --prefix=/usr          \
      --buildtype=release    \
      -Dgtk_doc=false          \
      --wrap-mode=nodownload \
      ..


ninja 


# Install
ninja install
DESTDIR=/pkgs/$PACKAGE ninja install
cd /pkgs


sudo echo "adwaita gsettings-desktop-schemas gtk3 itstool libhandy libxml2 openjpeg gnome-keyring gobject-introspection libarchive libsecret poppler" > /pkgs/$PACKAGE/depends
sudo echo "glib-compile-schemas /usr/share/glib-2.0/schemas" > /pkgs/$PACKAGE/postinst
sudo rm -rf /pkgs/$PACKAGE/blfs
sudo tar -cvpzf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


