#!/bin/bash
set -e
export CFLAGS=-"O2"
export CXXFLAGS="-O2"
PKG_VER=3.54.0
MINOR=$(echo $PKG_VER | sed 's|.[^.]*$||g')
URL=https://download.gnome.org/sources/evolution-data-server/$MINOR/evolution-data-server-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
# icu76 fix
sed '/pkg_check_modules/s/icu-i18n/& icu-uc/' -i CMakeLists.txt

mkdir build
cd build


cmake -DCMAKE_INSTALL_PREFIX=/usr   \
      -DSYSCONF_INSTALL_DIR=/etc    \
      -DENABLE_VALA_BINDINGS=ON     \
      -DENABLE_INSTALLED_TESTS=ON   \
      -DENABLE_GOOGLE=ON            \
      -DENABLE_OAUTH2_WEBKITGTK4=ON \
      -DWITH_OPENLDAP=OFF           \
      -DWITH_KRB5=ON               \
      -DENABLE_INTROSPECTION=ON     \
      -DENABLE_GTK_DOC=OFF          \
      -DWITH_LIBDB=OFF              \
      ..


make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "mitkrb berkeley-db gcr-4 libical libsecret nss sqlite gnome-online-accounts gobject-introspection gtk3 icu libcanberra libgdata libgweather vala geocode-glib-2 webkitgtk4.1 webkitgtk5.0" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


