#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

GNOME_MAJOR=44
GNOME_MINOR=3
URL=https://download.gnome.org/sources/file-roller/$GNOME_MAJOR/file-roller-$GNOME_MAJOR.$GNOME_MINOR.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir build &&
cd    build &&


meson setup --prefix=/usr --buildtype=release -Dpackagekit=false ..


ninja 


# Install
ninja install
DESTDIR=/pkgs/$PACKAGE ninja install
cd /pkgs


sudo echo "libportal gtk3 cpio itstool desktop-file-utils json-glib libarchive libnotify libhandy" > /pkgs/$PACKAGE/depends
sudo echo "glib-compile-schemas /usr/share/glib-2.0/schemas" > /pkgs/$PACKAGE/postinst
sudo echo "
gtk-update-icon-cache -qtf /usr/share/icons/hicolor &&
update-desktop-database -q" >> /pkgs/$PACKAGE/postinst
sudo rm -rf /pkgs/$PACKAGE/blfs
sudo tar -cvpzf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


