#!/bin/bash
export CFLAGS=-"O2"
export CXXFLAGS="-O2"

GNOME_MAJOR=43
GNOME_MINOR=0
URL=https://download.gnome.org/sources/GConf/3.2/GConf-3.2.6.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=gconf

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build


./configure --prefix=/usr \
            --sysconfdir=/etc \
            --disable-orbit \
            --disable-static 

ninja 


# Install
make install
make DESTDIR=/pkgs/$PACKAGE install
cd /pkgs


sudo echo "dbus-glib gobject-introspection gtk3 polkit" > /pkgs/$PACKAGE/depends
sudo echo "glib-compile-schemas /usr/share/glib-2.0/schemas" > /pkgs/$PACKAGE/postinst
sudo rm -r /pkgs/$PACKAGE/blfs
sudo tar -cvpzf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


