#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

PKG_VER=3.41.2
URL=https://download.gnome.org/sources/gcr/3.41/gcr-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

sed -i 's:"/desktop:"/org:' schema/*.xml
mkdir build &&
cd    build &&

meson --prefix=/usr --buildtype=release -Dgtk_doc=false .. 


ninja 


# Install
ninja install
DESTDIR=/pkgs/$PACKAGE ninja install
cd /pkgs


sudo echo "glib libgcrypt p11-kit gnupg gtk3 libsecret libxslt vala" > /pkgs/$PACKAGE/depends
sudo tar -cvpzf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


