#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


PKG_VER=4.3.0
MAJOR=$(echo $PKG_VER | sed 's|.[^.]*$||g')
URL=https://download.gnome.org/sources/gcr/$MAJOR/gcr-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=gcr-4

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir build &&
cd    build &&

meson setup --prefix=/usr --buildtype=release -Dgtk_doc=false .. 


ninja 


# Install
ninja install
DESTDIR=/pkgs/$PACKAGE ninja install
cd /pkgs


sudo echo "glib libgcrypt gnupg gobject-introspection gtk3 libxslt libsecret vala" > /pkgs/$PACKAGE/depends
sudo echo "openssh" > /pkgs/$PACKAGE/make-depends
sudo rm -rf /pkgs/$PACKAGE/blfs
sudo tar -cvpzf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


