#!/bin/bash
URL=https://download.gnome.org/sources/gfbgraph/0.2/gfbgraph-0.2.5.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build


./configure --prefix=/usr --disable-static --enable-gtk-doc

make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE libgfbgraphdocdir=/usr/share/doc/gfbgraph-0.2.5 install
sudo make libgfbgraphdocdir=/usr/share/doc/gfbgraph-0.2.5 install
cd /pkgs



sudo echo "gnome-online-accounts rest gobject-introspection" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


