#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"



PKG_VER=46.2
MAJOR=$(echo $PKG_VER | sed 's|.[^.]*$||g')
URL=https://download.gnome.org/sources/gnome-keyring/$MAJOR/gnome-keyring-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=gnome-keyring

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

sed -i 's:"/desktop:"/org:' schema/*.xml &&

./configure --prefix=/usr     \
            --sysconfdir=/etc \
	    --enable-ssh-agent \

make -j16



# Install
make install
make DESTDIR=/pkgs/$PACKAGE install
cd /pkgs


sudo echo "dbus gcr libxslt gnupg pam" > /pkgs/$PACKAGE/depends
sudo echo "openssh" > /pkgs/$PACKAGE/make-depends
sudo rm -rf /pkgs/$PACKAGE/blfs
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


