#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

GNOME_MAJOR=46
GNOME_MINOR=0.1
URL=https://download.gnome.org/sources/gnome-control-center/$GNOME_MAJOR/gnome-control-center-$GNOME_MAJOR.$GNOME_MINOR.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=gnome-control-center

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir build &&
cd    build &&

meson setup --prefix=/usr --buildtype=release .. &&


ninja -j16


# Install
ninja install && DESTDIR=/pkgs/$PACKAGE ninja install 
cd /pkgs



sudo echo "accounts-service colord-gtk gnome-online-accounts gnome-settings-daemon gsound libgtop libpwquality mitkrb shared-mime-info udisks cups samba gnome-bluetooth ibus libhandy modem-manager libnma xorg gnome-color-manager gnome-shell tecla" > /pkgs/$PACKAGE/depends
sudo rm -rf /pkgs/$PACKAGE/blfs
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


