#!/bin/bash
export CFLAGS=-"O2"
export CXXFLAGS="-O2"

GNOME_MAJOR=43
GNOME_MINOR=0
URL=https://download.gnome.org/sources/gnome-software/43/gnome-software-43.1.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir build &&
cd    build &&
# For some reason this app has to be compiled with Soup 2, otherwise it throws an error about the app being compiled with both soup2 & soup3 (might just be after upgrading)
meson --prefix=/usr --buildtype=release .. -Dsoup2=true


ninja 


# Install
ninja install
DESTDIR=/pkgs/$PACKAGE ninja install
cd /pkgs


sudo echo "packagekit appstream gnome-online-accounts gsettings-desktop-schemas gtk4 libadwaita libsoup3 libsoup flatpak fwupd xmlb"  > /pkgs/$PACKAGE/depends
sudo echo "glib-compile-schemas /usr/share/glib-2.0/schemas" > /pkgs/$PACKAGE/postinst
sudo rm -rf /pkgs/$PACKAGE/blfs
sudo tar -cvpzf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


