#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

GNOME_MAJOR=46
GNOME_MINOR=1
URL=https://download.gnome.org/sources/gnome-user-docs/$GNOME_MAJOR/gnome-user-docs-$GNOME_MAJOR.$GNOME_MINOR.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=gnome-user-docs

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

./configure --prefix=/usr &&
make -j16


# Install
make install
cd /pkgs
sudo  $PACKAGE


sudo echo "itstool libxml2" > /pkgs/$PACKAGE/depends
sudo rm -r /pkgs/$PACKAGE/blfs
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


