#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"
GNOME_MAJOR=47
GNOME_MINOR=0
URL=https://download.gnome.org/sources/gnome-system-monitor/$GNOME_MAJOR/gnome-system-monitor-$GNOME_MAJOR.$GNOME_MINOR.tar.xz
CAT=gnome
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir build
cd build

meson setup --prefix=/usr --buildtype=release ..
ninja


# Install
sudo  DESTDIR=/pkgs/$PACKAGE ninja install
sudo ninja install
cd /pkgs



sudo echo "libadwaita gtkmm4 gtk4 libsigc++ itstool libgtop librsvg desktop-file-utils" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


