#!/bin/bash
PACKAGE=gnome

# Get Package

cd /blfs/builds

# Build





mkdir -p /pkgs/$PACKAGE/var/cache/mercury/meta-pkgs
# Install
cd /pkgs



sudo echo "polkit-gnome gcr gsettings-desktop-schemas libsecret rest totem-pl-parser yelp-xsl gconf geocode-glib gjs gnome-autoar gnome-desktop gnome-menus gnome-video-effects gnome-online-accounts gvfs grilo libchamplain libgdata libgtop libgweather libpeas libwnck network-manager folks evolution-data-server gfbgraph tracker tracker-miners gsound dconf gnome-backgrounds nautilus gexiv2 zenity gnome-bluetooth gnome-keyring gnome-settings-daemon gnome-control-center mutter gnome-shell gnome-shell-extensions gnome-session cheese eog file-roller gnome-calculator gnome-disk-util gnome-logs gnome-maps gnome-nettool gnome-power-manager gnome-screenshot gnome-system-monitor gnome-terminal gnome-weather gtk4 gnome-icon-theme adwaita xdg-user-dirs xorg gdm chrome-gnome-shell gedit gnome-software" > /pkgs/$PACKAGE/depends
sudo echo "gdk-pixbuf-query-loaders --update-cache" > /pkgs/$PACKAGE/postinst
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished




