#!/bin/bash
GNOME_MAJOR=43
GNOME_MINOR=0
URL=https://download.gnome.org/sources/gnome-shell-extensions/$GNOME_MAJOR/gnome-shell-extensions-$GNOME_MAJOR.$GNOME_MINOR.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir build &&
cd    build &&


meson --prefix=/usr .. 

# Install
ninja install && DESTDIR=/pkgs/$PACKAGE ninja install
cd /pkgs



sudo echo "libgtop sassc" > /pkgs/$PACKAGE/depends
sudo rm -rf /pkgs/$PACKAGE/blfs
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


