#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

PKG_VER=3.54.0
URL=https://gitlab.gnome.org/GNOME/gnome-terminal/-/archive/$PKG_VER/gnome-terminal-$PKG_VER.tar.bz2
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
mkdir build &&
cd    build &&


meson setup --prefix=/usr --buildtype=release .. && 


ninja


# Install
ninja install && DESTDIR=/pkgs/$PACKAGE ninja install 
cd /pkgs



sudo echo "libhandy dconf gsettings-desktop-schemas itstool vte pcre2" > /pkgs/$PACKAGE/depends
sudo rm -rf /pkgs/$PACKAGE/blfs
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


