#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

GNOME_MAJOR=44
GNOME_MINOR=2
URL=https://download.gnome.org/sources/gnome-software/$GNOME_MAJOR/gnome-software-$GNOME_MAJOR.$GNOME_MINOR.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=gnome-software

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR
# Build

mkdir build &&
cd    build &&
# For some reason this app has to be compiled with Soup 2, otherwise it throws an error about the app being compiled with both soup2 & soup3 (might just be after upgrading)
meson setup --prefix=/usr --buildtype=release -Dpackagekit=false -Dsoup2=true .. 


ninja 


# Install
ninja install
DESTDIR=/pkgs/$PACKAGE ninja install
cd /pkgs


sudo echo "packagekit appstream gnome-online-accounts gsettings-desktop-schemas gtk4 libadwaita libsoup3 libsoup flatpak fwupd xmlb libunwind"  > /pkgs/$PACKAGE/depends
sudo echo "glib-compile-schemas /usr/share/glib-2.0/schemas" > /pkgs/$PACKAGE/postinst
sudo rm -rf /pkgs/$PACKAGE/blfs
sudo tar -cvpzf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
rm -rf $DIR

