#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

GNOME_MAJOR=44
GNOME_MINOR=0
URL=https://download.gnome.org/sources/gnome-shell/$GNOME_MAJOR/gnome-shell-$GNOME_MAJOR.$GNOME_MINOR.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir build &&
cd    build &&


meson --prefix=/usr --buildtype=release -Dtests=false .. &&

ninja -j16


# Install
ninja install && DESTDIR=/pkgs/$PACKAGE ninja install
cd /pkgs


sudo echo "evolution-data-server gjs gnome-autoar gnome-control-center gtk4 mutter sassc startup-notification systemd desktop-file-utils gnome-bluetooth gst-plugins-base network-manager gcr-4" > /pkgs/$PACKAGE/depends
sudo rm -r /pkgs/$PACKAGE/blfs
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


