#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

GNOME_MAJOR=43
GNOME_MINOR=0
URL=https://download.gnome.org/sources/gtk/4.12/gtk-4.12.3.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=gtk4

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir build &&
cd    build &&


meson --prefix=/usr --buildtype=release -Dbroadway-backend=true -Dintrospection=enabled ..


ninja 


# Install
ninja install
DESTDIR=/pkgs/$PACKAGE ninja install
cd /pkgs


sudo echo "fribidi gdk-pixbuf graphene iso-codes libepoxy libxkbcommon pango pygobject3 wayland-protocols adwaita  gst-plugins-bad gst-plugins-good libvpx hicolor-icons librsvg ffmpeg sassc" > /pkgs/$PACKAGE/depends
sudo echo "glib-compile-schemas /usr/share/glib-2.0/schemas" > /pkgs/$PACKAGE/postinst
sudo rm -rf /pkgs/$PACKAGE/blfs
sudo tar -cvpzf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


