#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

GNOME_MAJOR=47
GNOME_MINOR=0
URL=https://download.gnome.org/sources/mutter/$GNOME_MAJOR/mutter-$GNOME_MAJOR.$GNOME_MINOR.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir build &&
cd    build &&



meson setup --prefix=/usr --buildtype=release -Dtests=disabled .. &&

ninja


# Install
ninja install && DESTDIR=/pkgs/$PACKAGE ninja install
cd /pkgs



sudo echo "gnome-settings-daemon graphene libxcvt libxkbcommon pipewire zenity desktop-file-utils gobject-introspection startup-notification sysprof libinput wayland-protocols xwayland gtk3" > /pkgs/$PACKAGE/depends
sudo rm -rf /pkgs/$PACKAGE/blfs
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


