#!/bin/bash
PKG_VER=44.0
URL=https://download.gnome.org/sources/mutter/43/mutter-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir build &&
cd    build &&



meson --prefix=/usr --buildtype=release -Dtests=false .. &&

ninja -j16


# Install
ninja install && DESTDIR=/pkgs/$PACKAGE ninja install
cd /pkgs



sudo echo "gnome-settings-daemon graphene libxcvt libxkbcommon pipewire zenity desktop-file-utils gobject-introspection startup-notification sysprof libinput wayland-protocols xwayland gtk3" > /pkgs/$PACKAGE/depends
sudo rm -r /pkgs/$PACKAGE/blfs
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


