#!/bin/bash
# meta
PACKAGE=xorg


# Install
mkdir -p /pkgs/$PACKAGE
cd /pkgs



sudo echo "xinit xorg-server libevdev xorg-evdev xorg-libinput libinput mesa xcb-util-cursor xcb-util-image xcb-util-wm xcb-util-renderutil xcb-util dejavu-mono intel-media-driver intel-vaapi" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds


