#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

PACKAGE=kapidox
PKG_VER=6.8
URL=https://download.kde.org/stable/frameworks/$PKG_VER/$PACKAGE-$PKG_VER.0.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
python3 -m build --wheel --skip-dependency-check



# Install
sudo python3 -m installer --destdir=/pkgs/$PACKAGE  dist/*.whl

cd /pkgs

sudo cp -rpv /pkgs/$PACKAGE/* /

sudo echo "python" > /pkgs/$PACKAGE/depends
sudo echo "pyproject-hooks python-build python-installer" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


