#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


PKG_VER=2.18.0
URL=https://files.pythonhosted.org/packages/source/P/Pygments/pygments-$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=pygments

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
python3 -m build --wheel --skip-dependency-check



# Install
sudo python3 -m installer --destdir=/pkgs/$PACKAGE  dist/*.whl

cd /pkgs

cp -rpv $PACKAGE/* /

sudo echo "python" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


