#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"
PKG_VER=3.46.0
MAJOR=$(echo $PKG_VER | sed 's|.[^.]*$||g')
URL= https://download.gnome.org/sources/pygobject/$MAJOR/pygobject-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')3

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build


python3 setup.py build




# Install
sudo python3 setup.py install --root="/pkgs/$PACKAGE" --optimize=1
cd /pkgs

sudo cp -rpv /pkgs/$PACKAGE/* /

sudo echo "python3 gtk3 pycairo" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


