#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

#ARCH_PKG=python-hatchling
#ARCH_VAR=pkgver
PKG_VER=1.21.0
URL=https://files.pythonhosted.org/packages/source/h/hatchling/hatchling-$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=python-$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

python3 -m build -wn --skip-dependency-check





# Install
sudo python3 -m installer --destdir="/pkgs/$PACKAGE" dist/*.whl




cd /pkgs

sudo cp -rpv /pkgs/$PACKAGE/* /

sudo echo "python-pluggy python python-pathspec python-editables" > /pkgs/$PACKAGE/depends
sudo echo "python-trove-classifiers python-build python-installer" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


