#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

URL=https://files.pythonhosted.org/packages/source/P/PyQt5/PyQt5-5.15.10.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=python-pyqt5

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
# Credit: Arch
sip-build \
    --confirm-license \
    --no-make \
    --api-dir /usr/share/qt/qsci/api/python \
    --pep484-pyi
cd build
make -j22



# Install
make INSTALL_ROOT=/pkgs/$PACKAGE install

python -m compileall -d / /pkgs/$PACKAGE/usr/lib
python -O -m compileall -d / /pkgs/$PACKAGE/usr/lib

cd /pkgs

sudo cp -rpv /pkgs/$PACKAGE/* /

sudo echo "python qt5 python-pyqt5-sip" > /pkgs/$PACKAGE/depends
sudo echo "python-build python-installer" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


