#!/bin/bash
URL=https://github.com/python-pillow/Pillow/archive/refs/tags/9.3.0.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=Pillow-9.3.0
PACKAGE=python-pillow

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build


python3 setup.py build




# Install
sudo python3 setup.py install --root="/pkgs/$PACKAGE" --optimize=1
cd /pkgs

sudo cp -rpv /pkgs/$PACKAGE/* /

sudo echo "python3" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


