#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


PKG_VER=2.3.0
URL=https://github.com/urllib3/urllib3/releases/download/$PKG_VER/urllib3-$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=python-$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

python3 -m build -wn --skip-dependency-check





# Install
sudo python3 -m installer --destdir="/pkgs/$PACKAGE" dist/*.whl

cd /pkgs

sudo cp -rpv /pkgs/$PACKAGE/* /

sudo echo "python python-certifi" > /pkgs/$PACKAGE/depends
sudo echo "python-hatch-vcs python-build python-installer python-trove-classifiers" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


