#!/bin/bash
export CFLAGS=-"O2"
export CXXFLAGS="-O2"

URL=https://github.com/pypa/installer/archive/refs/tags/0.5.1.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=installer-$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=python-installer

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

python3 -m build -wn --skip-dependency-check





# Install
sudo python3 -m installer --destdir="/pkgs/$PACKAGE" dist/*.whl 
cd /pkgs

sudo cp -rpv /pkgs/$PACKAGE/* /

sudo echo "python python-build" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


