#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

URL=https://github.com/pypa/build/archive/refs/tags/0.9.0.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=build-$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=python-build

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build


python3 -m build --wheel --skip-dependency-check --no-isolation




# Install
sudo python3 -m installer --destdir="/pkgs/$PACKAGE" dist/*.whl
cd /pkgs

sudo cp -rpv /pkgs/$PACKAGE/* /

sudo echo "python" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


