#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"
set -e
URL=https://files.pythonhosted.org/packages/49/05/6bf21838623186b91aedbda06248ad18f03487dc56fbc20e4db384abde6c/tomli_w-1.0.0.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=tomli-w

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build


python3 -m build -wn --skip-dependency-check

# Install
sudo python3 -m installer --destdir="/pkgs/$PACKAGE" dist/*.whl
cd /pkgs

sudo cp -rpv /pkgs/$PACKAGE/* /

sudo echo "python libyaml" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


