#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

PKG_VER=12.16.0
URL=https://files.pythonhosted.org/packages/source/P/PyQt5-sip/PyQt5_sip-$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=python-pyqt5-sip

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
python3 -m build --wheel --skip-dependency-check



# Install
sudo python3 -m installer --destdir=/pkgs/$PACKAGE  dist/*.whl

cd /pkgs

sudo cp -rpv /pkgs/$PACKAGE/* /

sudo echo "python-sip qt5 python python-packaging setuptools tomli-w" > /pkgs/$PACKAGE/depends
sudo echo "python-build python-installer python-packaging python-setuptools tomli-w" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


