#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

# Using git, there might be other submodules later
URL=https://github.com/rahulc07/Tucana.git
# If it's a frequently updated git repo without a set version, title it with the tucana version in the for t[version] no minor versions, just append to the major eg 1.1=t11
TAR_FINAL=mercury.tar.xz
# master?
COMMIT=4cd6880368f71d40d2f06f3790bf33923484cd83
# Don't touch
DIR=$(echo $URL | sed -r 's|(.*)/||' | sed 's/.git//')
FINAL_DIR=mercury
cd /blfs/builds
mkdir -p $FINAL_DIR
git clone $URL
cd  $DIR
git checkout $COMMIT
# Only using mercury-install mercury-reinstall mercury-update and mercury-sync
mv mercury/{mercury-install,mercury-reinstall,mercury-update,mercury-sync} ../$FINAL_DIR
cd ..
tar -cvpf $TAR_FINAL $FINAL_DIR




