#!/bin/bash
# Using git, there might be other submodules later
URL=
# If it's a frequently updated git repo without a set version, title it with the tucana version in the for t[version] no minor versions, just append to the major eg 1.1=t11
TAR_FINAL=.tar.xz
# master?
COMMIT=
# Don't touch
DIR=$(echo $URL | sed -r 's|(.*)/||' | sed 's/.git//')

cd /blfs/builds

git clone $URL
cd  $DIR
git checkout $COMMIT
cd ..
mv $DIR $(echo $TAR_FINAL | sed 's/.tar.xz//')
tar -cvpf $TAR_FINAL $(echo $TAR_FINAL | sed 's/.tar.xz//')




