#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

# Using git, there might be other submodules later
URL=https://code.videolan.org/videolan/x264.git
# If it's a frequently updated git repo without a set version, title it with the tucana version in the for t[version] no minor versions, just append to the major eg 1.1=t11
TAR_FINAL=x264-t2.tar.xz
# master?
COMMIT=baee400fa9ced6f5481a728138fed6e867b0ff7f
# Don't touch
DIR=$(echo $URL | sed -r 's|(.*)/||' | sed 's/.git//')

cd /blfs/builds

git clone $URL
cd  $DIR
git checkout $COMMIT
rm -r .git
cd ..
mv $DIR $(echo $TAR_FINAL | sed 's/.tar.xz//')
tar -cvpf $TAR_FINAL $(echo $TAR_FINAL | sed 's/.tar.xz//')



