#!/bin/bash
set -e
bash amdgpu
bash base/bc
bash base/diffutils
bash base/gawk
bash base/grep
bash base/iana-etc
bash base/iproute2
bash base/less
bash base/libcap
bash base/man-pages
bash base/openssl
bash base/perl
bash base/util-linux
bash base/xz
bash base/zlib
bash base/zstd
bash build_kernel.sh
bash firefox
bash gnome/gdm
bash gnome/gnome-software
bash gnome/vte4
bash gst-plugins-bad
bash gst-plugins-base
bash gst-plugins-good
bash gst-plugins-ugly
bash gstreamer
bash lib32/lib32-llvm
bash lib32/lib32-mesa
bash lib32/lib32-xorg/lib32-xorgproto
bash lib32/lib32-xorg/libs/lib32-libX11
bash libdaemon
bash libgcrypt
bash libgpg-error
bash librsvg
bash libvulkan
bash llvm
bash mesa
bash nss
bash python-modules/wheel
bash toolchain/gcc-3
bash unrar
bash vkd3d
bash vlc
bash wine
bash xfce4/libxfce4ui
bash xfce4/thunar
bash xfce4/xfce4-panel
bash xfce4/xfce4-session
bash xfce4/xfdesktop
bash xorg/libs/libX11
bash xorg/xorgproto
