bash base/dbus
bash base/python
bash cinnamon/cinnamon-control-center
bash cinnamon/cinnamon-desktop
bash cinnamon/cinnamon-menus
bash cinnamon/cinnamon-screensaver
bash cinnamon/cinnamon-session
bash cinnamon/cinnamon-settings-daemon
bash cinnamon/cinnamon-template
bash cinnamon/cjs
bash cinnamon/muffin
bash gnome/eog
bash gnome/gjs
bash gnome/gnome-weather
bash gnome/libadwaita
bash gnome/libgnomekbd
bash intel-gmmlib
bash kde/kf5
bash libcanberra
bash libisofs
bash php
bash python-modules/markupsafe
bash qt5
bash smartmontools
bash tidy
bash wine
bash xorg/xkeyboard-config
