#!/bin/bash
export CFLAGS=-"O2"
export CXXFLAGS="-O2"

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

URL=https://download.savannah.gnu.org/releases/acl/acl-2.3.1.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build


./configure --prefix=/usr         \
            --disable-static      \
            --docdir=/usr/share/doc/acl-2.3.1

make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "attr glibc" > /pkgs/$PACKAGE/depends
sudo echo "attr bash binutils coreutils gcc gettext grep m4 make perl sed texinfo" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


