#!/bin/bash
PACKAGE=base-update





cd /pkgs
mkdir -p base-update/etc
cd base-update/etc

cat > /pkgs/$PACKAGE/etc/lsb-release << "EOF"
DISTRIB_ID="Tucana Linux"
DISTRIB_RELEASE="3.0"
DISTRIB_DESCRIPTION="Tucana GNU/Linux"
EOF

cat > /pkgs/$PACKAGE/etc/os-release << "EOF"
NAME="Tucana Linux"
VERSION="3.0"
ID=tucana
PRETTY_NAME="Tucana GNU/Linux 3.0"
VENDOR_NAME="Rahul Chandra"


EOF

cd /pkgs
echo "" > /pkgs/$PACKAGE/depends
tar -cvzpf $PACKAGE.tar.xz $PACKAGE
cp $PACKAGE.tar.xz /finished
