#!/bin/bash
PACKAGE=base-update





cd /pkgs
mkdir -p base-update/etc
cd base-update/etc

cat > /pkgs/$PACKAGE/etc/lsb-release << "EOF"
DISTRIB_ID="Tucana Linux"
DISTRIB_RELEASE="3.1"
DISTRIB_DESCRIPTION="Tucana GNU/Linux"
EOF

cat > /pkgs/$PACKAGE/etc/os-release << "EOF"
NAME="Tucana Linux"
VERSION="3.1"
ID=tucana
PRETTY_NAME="Tucana GNU/Linux 3.1"
VENDOR_NAME="Rahul Chandra"


EOF

cd /pkgs
echo "zlib mercury coreutils util-linux findutils gettext glibc grep sed libgcc iproute2 file procps-ng systemd tar xz zstd psmisc gzip bzip2 bash shadow pam ca-certificates p11-kit wget mkinitramfs kmod efibootmgr grub libffi man-pages man-db less ncurses perl perl-xml-parser openssl e2fsprogs sudo libunistring diffutils gawk iana-etc" > /pkgs/$PACKAGE/depends
tar -cvzpf $PACKAGE.tar.xz $PACKAGE
cp $PACKAGE.tar.xz /finished
