#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


# Credits
# The Linux From Scratch project <linuxfromscratch.org>
# Tucana would not be possible without them!
set -e
PACKAGE=base
TUCANA_VERSION='3.0'

# Notes 
# To update
# If updates are pushed make sure to change the Tucana version
# Then change the base-update package
# So that people can update from one version to another



# Get Package

cd /blfs/builds


# Build

# Create essential folders
mkdir -pv /pkgs/$PACKAGE/etc/sysconfig
mkdir -pv /pkgs/$PACKAGE/etc/modprobe.d
mkdir -pv /pkgs/$PACKAGE/usr/lib
mkdir -pv /pkgs/$PACKAGE/usr/bin
mkdir -pv /pkgs/$PACKAGE/usr/sbin
mkdir -pv /pkgs/$PACKAGE/usr/bin
mkdir -pv /pkgs/$PACKAGE/var/lock
mkdir -pv /pkgs/$PACKAGE/var/{cache,local,log,mail,opt,spool}
mkdir -pv /pkgs/$PACKAGE/dev
mkdir -pv /pkgs/$PACKAGE/proc
mkdir -pv /pkgs/$PACKAGE/sys
mkdir -pv /pkgs/$PACKAGE/mnt
mkdir -pv /pkgs/$PACKAGE/media
mkdir -pv /pkgs/$PACKAGE/boot
mkdir -pv /pkgs/$PACKAGE/home
mkdir -pv /pkgs/$PACKAGE/opt
mkdir -pv /pkgs/$PACKAGE/usr/lib/firmware
mkdir -pv /pkgs/$PACKAGE/lib64
install -dv -m 0750 /pkgs/$PACKAGE/root
install -dv -m 1777 /pkgs/$PACKAGE/tmp /pkgs/$PACKAGE/var/tmp

# Create symlinks

ln -sfv /proc/self/mounts /pkgs/$PACKAGE/etc/mtab

ln -sfv /run /pkgs/$PACKAGE/var/run
ln -sfv /run/lock /pkgs/$PACKAGE/var/lock
ln -sfv /usr/lib /pkgs/$PACKAGE/lib

ln -sfv ../lib/ld-linux-x86-64.so.2 /pkgs/$PACKAGE/lib64
ln -sfv ../lib/ld-linux-x86-64.so.2 /pkgs/$PACKAGE/lib64/ld-lsb-x86-64.so.3

ln -sfv /usr/bin /pkgs/$PACKAGE/bin
ln -sfv /usr/sbin /pkgs/$PACKAGE/sbin


# Create /etc/hosts

cat > /pkgs/$PACKAGE/etc/hosts << EOF
127.0.0.1  localhost.localdomain localhost
::1        localhost
EOF

# Create /etc/group

cat > /pkgs/$PACKAGE/etc/group << "EOF"
root:x:0:
bin:x:1:daemon
sys:x:2:
kmem:x:3:
tape:x:4:
tty:x:5:
daemon:x:6:
floppy:x:7:
disk:x:8:
lp:x:9:
dialout:x:10:
audio:x:11:
video:x:12:
utmp:x:13:
usb:x:14:
cdrom:x:15:
adm:x:16:
messagebus:x:18:
systemd-journal:x:23:
input:x:24:
mail:x:34:
kvm:x:61:
systemd-journal-gateway:x:73:
systemd-journal-remote:x:74:
systemd-journal-upload:x:75:
systemd-network:x:76:
systemd-resolve:x:77:
systemd-timesync:x:78:
systemd-coredump:x:79:
uuidd:x:80:
systemd-oom:x:81:
wheel:x:97:
users:x:999:
nogroup:x:65534:
EOF

# Create /etc/passwd

cat > /pkgs/$PACKAGE/etc/passwd << "EOF"
root:x:0:0:root:/root:/bin/bash
bin:x:1:1:bin:/dev/null:/usr/bin/false
daemon:x:6:6:Daemon User:/dev/null:/usr/bin/false
messagebus:x:18:18:D-Bus Message Daemon User:/run/dbus:/usr/bin/false
systemd-journal-gateway:x:73:73:systemd Journal Gateway:/:/usr/bin/false
systemd-journal-remote:x:74:74:systemd Journal Remote:/:/usr/bin/false
systemd-journal-upload:x:75:75:systemd Journal Upload:/:/usr/bin/false
systemd-network:x:76:76:systemd Network Management:/:/usr/bin/false
systemd-resolve:x:77:77:systemd Resolver:/:/usr/bin/false
systemd-timesync:x:78:78:systemd Time Synchronization:/:/usr/bin/false
systemd-coredump:x:79:79:systemd Core Dumper:/:/usr/bin/false
uuidd:x:80:80:UUID Generation Daemon User:/dev/null:/usr/bin/false
systemd-oom:x:81:81:systemd Out Of Memory Daemon:/:/usr/bin/false
nobody:x:65534:65534:Unprivileged User:/dev/null:/usr/bin/false
EOF

cat > /pkgs/$PACKAGE/etc/shadow << "EOF"
bin:x:19119:0:99999:7:::
daemon:x:19119:0:99999:7:::
messagebus:x:19119:0:99999:7:::
systemd-journal-gateway:x:19119:0:99999:7:::
systemd-journal-remote:x:19119:0:99999:7:::
systemd-journal-upload:x:19119:0:99999:7:::
systemd-network:x:19119:0:99999:7:::
systemd-resolve:x:19119:0:99999:7:::
systemd-timesync:x:19119:0:99999:7:::
systemd-coredump:x:19119:0:99999:7:::
uuidd:x:19119:0:99999:7:::
systemd-oom:x:19119:0:99999:7:::
nobody:x:19119:0:99999:7:::
sshd:!:19119:0:99999:7:::
EOF
chmod -v 600 /pkgs/$PACKAGE/etc/shadow



touch /pkgs/$PACKAGE/var/log/{btmp,lastlog,faillog,wtmp}
chgrp -v utmp /pkgs/$PACKAGE/var/log/lastlog
chmod -v 664  /pkgs/$PACKAGE/var/log/lastlog
chmod -v 600  /pkgs/$PACKAGE/var/log/btmp


cat > /pkgs/$PACKAGE/etc/lsb-release << "EOF"
DISTRIB_ID="Tucana Linux"
DISTRIB_RELEASE="3.0"
DISTRIB_DESCRIPTION="Tucana GNU/Linux"
EOF

cat > /pkgs/$PACKAGE/etc/os-release << "EOF"
NAME="Tucana Linux"
VERSION="3.0"
ID=tucana
PRETTY_NAME="Tucana GNU/Linux 3.0"
VENDOR_NAME="Rahul Chandra"

EOF

cat > /pkgs/$PACKAGE/etc/shells << "EOF"
# A list of shells on the system

/bin/sh
/bin/bash
/bin/zsh

EOF

# Create the early module load file
echo '
# This file is for loading modules in the early boot stages in the initramfs
EARLY_LOAD_MODULES=""' > /pkgs/$PACKAGE/etc/early_load_modules.conf


# Install


cd /pkgs



sudo echo "zlib mercury coreutils util-linux findutils gettext glibc grep sed libgcc iproute2 file procps-ng systemd tar xz zstd psmisc gzip bzip2 bash shadow pam ca-certificates p11-kit wget mkinitramfs kmod efibootmgr grub libffi man-pages man-db less ncurses perl perl-xml-parser openssl e2fsprogs sudo libunistring diffutils gawk iana-etc" > /pkgs/$PACKAGE/depends
sudo echo "coreutils" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished





