#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

URL=https://ftp.gnu.org/gnu/bison/bison-3.8.2.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

./configure --prefix=/usr --docdir=/usr/share/doc/bison-3.8.2



make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "glibc" > /pkgs/$PACKAGE/depends
sudo echo "bash binutils coreutils gcc gettext glibc grep m4 make perl sed" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


