#!/bin/bash
export CFLAGS=-"O2"
export CXXFLAGS="-O2"

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


PACKAGE=build-essentials

cd /blfs/builds

# Build




mkdir -p /pkgs/$PACKAGE/var/cache/mercury/meta-pkgs
echo "gcc binutils gperf flex automake autoconf autoconf213 bc bison diffutils patch gettext cmake meson ninja groff jinja kbd kmod gmp mpc mpfr libelf m4 make libtool pkg-config expat expect check" > /pkgs/$PACKAGE/var/cache/mercury/meta-pkgs/build-essentials


# Install

cd /pkgs



sudo echo "bash coreutils grep m4 make perl sed texinfo" > /pkgs/$PACKAGE/depends
sudo echo "bash coreutils grep m4 make perl sed texinfo" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


