#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


PKG_VER=1.0.8
URL=https://www.sourceware.org/pub/bzip2/bzip2-$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')
set -e
# Get Package

cd /blfs/builds
wget $URL
wget https://www.linuxfromscratch.org/patches/lfs/development/bzip2-$PKG_VER-install_docs-1.patch
tar -xvf $TAR
cd $DIR

# Build


patch -Np1 -i ../bzip2-$PKG_VER-install_docs-1.patch
sed -i 's@\(ln -s -f \)$(PREFIX)/bin/@\1@' Makefile
sed -i "s@(PREFIX)/man@(PREFIX)/share/man@g" Makefile
make -f Makefile-libbz2_so
make clean

make -j20

make -j16



# Install
sudo make PREFIX=/pkgs/$PACKAGE/usr  install


mkdir -p /pkgs/$PACKAGE/usr/bin
mkdir -p /pkgs/$PACKAGE/usr/lib
cp -av libbz2.so.* /pkgs/$PACKAGE/usr/lib
ln -sfv libbz2.so.$PKG_VER /pkgs/$PACKAGE/usr/lib/libbz2.so


cp -v bzip2-shared /pkgs/$PACKAGE/usr/bin/bzip2
for i in /pkgs/$PACKAGE/usr/bin/{bzcat,bunzip2}; do
  ln -sfv bzip2 $i
done

cd /pkgs



sudo echo "bash binutils coreutils diffutils gcc glibc make patch" > /pkgs/$PACKAGE/make-depends
sudo echo "glibc" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished

cp -rpv /pkgs/$PACKAGE/* /

cd /blfs/builds
sudo rm -r $DIR


