#!/bin/bash


PKG_VER=9.5
URL=https://ftp.gnu.org/gnu/coreutils/coreutils-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')
set -e

# Get Package

cd /blfs/builds
wget https://www.linuxfromscratch.org/patches/downloads/coreutils/coreutils-$PKG_VER-i18n-1.patch
wget $URL
tar -xvf $TAR
cd $DIR

# Build
patch -Np1 -i ../coreutils-$PKG_VER-i18n-1.patch
autoreconf -fiv
export FORCE_UNSAFE_CONFIGURE=1
./configure --prefix=/usr                     \
	--enable-install-program=hostname \
        --enable-no-install-program=kill,uptime

make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install

mkdir -p /pkgs/coreutils/usr/sbin
mv -v /usr/bin/chroot /usr/sbin
mv -v /pkgs/coreutils/usr/bin/chroot /pkgs/coreutils/usr/sbin

cd /pkgs



sudo echo "gettext glibc gmp grep libcap openssl attr acl" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


