#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

export CFLAGS=-"O2"
export CXXFLAGS="-O2"
PKG_VER=1.16.0
URL=https://dbus.freedesktop.org/releases/dbus/dbus-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
mkdir build
cd build
meson setup --prefix=/usr --buildtype=release ..

ninja

# Install
sudo DESTDIR=/pkgs/$PACKAGE ninja install
sudo ninja install
cd /pkgs

chown -v root:messagebus /pkgs/$PACKAGE/usr/libexec/dbus-daemon-launch-helper &&
chmod -v      4750       /pkgs/$PACKAGE/usr/libexec/dbus-daemon-launch-helper

sudo echo "glibc systemd expat" > /pkgs/$PACKAGE/depends
sudo echo "meson ninja systemd" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


