#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

URL=https://downloads.sourceforge.net/project/e2fsprogs/e2fsprogs/v1.46.5/e2fsprogs-1.46.5.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build


mkdir -v build
cd       build
../configure --prefix=/usr           \
             --sysconfdir=/etc       \
             --enable-elf-shlibs     \
             --disable-libblkid      \
             --disable-libuuid       \
             --disable-uuidd         \
             --disable-fsck



make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install

rm -fv /pkgs/$PACKAGE/usr/lib/{libcom_err,libe2p,libext2fs,libss}.a
gunzip -v /pkgs/$PACKAGE/usr/share/info/libext2fs.info.gz
install-info --dir-file=/pkgs/$PACKAGE/usr/share/info/dir /pkgs/$PACKAGE/usr/share/info/libext2fs.info

cd /pkgs

sudo cp -rpv $PACKAGE/* /

sudo echo "" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


