#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


PKG_VER=39
URL=https://github.com/rhboot/efivar/releases/download/$PKG_VER/efivar-$PKG_VER.tar.bz2
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build


sed '/prep :/a\\ttouch prep' -i src/Makefile
sed '/sys\/mount\.h/d' -i src/util.h
sed '/unistd\.h/a#include <sys/mount.h>' -i src/gpt.c src/linux.c


make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE  LIBDIR=/usr/lib install
sudo make  LIBDIR=/usr/lib  install
cd /pkgs



sudo echo "glibc" > /pkgs/$PACKAGE/depends
sudo echo "mandoc" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


