#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

PKG_VER=0.23
URL=https://ftp.gnu.org/gnu/gettext/gettext-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package
cd /blfs/builds
if [[ ! -d tucana-pkgs-extra ]]; then
   git clone https://github.com/Tucana-Linux/tucana-pkgs-extra.git
fi
wget $URL
tar -xvf $TAR
cd $DIR

# Build
patch -Np1 < ../tucana-pkgs-extra/gettext/*$PKG_VER*.patch
./configure --prefix=/usr    \
            --disable-static \


make -j20


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs

chmod -v 0755 /usr/lib/preloadable_libintl.so
chmod -v 0755 /pkgs/$PACKAGE/usr/lib/preloadable_libintl.so

sudo echo "acl bash glibc libgcc libunistring" > /pkgs/$PACKAGE/depends
sudo echo "bash binutils coreutils gawk gcc glibc grep make ncurses sed texinfo" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


