#!/bin/bash
URL=https://launchpad.net/intltool/trunk/0.51.0/+download/intltool-0.51.0.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

sed -i 's:\\\${:\\\$\\{:' intltool-update.in
./configure --prefix=/usr

make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "autoconf automake bash glibc grep perl sed" > /pkgs/$PACKAGE/depends
sudo echo "bash gawk glibc make perl sed perl-xml-parser" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


