#!/bin/bash
export CFLAGS=-"O2"
export CXXFLAGS="-O2"

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

URL=https://www.kernel.org/pub/linux/utils/net/iproute2/iproute2-6.1.0.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

sed -i /ARPD/d Makefile
rm -fv man/man8/arpd.8


make NETNS_RUN_DIR=/run/netns -j16


# Install
sudo make SBINDIR=/usr/sbin  DESTDIR=/pkgs/$PACKAGE install
sudo make SBINDIR=/usr/sbin  install
cd /pkgs



sudo echo "bash coreutils glibc libcap libelf zlib" > /pkgs/$PACKAGE/depends
sudo echo "bash bison coreutils flex gcc glibc make libcap libelf linux api headers zlib" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


