#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


PKG_VER=2.6.4
URL=https://www.kernel.org/pub/linux/utils/kbd/kbd-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build


sed -i '/RESIZECONS_PROGS=/s/yes/no/' configure
sed -i 's/resizecons.8 //' docs/man/man8/Makefile.in
./configure --prefix=/usr --disable-vlock

make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
mkdir -pv           /pkgs/$PACKAGE/usr/share/doc/kbd-$PKG_VER
cp -R -v docs/doc/* /pkgs/$PACKAGE/usr/share/doc/kbd-$PKG_VER

cd /pkgs



sudo echo "bash coreutils glibc" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


