#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


PKG_VER=2.73
URL=https://www.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
export GOPATH="$DIR"
sed -i '/install -m.*STA/d' libcap/Makefile


make  prefix=/usr lib=lib GOFLAGS="-buildmode=pie -mod=readonly -modcacherw" GO_BUILD_FLAGS="-ldflags '-compressdwarf=false -linkmode=external'" -j16


# Install
make  DESTDIR=/pkgs/$PACKAGE prefix=/usr lib=lib GOFLAGS="-buildmode=pie -mod=readonly -modcacherw" GO_BUILD_FLAGS="-ldflags '-compressdwarf=false -linkmode=external'" install
cd /pkgs


sudo echo "glibc" > /pkgs/$PACKAGE/depends
sudo echo "glibc" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR
cp -rpv /pkgs/$PACKAGE/* /


