#!/bin/bash
URL=https://sourceware.org/ftp/elfutils/0.188/elfutils-0.188.tar.bz2
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=libelf

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

./configure --prefix=/usr                \
            --disable-debuginfod         \
            --enable-libdebuginfod=dummy


make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE -C libelf  install
install -vm644 config/libelf.pc /pkgs/libelfi/usr/lib/pkgconfig
rm /pkgs/libelf/usr/lib/libelf.a
cd /pkgs



sudo echo "glibc zlib" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR

cp -rpv /pkgs/$PACKAGE/* /
