#!/bin/bash
URL=https://github.com/mesonbuild/meson/releases/download/1.0.0/meson-1.0.0.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')
set -e
# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

pip3 wheel -w dist --no-build-isolation --no-deps $PWD





# Install
python3 setup.py install --root=/pkgs/$PACKAGE --optimize=1
cd /pkgs



sudo echo "ninja python3" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished

cp -rpv /pkgs/meson/* /

cd /blfs/builds
sudo rm -r $DIR


