#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

PKG_VER=1.3.0
URL=https://github.com/mesonbuild/meson/releases/download/$PKG_VER/meson-$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')
set -e
# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

pip3 wheel -w dist --no-build-isolation --no-deps $PWD





# Install
python3 setup.py install --root=/pkgs/$PACKAGE --optimize=1
cd /pkgs



sudo echo "ninja python" > /pkgs/$PACKAGE/depends
sudo echo "setuptools" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished

cp -rpv /pkgs/meson/* /

cd /blfs/builds
sudo rm -r $DIR


