#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

PKG_VER=3.1.0
URL=https://github.com/Tucana-Linux/neptune/releases/download/$PKG_VER/neptune-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=neptune

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
python3 -m build --wheel --skip-dependency-check



# Install
sudo python3 -m installer --destdir=/pkgs/$PACKAGE  dist/*.whl

cd /pkgs

sudo cp -rpv /pkgs/$PACKAGE/* /

sudo echo "python python-requests" > /pkgs/$PACKAGE/depends
sudo echo "python-build python-installer" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


