#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

PKG_VER=0.1.3
URL=https://github.com/Tucana-Linux/neptune/releases/download/$PKG_VER/neptune-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=neptune

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
python3 -m build --wheel --skip-dependency-check



# Install
sudo python3 -m installer --destdir=/pkgs/$PACKAGE  dist/*.whl

cd /pkgs

# make inital directories
mkdir -p /pkgs/$PACKAGE/var/lib/neptune/cache/depend
mkdir -p /pkgs/$PACKAGE/var/lib/neptune/file-lists
mkdir -p /pkgs/$PACKAGE/etc/neptune
mkdir -p /pkgs/$PACKAGE/usr/share/doc/neptune/

# base config
cat > /pkgs/$PACKAGE/etc/neptune/config.yaml << EOF
repositories:
  - "https://repo.tucanalinux.org/development/mercury/"

system-settings:
  install_path: "/"
  yes_mode_by_default: false
  stream_chunk_size: 8192  
EOF
cp /pkgs/$PACKAGE/etc/neptune/config.yaml /pkgs/$PACKAGE/usr/share/doc/neptune/sample-config.yaml

sudo echo "pyyaml python-rich python-requests" > /pkgs/$PACKAGE/depends
sudo echo "python-build python-installer" > /pkgs/$PACKAGE/make-depends
sudo echo "/etc/neptune/config.yaml" > /pkgs/$PACKAGE/backup
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


