#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

URL=https://github.com/ninja-build/ninja/archive/v1.11.1/ninja-1.11.1.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build




export NINJAJOBS=$(nproc)
python3 configure.py --bootstrap


# Install
mkdir -p /pkgs/ninja/usr/bin
install -vm755 ninja /pkgs/ninja/usr/bin/
install -vDm644 misc/bash-completion /pkgs/ninja/usr/share/bash-completion/completions/ninja
install -vDm644 misc/zsh-completion  /pkgs/ninja/usr/share/zsh/site-functions/_ninja

install -vm755 ninja /usr/bin/
install -vDm644 misc/bash-completion /usr/share/bash-completion/completions/ninja
install -vDm644 misc/zsh-completion  /usr/share/zsh/site-functions/_ninja
cd /pkgs



sudo echo "binutils gcc coreutils python" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


