#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"
PKG_VER=3.12.1
URL=https://www.python.org/ftp/python/$PKG_VER/Python-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=python

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

./configure --prefix=/usr        \
            --enable-shared      \
            --with-system-expat  \
            --with-system-ffi    \
            --enable-optimizations \
            --with-ensurepip=install \




make -j20


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
cd /pkgs
mkdir -p /pkgs/python/etc
cat > /pkgs/python/etc/pip.conf << EOF
[global]
root-user-action = ignore
disable-pip-version-check = true
EOF

# For some reason pip does not install by default even with ensurepip on
curl -sSL https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python3 get-pip.py --ignore-installed --root=/pkgs/$PACKAGE
rm get-pip.py


install -v -dm755 /pkgs/python/usr/share/doc/python-$PKG_VER/html

tar --strip-components=1  \
    --no-same-owner       \
    --no-same-permissions \
    -C /pkgs/python/usr/share/doc/python-$PKG_VER/html \
    -xvf ../python-$PKG_VER-docs-html.tar.bz2

sudo cp -rpv /pkgs/$PACKAGE/* /

sudo echo "bzip2 expat libffi zlib openssl sqlite libxcrypt" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


