#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"
PKG_VER=4.17.0
set -e
URL=https://github.com/shadow-maint/shadow/releases/download/$PKG_VER/shadow-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

sed -i 's/groups$(EXEEXT) //' src/Makefile.in          &&

find man -name Makefile.in -exec sed -i 's/groups\.1 / /'   {} \; &&
find man -name Makefile.in -exec sed -i 's/getspnam\.3 / /' {} \; &&
find man -name Makefile.in -exec sed -i 's/passwd\.5 / /'   {} \; &&

sed -e 's@#ENCRYPT_METHOD DES@ENCRYPT_METHOD YESCRYPT@' \
    -e 's@/var/spool/mail@/var/mail@'                   \
    -e '/PATH=/{s@/sbin:@@;s@/bin:@@}'                  \
    -i etc/login.defs          

./configure --sysconfdir=/etc               \
            --disable-static                \
            --without-libbsd                 \
            --with-{b,yes}crypt              \
            --with-group-name-max-length=32 &&


make -j16


# Install
mkdir -p /pkgs/$PACKAGE
make DESTDIR=/pkgs/$PACKAGE exec_prefix=/usr  install
make DESTDIR=/pkgs/$PACKAGE -C  man install-man
cd /pkgs
mkdir -p /etc/default
echo "useradd -D --gid 999" > /pkgs/$PACKAGE/postinst
mkdir -p /pkgs/shadow/etc/default

install -v -Dm644 /pkgs/shadow/etc/login.defs /pkgs/shadow/etc/login.defs.orig &&
for FUNCTION in FAIL_DELAY               \
                FAILLOG_ENAB             \
                LASTLOG_ENAB             \
                MAIL_CHECK_ENAB          \
                OBSCURE_CHECKS_ENAB      \
                PORTTIME_CHECKS_ENAB     \
                QUOTAS_ENAB              \
                CONSOLE MOTD_FILE        \
                FTMP_FILE NOLOGINS_FILE  \
                ENV_HZ PASS_MIN_LEN      \
                SU_WHEEL_ONLY            \
                CRACKLIB_DICTPATH        \
                PASS_CHANGE_TRIES        \
                PASS_ALWAYS_WARN         \
                CHFN_AUTH ENCRYPT_METHOD \
                ENVIRON_FILE
do
    sed -i "s/^${FUNCTION}/# &/" /pkgs/shadow/etc/login.defs
done
mkdir -p /pkgs/shadow/etc/pam.d
cat > /pkgs/shadow/etc/pam.d/login << "EOF"
# Begin /etc/pam.d/login

# Set failure delay before next prompt to 3 seconds
auth      optional    pam_faildelay.so  delay=3000000

# Check to make sure that the user is allowed to login
auth      requisite   pam_nologin.so

# Check to make sure that root is allowed to login
# Disabled by default. You will need to create /etc/securetty
# file for this module to function. See man 5 securetty.
#auth      required    pam_securetty.so

# Additional group memberships - disabled by default
#auth      optional    pam_group.so

# include system auth settings
auth      include     system-auth

# check access for the user
account   required    pam_access.so

# include system account settings
account   include     system-account

# Set default environment variables for the user
session   required    pam_env.so

# Set resource limits for the user
session   required    pam_limits.so

# Display date of last login - Disabled by default
#session   optional    pam_lastlog.so

# Display the message of the day - Disabled by default
#session   optional    pam_motd.so

# Check user's mail - Disabled by default
#session   optional    pam_mail.so      standard quiet

# include system session and password settings
session   include     system-session
password  include     system-password

# End /etc/pam.d/login
EOF

cat > /pkgs/shadow/etc/pam.d/passwd << "EOF"
# Begin /etc/pam.d/passwd

password  include     system-password

# End /etc/pam.d/passwd
EOF

cat > /pkgs/shadow/etc/pam.d/su << "EOF"
# Begin /etc/pam.d/su

# always allow root
auth      sufficient  pam_rootok.so

# Allow users in the wheel group to execute su without a password
# disabled by default
#auth      sufficient  pam_wheel.so trust use_uid

# include system auth settings
auth      include     system-auth

# limit su to users in the wheel group
# disabled by default
#auth      required    pam_wheel.so use_uid

# include system account settings
account   include     system-account

# Set default environment variables for the service user
session   required    pam_env.so

# include system session settings
session   include     system-session

# End /etc/pam.d/su
EOF



cat > /pkgs/shadow/etc/pam.d/chpasswd << "EOF"
# Begin /etc/pam.d/chpasswd

# always allow root
auth      sufficient  pam_rootok.so

# include system auth and account settings
auth      include     system-auth
account   include     system-account
password  include     system-password

# End /etc/pam.d/chpasswd
EOF

sed -e 's/chpasswd/newusers/' /pkgs/shadow/etc/pam.d/chpasswd >/pkgs/shadow/etc/pam.d/newusers

cat > /pkgs/shadow/etc/pam.d/chage << "EOF"
# Begin /etc/pam.d/chage

# always allow root
auth      sufficient  pam_rootok.so

# include system auth and account settings
auth      include     system-auth
account   include     system-account

# End /etc/pam.d/chage
EOF

for PROGRAM in chfn chgpasswd chsh groupadd groupdel \
               groupmems groupmod useradd userdel usermod
do
    install -v -m644 /pkgs/shadow/etc/pam.d/chage /pkgs/shadow/etc/pam.d/${PROGRAM}
    sed -i "s/chage/$PROGRAM/"  /pkgs/shadow/etc/pam.d/${PROGRAM}
done
[ -f /pkgs/shadow/etc/login.access ] && mv -v /pkgs/shadow/etc/login.access{,.NOUSE}
[ -f /pkgs/shadow/etc/limits ] && mv -v /pkgs/shadow/etc/limits{,.NOUSE}


sudo echo "glibc pam" > /pkgs/$PACKAGE/depends
sudo echo "acl attr bash binutils coreutils diffutils findutils gawk gcc gettext glibc grep libcap make sed pam" > /pkgs/$PACKAGE/make-depends
sudo echo "pwconv && grpconv && useradd -D --gid 999" > /pkgs/$PACKAGE/postinst
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished




#cp -rpv shadow/* /



cd /blfs/builds
sudo rm -r $DIR


