#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


PKG_VER=1.9.16
URL=https://www.sudo.ws/dist/sudo-$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

./configure --prefix=/usr              \
            --libexecdir=/usr/lib      \
            --with-secure-path         \
            --with-all-insults         \
            --with-env-editor          \
            --with-passprompt="[sudo] password for %p: "


make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
ln -sfv libsudo_util.so.0.0.0 /pkgs/$PACKAGE/usr/lib/sudo/libsudo_util.so.0

mkdir -p /pkgs/$PACKAGE/etc/pam.d

cat > /pkgs/$PACKAGE/etc/pam.d/sudo << "EOF"
# Begin /etc/pam.d/sudo

# include the default auth settings
auth      include     system-auth

# include the default account settings
account   include     system-account

# Set default environment variables for the service user
session   required    pam_env.so

# include system session defaults
session   include     system-session

# End /etc/pam.d/sudo
EOF
chmod 644 /etc/pam.d/sudo

cat > /pkgs/$PACKAGE/etc/sudoers.d/00-sudo << "EOF"
Defaults secure_path="/usr/sbin:/usr/bin"
%wheel ALL=(ALL) ALL
EOF

cd /pkgs

echo "pam glibc " > /pkgs/$PACKAGE/depends
echo "" > /pkgs/$PACKAGE/make-depends
tar -cvzpf $PACKAGE.tar.xz $PACKAGE
cp $PACKAGE.tar.xz /finished



cd /blfs/builds
sudo rm -r $DIR


