#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


set -e

PKG_VER=254
URL=https://github.com/systemd/systemd/archive/v$PKG_VER/systemd-$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
sed -i -e 's/GROUP="render"/GROUP="video"/' \
       -e 's/GROUP="sgx", //' rules.d/50-udev-default.rules.in


sed '/bus_message_type_from_string/s/_pure_//' \
    -i src/libsystemd/sd-bus/bus-internal.h    &&
sed '/devt_hash_func/s/_pure_//'               \
    -i src/basic/hash-funcs.h                  &&
sed '/job_get_timeout/s/_pure_//'              \
    -i src/core/job.h

mkdir build
cd build

meson --prefix=/usr                 \
      --buildtype=release           \
      -Ddefault-dnssec=no           \
      -Dfirstboot=false             \
      -Dinstall-tests=false         \
      -Dldconfig=false              \
      -Dman=auto                    \
      -Dsysusers=false              \
      -Drpmmacrosdir=no             \
      -Dhomed=false                 \
      -Duserdb=false                \
      -Dmode=release                \
      -Dpam=true                    \
      -Dpamconfdir=/etc/pam.d       \
      -Dsbat-distro-url=https://github.com/xXTeraXx/Tucana \
      ..      
      
ninja


# Install
sudo  DESTDIR=/pkgs/$PACKAGE ninja install
sudo ninja install
cd /pkgs
grep 'pam_systemd' /etc/pam.d/system-session ||

cat >> /etc/pam.d/system-session << "EOF"
# Begin Systemd addition

session  required    pam_loginuid.so
session  optional    pam_systemd.so

# End Systemd addition
EOF

cat > /etc/pam.d/systemd-user << "EOF"
# Begin /etc/pam.d/systemd-user

account  required    pam_access.so
account  include     system-account

session  required    pam_env.so
session  required    pam_limits.so
session  required    pam_unix.so
session  required    pam_loginuid.so
session  optional    pam_keyinit.so force revoke
session  optional    pam_systemd.so

auth     required    pam_deny.so
password required    pam_deny.so

# End /etc/pam.d/systemd-user
EOF


# Usually there would be a modification to the pam,d system-sessions file, that is done during the pam build

cat > /pkgs/$PACKAGE/etc/pam.d/systemd-user << "EOF"
# Begin /etc/pam.d/systemd-user

account  required    pam_access.so
account  include     system-account

session  required    pam_env.so
session  required    pam_limits.so
session  required    pam_unix.so
session  required    pam_loginuid.so
session  optional    pam_keyinit.so force revoke
session  optional    pam_systemd.so

auth     required    pam_deny.so
password required    pam_deny.so

# End /etc/pam.d/systemd-user
EOF

# Needed for steam to run
ln -s /usr/lib/libudev.so.1 /pkgs/$PACKAGE/usr/lib/libudev.so.0


sudo echo "cryptsetup pam glibc util-linux libcap acl attr libidn2 libseccomp iptables dbus libgcrypt p11-kit libxcrypt" > /pkgs/$PACKAGE/depends
sudo echo "pam glibc util-linux libcap acl attr gnu-efi jinja" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


