#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

PKG_VER=8.6.12
URL=https://downloads.sourceforge.net/tcl/tcl$PKG_VER-src.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=tcl$PKG_VER
PACKAGE=tcl

# Get Package

cd /blfs/builds
wget $URL
wget https://downloads.sourceforge.net/tcl/tcl8.6.12-html.tar.gz
tar -xvf $TAR
cd $DIR

# Build

tar -xf ../tcl8.6.12-html.tar.gz --strip-components=1
SRCDIR=$(pwd)
cd unix
./configure --prefix=/usr           \
            --mandir=/usr/share/man


make -j16

sed -e "s|$SRCDIR/unix|/usr/lib|" \
    -e "s|$SRCDIR|/usr/include|"  \
    -i tclConfig.sh

sed -e "s|$SRCDIR/unix/pkgs/tdbc1.1.3|/usr/lib/tdbc1.1.3|" \
    -e "s|$SRCDIR/pkgs/tdbc1.1.3/generic|/usr/include|"    \
    -e "s|$SRCDIR/pkgs/tdbc1.1.3/library|/usr/lib/tcl8.6|" \
    -e "s|$SRCDIR/pkgs/tdbc1.1.3|/usr/include|"            \
    -i pkgs/tdbc1.1.3/tdbcConfig.sh

sed -e "s|$SRCDIR/unix/pkgs/itcl4.2.2|/usr/lib/itcl4.2.2|" \
    -e "s|$SRCDIR/pkgs/itcl4.2.2/generic|/usr/include|"    \
    -e "s|$SRCDIR/pkgs/itcl4.2.2|/usr/include|"            \
    -i pkgs/itcl4.2.2/itclConfig.sh

unset SRCDIR


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs

chmod -v u+w /pkgs/tcl/usr/lib/libtcl8.6.so
chmod -v u+w /usr/lib/libtcl8.6.so

make install-private-headers
make DESTDIR=/pkgs/$PACKAGE install-private-headers
ln -sfv tclsh8.6 /usr/bin/tclsh
ln -sfv tclsh8.6 /pkgs/tcl/usr/bin/tclsh
mv /usr/share/man/man3/{Thread,Tcl_Thread}.3
mv /pkgs/tcl/usr/share/man/man3/{Thread,Tcl_Thread}.3

sudo echo "glibc zlib" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


