#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

URL=https://github.com/facebook/zstd/releases/download/v1.5.4/zstd-1.5.4.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build


make prefix=/usr -j16


# Install
sudo make prefix=/usr DESTDIR=/pkgs/$PACKAGE install
sudo make prefix=/usr install
rm -v /usr/lib/libzstd.a
rm -v /pkgs/zstd/usr/lib/libzstd.a
cd /pkgs



sudo echo "lz4" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


