#!/bin/bash
URL=https://github.com/facebook/zstd/releases/download/v1.5.2/zstd-1.5.2.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
wget https://www.linuxfromscratch.org/patches/lfs/development/zstd-1.5.2-upstream_fixes-1.patch
tar -xvf $TAR
cd $DIR

# Build


patch -Np1 -i ../zstd-1.5.2-upstream_fixes-1.patch

make prefix=/usr -j16


# Install
sudo make prefix=/usr DESTDIR=/pkgs/$PACKAGE install
sudo make prefix=/usr install
rm -v /usr/lib/libzstd.a
rm -v /pkgs/zstd/usr/lib/libzstd.a
cd /pkgs



sudo echo "lz4" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


