#!/bin/bash
GNOME_MAJOR=43
GNOME_MINOR=0
URL=https://download.gnome.org/sources/gnome-settings-daemon/$GNOME_MAJOR/gnome-settings-daemon-$GNOME_MAJOR.$GNOME_MINOR.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir build &&
cd    build &&

meson --prefix=/usr --buildtype=release .. &&


ninja -j16


# Install
ninja install && DESTDIR=/pkgs/$PACKAGE ninja install
cd /pkgs



sudo echo "alsa-lib colord fontconfig gcr-4 geoclue geocode-glib gnome-desktop lcms libcanberra libgweather libnotify pulseaudio libwacom systemd upower cups nss wayland network-manager geocode-glib-2" > /pkgs/$PACKAGE/depends
sudo rm -r /pkgs/$PACKAGE/blfs
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


