#!/bin/bash
URL=https://github.com/ddccontrol/ddccontrol-db.git
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.git||g')
PACKAGE=ddccontrol-db
set -e
# Get Package

cd /blfs/builds
git clone $URL
cd $DIR

# Build
./autogen.sh
./configure --prefix=/usr


make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


