#!/bin/bash
URL=https://github.com/LibVNC/x11vnc/archive/refs/tags/0.9.16.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g' | sed 's/^/x11vnc-/')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
wget https://github.com/LibVNC/x11vnc/commit/a48b0b1cd887.patch
tar -xvf $TAR
cd $DIR

# Build

patch -Np1 < ../a48b0b1cd887.patch
./autogen.sh
./configure --prefix=/usr


make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "libvncserver xorg-libs avahi" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


