#!/bin/bash
bash qca-qt5
bash attica5
bash karchive5
bash kcodecs5
bash kconfig5
bash kcoreaddons5
bash kdbusaddons5
bash kguiaddons5
bash ki18n5
bash kitemviews5
bash kwidgetaddons5
bash kwindowsystem5
bash solid5
bash sonnet5
bash kauth5
bash kcompletion5
bash kcrash5
bash kconfigwidgets5
bash kservice5
bash kglobalaccel5
bash kpackage5
bash kiconthemes5
bash kjobwidgets5
bash knotifications5
bash ktextwidgets5
bash kxmlgui5
bash kbookmarks5
bash kwallet5
bash kded5
bash kio5
bash kirigami2
bash syndication5
bash knewstuff5
bash frameworkintegration5
bash kwayland5

