#!/bin/bash
URL=https://download.savannah.gnu.org/releases/attr/attr-2.5.1.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=lib32-$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
export CC="gcc -m32"
./configure --prefix=/usr     \
            --disable-static  \
            --sysconfdir=/etc \
            --docdir=/usr/share/doc/attr-2.5.1 \
	    --host=i686-pc-linux-gnu \
	    --libdir=/usr/lib32 \


make -j16


# Install
mkdir -p /pkgs/$PACKAGE/usr/lib32
make DESTDIR=$PWD/DESTDIR install
cp -Rv DESTDIR/usr/lib32/* /pkgs/$PACKAGE/usr/lib32
rm -rf DESTDIR
cp -rpv /pkgs/$PACKAGE/* /

cd /pkgs



sudo echo "attr lib32-glibc lib32-libgcc" > /pkgs/$PACKAGE/depends
sudo echo "bash binutils coreutils gcc gettext glibc grep m4 make perl sed texinfo" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


