#!/bin/bash
URL=https://astron.com/pub/file/file-5.44.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=lib32-$(echo $DIR | sed 's|-[^-]*$||g')
set -e
# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

export CC="gcc -m32"
./configure --prefix=/usr    --libdir=/usr/lib32  --host=i686-pc-linux-gnu

make -j20


# Install
mkdir -p /pkgs/$PACKAGE/usr/lib32
make DESTDIR=$PWD/DESTDIR install
cp -Rv DESTDIR/usr/lib32/* /pkgs/$PACKAGE/usr/lib32
rm -rf DESTDIR
cp -rpv /pkgs/$PACKAGE/* /
cd /pkgs



sudo echo "glibc bzip2 xz zlib" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


