#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "

PKG_VER=2.82.4
MINOR=$(echo $PKG_VER | sed 's|.[^.]*$||g') 
URL=https://download.gnome.org/sources/glib/$MINOR/glib-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=lib32-$(echo $DIR | sed 's|-[^-]*$||g')
set -e
export CC="gcc -m32"
export CXX="gcc -m32"
export CFLAGS+="-mstackrealign" 
export CXXFLAGS+="-mstackrealign"
export PKG_CONFIG="i686-pc-linux-gnu-pkg-config"
# Get Package
cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
mkdir build
cd build

meson setup --prefix=/usr       \
      --buildtype=release \
      -Dman=false          \
      -Dglib_debug=disabled \
      -Dselinux=disabled \
      -Dintrospection=disabled \
      -Dsysprof=disabled \
      -Dgtk_doc=false \
       --libdir=/usr/lib32 \
      ..     


ninja


# Install
mkdir -p /pkgs/$PACKAGE/usr/lib32
mkdir -p /pkgs/$PACKAGE/usr/bin
DESTDIR=$PWD/DESTDIR ninja install

cp -Rv DESTDIR/usr/lib32/* /pkgs/$PACKAGE/usr/lib32
cp -Rv DESTDIR/usr/bin/gio-querymodules /pkgs/$PACKAGE/usr/bin/gio-querymodules-32

rm -rf DESTDIR
cp -rpv /pkgs/$PACKAGE/* /

cd /pkgs


sudo echo "glib lib32-pcre2 lib32-libffi lib32-util-linux lib32-zlib" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


