#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2 "

set -e
URL=https://github.com/systemd/systemd/archive/v253/systemd-253.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=lib32-$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

export CFLAGS+="-m32"
export CXXFLAGS+="-m32"
export PKG_CONFIG="i686-pc-linux-gnu-pkg-config"

sed -i -e 's/GROUP="render"/GROUP="video"/' \
       -e 's/GROUP="sgx", //' rules.d/50-udev-default.rules.in

mkdir build
cd build

meson --prefix=/usr                 \
      --buildtype=release           \
      -Ddefault-dnssec=no           \
      -Dfirstboot=false             \
      -Dinstall-tests=false         \
      -Dldconfig=false              \
      -Dman=auto                    \
      -Dsysusers=false              \
      -Drpmmacrosdir=no             \
      -Dhomed=false                 \
      -Duserdb=false                \
      -Dmode=release                \
      -Dpamconfdir=/etc/pam.d       \
      -Ddocdir=/usr/share/doc/systemd-252 \
      -Dsbat-distro-url=https://github.com/xXTeraXx/Tucana \
      --libdir=/usr/lib32 \
      ..      
      
ninja



# Install
mkdir -p /pkgs/$PACKAGE/usr/lib32
DESTDIR=$PWD/DESTDIR ninja install
cp -Rv DESTDIR/usr/lib32/* /pkgs/$PACKAGE/usr/lib32
rm -rf DESTDIR
cp -rpv /pkgs/$PACKAGE/* /
cd /pkgs
# Needed for steam
ln -sfv /usr/lib32/libudev.so.1 /pkgs/$PACKAGE/usr/lib32/libudev.so.0

sudo echo "lib32-dbus lib32-glibc systemd" > /pkgs/$PACKAGE/depends
sudo echo "pam glibc util-linux libcap acl attr gnu-efi" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


