#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "
PKG_VER=$(
URL=https://ftp.gnu.org/gnu/nettle/nettle-3.8.1.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=lib32-$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package
export CFLAGS+="-m32" 
export CXXFLAGS+="-m32"
export PKG_CONFIG="i686-pc-linux-gnu-pkg-config"
cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build


./configure --prefix=/usr --disable-static  --libdir=/usr/lib32

make -j16


# Install


mkdir -p /pkgs/$PACKAGE/usr/lib32
make DESTDIR=$PWD/DESTDIR install
cp -Rv DESTDIR/usr/lib32/* /pkgs/$PACKAGE/usr/lib32
rm -rf DESTDIR
cp -rpv /pkgs/$PACKAGE/* /
cd /pkgs



sudo echo "nettle lib32-glibc" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


