#!/bin/bash
URL=https://github.com/lm-sensors/lm-sensors/archive/V3-6-0/lm-sensors-3-6-0.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=lib32-lm-sensors

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

export CC="gcc -m32" 
export CXX="g++ -m32"
export PKG_CONFIG="i686-pc-linux-gnu-pkg-config"


make PREFIX=/usr        \
     BUILD_STATIC_LIB=0 \
     MANDIR=/usr/share/man LIBDIR=/usr/lib32 -j20




# Install
mkdir -p /pkgs/$PACKAGE/usr/lib32
make PREFIX=/usr        \
     BUILD_STATIC_LIB=0 \
     MANDIR=/usr/share/man \
     LIBDIR=/usr/lib32 \
     DESTDIR=$PWD/DESTDIR \
     install
cp -Rv DESTDIR/usr/lib32/* /pkgs/$PACKAGE/usr/lib32
rm -rf DESTDIR
cp -rpv /pkgs/$PACKAGE/* /
cd /pkgs



sudo echo "lm-sensors lib32-glibc" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


