#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "

PKG_VER=32
 
URL=https://www.kernel.org/pub/linux/utils/kernel/kmod/kmod-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=lib32-$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
export CC="gcc -m32"

./configure --prefix=/usr          \
            --sysconfdir=/etc      \
            --with-openssl         \
	    --disable-manpages \
            --with-xz              \
            --with-zstd            \
            --with-zlib \
	    --with-rootlibdir=/usr/lib32 \
	    --host=i686-pc-linux-gnu \



make -j20

# Install
mkdir -p /pkgs/$PACKAGE/usr/lib32
make DESTDIR=$PWD/DESTDIR install
cp -Rv DESTDIR/usr/lib32/* /pkgs/$PACKAGE/usr/lib32
rm -rf DESTDIR
cp -rpv /pkgs/$PACKAGE/* /

cd /pkgs


sudo echo "kmod lib32-glibc lib32-libgcc lib32-zlib lib32-xz" > /pkgs/$PACKAGE/depends
sudo echo "bash binutils bison coreutils flex gcc gettext glibc gzip make openssl pkg-config sed xz zlib" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


