#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "


PKG_VER=3.4.6
 
URL=https://github.com/libffi/libffi/releases/download/v$PKG_VER/libffi-$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=lib32-$(echo $DIR | sed 's|-[^-]*$||g')
set -e
# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

# Core 2 Compatibility , if you have a problem with this, consider if your system is even capable of running Tucana then open a github issue with your situation
export CC="gcc -m32" CXX="g++ -m32"
./configure --prefix=/usr          \
            --disable-static       \
            --with-gcc-arch=i686 \
            --disable-exec-static-tramp \
	    --host=i686-pc-linux-gnu \
	    --libdir=/usr/lib32 


make -j16


# Install

mkdir -p /pkgs/$PACKAGE/usr/lib32
make DESTDIR=$PWD/DESTDIR install
cp -Rv DESTDIR/usr/lib32/* /pkgs/$PACKAGE/usr/lib32
rm -rf DESTDIR
cp -rpv /pkgs/$PACKAGE/* /

cd /pkgs



sudo echo "libffi lib32-glibc" > /pkgs/$PACKAGE/depends
sudo echo "bash binutils coreutils gcc glibc make sed" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


