#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "

PKG_VER=0.192
 
URL=https://sourceware.org/ftp/elfutils/$PKG_VER/elfutils-$PKG_VER.tar.bz2
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=lib32-libelf

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
export CC="gcc -m32"
./configure --prefix=/usr                \
            --disable-debuginfod         \
            --enable-libdebuginfod=dummy \
	    --libdir=/usr/lib32 \
	    --host=i686-pc-linux-gnu \


make -j20


# Install
make DESTDIR=$PWD/DESTDIR -C libelf install
mkdir -p /pkgs/$PACKAGE/usr/lib32
install -vDm644 config/libelf.pc DESTDIR/usr/lib32/pkgconfig/libelf.pc
cp -Rv DESTDIR/usr/lib32/* /pkgs/$PACKAGE/usr/lib32
rm -rf DESTDIR
cp -rpv /pkgs/$PACKAGE/* /
cd /pkgs



sudo echo "lib32-bzip2 lib32-libgcc lib32-xz lib32-zlib lib32-zstd libelf" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR

cp -rpv /pkgs/$PACKAGE/* /
