#!/bin/bash

export CFLAGS="-m32 -O2"
export CXXFLAGS="-m32 -O2"
export PKG_CONFIG="i686-pc-linux-gnu-pkg-config"

PKG_VER=0.21.5
URL=https://github.com/rockdaboot/libpsl/releases/download/$PKG_VER/libpsl-$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=lib32-$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
sed -i 's/env python/&3/' src/psl-make-dafsa    
./configure --prefix=/usr --disable-static --libdir=/usr/lib32 PYTHON=python3 


make -j16


# Install
mkdir -p /pkgs/$PACKAGE/usr/lib32
make DESTDIR=$PWD/DESTDIR install
cp -Rv DESTDIR/usr/lib32/* /pkgs/$PACKAGE/usr/lib32/
rm -rf DESTDIR
cp -rpv /pkgs/$PACKAGE/* /
cd /pkgs



sudo echo "libpsl lib32-glibc" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


