#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "

URL=https://download.savannah.nongnu.org/releases/libunwind/libunwind-1.6.2.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=lib32-$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

export CFLAGS+="-m32" 
export CXXFLAGS+="-m32"
export PKG_CONFIG="i686-pc-linux-gnu-pkg-config"



./configure --prefix=/usr --disable-static  --libdir=/usr/lib32 --host=i686-pc-linux-gnu



make -j16


# Install
mkdir -p /pkgs/$PACKAGE/usr/lib32
mkdir -p /pkgs/$PACKAGE/usr/include
make DESTDIR=$PWD/DESTDIR install
cp -Rv DESTDIR/usr/lib32/* /pkgs/$PACKAGE/usr/lib32
cp -Rv DESTDIR/usr/include/libunwind-x86.h /pkgs/$PACKAGE/usr/include
rm -rf DESTDIR
cp -rpv /pkgs/$PACKAGE/* /
cd /pkgs



sudo echo "lib32-glibc libunwind" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


