#!/bin/bash
export CFLAGS=-"O2"
export CXXFLAGS="-O2"

URL=https://download.gnome.org/sources/libxml2/2.10/libxml2-2.10.0.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=lib32-$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
export CFLAGS="-m32"
  export PKG_CONFIG=i686-pc-linux-gnu-pkg-config
export CXXFLAGS="-m32"
autoreconf -fiv
./configure --prefix=/usr           \
            --sysconfdir=/etc       \
            --disable-static        \
            --with-history          \
	    --without-python \
            --docdir=/usr/share/doc/libxml2-2.10.0 \
            --libdir=/usr/lib32 \
	    --host=i686-pc-linux-gnu \


make -j16


# Install
mkdir -p /pkgs/$PACKAGE/usr/lib32
make DESTDIR=$PWD/DESTDIR install
cp -Rv DESTDIR/usr/lib32/* /pkgs/$PACKAGE/usr/lib32
rm -rf DESTDIR
cp -rpv /pkgs/$PACKAGE/* /
cd /pkgs



sudo echo "libxml2 lib32-glibc lib32-zlib lib32-icu lib32-xz" > /pkgs/$PACKAGE/depends
sudo echo "icu" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


