#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "


PKG_VER=0.23
 
URL=https://ftp.gnu.org/gnu/gettext/gettext-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=lib32-$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package
cd /blfs/builds
if [[ ! -d tucana-pkgs-extra ]]; then
  git clone https://github.com/Tucana-Linux/tucana-pkgs-extra.git
fi
wget $URL
tar -xvf $TAR
cd $DIR

# Build
export CC="gcc -m32"
export CXX="g++ -m32"
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
patch -Np1  < ../tucana-pkgs-extra/gettext/*$PKG_VER*.patch

./configure --prefix=/usr    \
            --disable-static \
	    --libdir=/usr/lib32 \


make -j16


# Install
mkdir -p /pkgs/$PACKAGE/usr/lib32
make DESTDIR=$PWD/DESTDIR install
cp -Rv DESTDIR/usr/lib32/* /pkgs/$PACKAGE/usr/lib32
rm -rf DESTDIR
cp -rpv /pkgs/$PACKAGE/* /

cd /pkgs

chmod -v 0755 /pkgs/$PACKAGE/usr/lib32/preloadable_libintl.so

cp -rpv /pkgs/$PACKAGE/* /

sudo echo "gettext lib32-glibc lib32-libgcc" > /pkgs/$PACKAGE/depends
sudo echo "bash binutils coreutils gawk gcc lib32-glibc glibc grep make ncurses sed texinfo" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


