#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "

PKG_VER=2.40.2

URL=https://www.kernel.org/pub/linux/utils/util-linux/v$MAJOR/util-linux-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=lib32-$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package
export CFLAGS+="-m32" 
export CXXFLAGS+="-m32"
export PKG_CONFIG="i686-pc-linux-gnu-pkg-config"
cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
./configure ADJTIME_PATH=/var/lib/hwclock/adjtime   \
            --bindir=/usr/bin    \
            --libdir=/usr/lib32    \
            --sbindir=/usr/sbin  \
            --docdir=/usr/share/doc/util-linux-2.38.1 \
            --disable-chfn-chsh  \
            --disable-login      \
            --disable-nologin    \
            --disable-su         \
            --disable-setpriv    \
            --disable-runuser    \
            --disable-pylibmount \
            --disable-static     \
            --without-python \
	    --host=i686-pc-linux-gnu \


make lib{uuid,blkid,fdisk,mount,smartcols}.la -j20


# Install
mkdir -p /pkgs/$PACKAGE/usr/lib32
make DESTDIR=$PWD/DESTDIR    install-usrlib_execLTLIBRARIES install-pkgconfigDATA
cp -Rv DESTDIR/usr/lib32/* /pkgs/$PACKAGE/usr/lib32
rm -rf DESTDIR
cp -rpv /pkgs/$PACKAGE/* /
cd /pkgs


sudo echo "util-linux lib32-glibc" > /pkgs/$PACKAGE/depends
sudo echo "bash binutils coreutils diffutils eudev findutils gawk libgcc gettext glibc grep libcap make ncurses sed zlib" > /pkgs/$PACKAGE/make-depends

sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


