#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "

URL=https://download.gnome.org/sources/pango/1.50/pango-1.50.12.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=lib32-$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

export CFLAGS+="-m32" 
export CXXFLAGS+="-m32"
export PKG_CONFIG="i686-pc-linux-gnu-pkg-config"


mkdir build
cd build


meson --prefix=/usr --buildtype=release --wrap-mode=nofallback --libdir=/usr/lib32 -Dintrospection=disabled .. 


ninja


# Install
mkdir -p /pkgs/$PACKAGE/usr/lib32
DESTDIR=$PWD/DESTDIR ninja install
cp -Rv DESTDIR/usr/lib32/* /pkgs/$PACKAGE/usr/lib32
rm -rf DESTDIR
cp -rpv /pkgs/$PACKAGE/* /
cd /pkgs



sudo echo "lib32-fontconfig lib32-freetype2 lib32-fribidi lib32-glib pango" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


