#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2 "

PKG_VER=1.2.59
URL=https://sourceforge.net/projects/libpng/files/libpng-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=lib32-$(echo $DIR | sed 's|-[^-]*$||g')12

# Get Package


export CFLAGS+="-m32" 
export CXXFLAGS+="-m32"
export PKG_CONFIG="i686-pc-linux-gnu-pkg-config"

cd /blfs/builds
wget $URL
wget "https://sourceforge.net/projects/libpng-apng/files/libpng12/$PKG_VER/libpng-$PKG_VER-apng.patch.gz"
tar -xvf $TAR
cd $DIR

# Build

gzip -cd ../libpng-$PKG_VER-apng.patch.gz | patch -p1


./configure --prefix=/usr --disable-static --libdir=/usr/lib32

make -j16


# Install

make DESTDIR=/pkgs/$PACKAGE install
mkdir -p /pkgs/$PACKAGE/usr/lib32
# thanks arch... saved me a lot of time and line space
rm -rf /pkgs/$PACKAGE/usr/{bin,include/*.h,lib32/{libpng.{a,so},pkgconfig},share}
rm -rf /pkgs/$PACKAGE/usr/include
cd /pkgs



sudo echo "lib32-zlib libpng12" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


