#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "

PKG_VER=R_2_6_3
PKG_VER_REFORMAT=$(echo $PKG_VER | sed 's/R_//g' | sed 's/_/\./g')
URL=https://github.com/libexpat/libexpat/releases/download/$PKG_VER/expat-$PKG_VER_REFORMAT.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=lib32-$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
export CC="gcc -m32"
./configure --prefix=/usr    \
            --disable-static \
            --docdir=/usr/share/doc/expat-$PKG_VER \
	    --libdir=/usr/lib32 \
	    --host=i686-pc-linux-gnu


make -j20


# Install

mkdir -p /pkgs/$PACKAGE/usr/lib32
make DESTDIR=$PWD/DESTDIR install
cp -Rv DESTDIR/usr/lib32/* /pkgs/$PACKAGE/usr/lib32
rm -rf DESTDIR
cp -rpv /pkgs/$PACKAGE/* /

cd /pkgs




sudo echo "expat lib32-glibc" > /pkgs/$PACKAGE/depends
sudo echo "bash binutils coreutils gawk gcc glibc grep make sed" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


