#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "

PKG_VER=2.70
 
URL=https://www.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=lib32-$(echo $DIR | sed 's|-[^-]*$||g')
set -e
# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

sed -i '/install -m.*STA/d' libcap/Makefile

make  prefix=/usr CC="gcc -m32" lib=lib32 -j16


# Install
sudo make prefix=$PWD/DESTDIR/usr lib=lib32 install
mkdir -p /pkgs/$PACKAGE/usr/lib32
sed -e "s|^libdir=.*|libdir=/usr/lib32|" -i DESTDIR/usr/lib32/pkgconfig/lib{cap,psx}.pc
cp -Rv DESTDIR/usr/lib32/* /pkgs/$PACKAGE/usr/lib32
rm -rf DESTDIR
cp -rpv /pkgs/$PACKAGE/* /

cd /pkgs



sudo echo "lib32-glibc libcap" > /pkgs/$PACKAGE/depends
sudo echo "glibc" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


