#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "

PKG_VER=1.6.44
 
URL=https://downloads.sourceforge.net/libpng/libpng-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=lib32-$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package
export CFLAGS+="-m32" 
export CXXFLAGS+="-m32"
cd /blfs/builds
wget $URL
wget https://downloads.sourceforge.net/sourceforge/libpng-apng/libpng-$PKG_VER-apng.patch.gz
tar -xvf $TAR
cd $DIR

# Build

gzip -cd ../libpng-$PKG_VER-apng.patch.gz | patch -p1


./configure --prefix=/usr --disable-static  --libdir=/usr/lib32

make -j16


# Install
mkdir -p /pkgs/$PACKAGE/usr/lib32
make DESTDIR=$PWD/DESTDIR install
cp -Rv DESTDIR/usr/lib32/* /pkgs/$PACKAGE/usr/lib32
rm -rf DESTDIR
cp -rpv /pkgs/$PACKAGE/* /
cd /pkgs



sudo echo "libpng lib32-zlib" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


