#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "
PKG_VER=76.1
MAJOR=$(echo $PKG_VER | sed 's/\./-/g')
REFORMAT=$(echo $PKG_VER | sed 's/\./_/g')
URL=https://github.com/unicode-org/icu/releases/download/release-$MAJOR/icu4c-$REFORMAT-src.tgz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=icu
PACKAGE=lib32-$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

export CFLAGS+="-m32" 
export CXXFLAGS+="-m32"
cd source
./configure --prefix=/usr --libdir=/usr/lib32 --host=i686-pc-linux-gnu --disable-clang


make -j16


# Install


mkdir -p /pkgs/$PACKAGE/usr/lib32
make DESTDIR=$PWD/DESTDIR install
cp -Rv DESTDIR/usr/lib32/* /pkgs/$PACKAGE/usr/lib32
rm -rf DESTDIR
cp -rpv /pkgs/$PACKAGE/* /

cd /pkgs



sudo echo "lib32-libgcc icu" > /pkgs/$PACKAGE/depends
sudo echo "python clang" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


