#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "

PKG_VER=19.1.1
URL=https://github.com/KhronosGroup/SPIRV-LLVM-Translator/archive/v$PKG_VER/SPIRV-LLVM-Translator-$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=lib32-spirv-llvm-translator

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

export CFLAGS+="-m32"
export CXXFLAGS+="-m32"
export PKG_CONFIG="i686-pc-linux-gnu-pkg-config"
mkdir build
cd build

cmake -D CMAKE_INSTALL_PREFIX=/usr               \
      -D CMAKE_BUILD_TYPE=Release                \
      -D BUILD_SHARED_LIBS=ON                    \
      -D CMAKE_SKIP_INSTALL_RPATH=ON             \
      -D LLVM_EXTERNAL_SPIRV_HEADERS_SOURCE=/usr \
      -D CMAKE_INSTALL_LIBDIR=lib32 \
      -G Ninja ..

ninja


# Install
mkdir -p /pkgs/$PACKAGE/usr/lib32
DESTDIR=$PWD/DESTDIR ninja install
cp -Rv DESTDIR/usr/lib32/* /pkgs/$PACKAGE/usr/lib32
rm -rf DESTDIR
cp -rpv /pkgs/$PACKAGE/* /
cd /pkgs



sudo echo "lib32-libxml2 lib32-llvm lib32-spirv-tools spirv-llvm-translator" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


