#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2 "

URL=https://github.com/PipeWire/pipewire/archive/0.3.61/pipewire-0.3.61.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=lib32-$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
export CFLAGS+="-m32" 
export CXXFLAGS+="-m32"
export PKG_CONFIG="i686-pc-linux-gnu-pkg-config"



mkdir build
cd build


meson --prefix=/usr --buildtype=release -Dsession-managers= --libdir=/usr/lib32 -Dsdl2=disabled ..

ninja


# Install
mkdir -p /pkgs/$PACKAGE/usr/lib32
DESTDIR=$PWD/DESTDIR ninja install
cp -Rv DESTDIR/usr/lib32/* /pkgs/$PACKAGE/usr/lib32
rm -rf DESTDIR
cp -rpv /pkgs/$PACKAGE/* /
cd /pkgs



sudo echo "pipewire lib32-dbus lib32-alsa-lib" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


