#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2 "

URL=https://www.openldap.org/software/download/OpenLDAP/openldap-release/openldap-2.6.3.tgz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tgz||g')
# Lib32 doesn't need the server
PACKAGE=lib32-openldap
set -e
# Get Package

cd /blfs/builds
wget $URL
wget  https://www.linuxfromscratch.org/patches/blfs/svn/openldap-2.6.3-consolidated-1.patch
tar -xvf $TAR
cd $DIR

export CFLAGS+="-m32" 
export CXXFLAGS+="-m32"
export PKG_CONFIG="i686-pc-linux-gnu-pkg-config"

# Build
autoconf

patch -Np1 -i ../openldap-2.6.3-consolidated-1.patch &&
./configure --prefix=/usr     \
            --sysconfdir=/etc \
            --disable-static  \
            --enable-dynamic  \
            --enable-versioning=yes  \
            --disable-debug   \
            --disable-slapd \
	    --libdir=/usr/lib32 \


make -j16


# Install
mkdir -p /pkgs/$PACKAGE/usr/lib32
make DESTDIR=$PWD/DESTDIR install
cp -Rv DESTDIR/usr/lib32/* /pkgs/$PACKAGE/usr/lib32
rm -rf DESTDIR
cp -rpv /pkgs/$PACKAGE/* /
cd /pkgs



sudo echo "lib32-glibc lib32-pam openldap-client" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
rm -rf $DIR
