#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2 "

PKG_VER=8.2
URL=https://ftp.gnu.org/gnu/readline/readline-$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=lib32-$(echo $DIR | sed 's|-[^-]*$||g')
set -e
# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build


sed -i '/MV.*old/d' Makefile.in
sed -i '/{OLDSUFF}/c:' support/shlib-install
export CC="gcc -m32"
./configure --prefix=/usr    \
            --disable-static \
            --with-curses    \
            --docdir=/usr/share/doc/readline-$PKG_VER \
	    --libdir=/usr/lib32 \
	    --host=i686-pc-linux-gnu


make SHLIB_LIBS="-lncursesw" -j16

# Install
mkdir -p /pkgs/$PACKAGE/usr/lib32
sudo make SHLIB_LIBS="-lncursesw" DESTDIR=$PWD/DESTDIR install
mkdir -p /pkgs/readline/usr/share/doc
install -v -m644 doc/*.{ps,pdf,html,dvi} /pkgs/readline/usr/share/doc/readline-8.1.2
cp -Rv DESTDIR/usr/lib32/* /pkgs/$PACKAGE/usr/lib32
rm -rf DESTDIR
cp -rpv /pkgs/$PACKAGE/* /

cd /pkgs



sudo echo "glibc ncurses" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


