#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "

PKG_VER=3.4.0
 
URL=https://www.openssl.org/source/openssl-$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=lib32-$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
export CFLAGS="-m32 -march=i686 -Wall -O3" CXXFLAGS="$CFLAGS"
./config --prefix=/usr         \
         --openssldir=/etc/ssl \
         --libdir=lib32          \
         shared                \
         zlib-dynamic \
	 linux-generic32 \
	 enable-ktls \


make -j16


# Install
sed -i '/INSTALL_LIBS/s/libcrypto.a libssl.a//' Makefile
mkdir -p /pkgs/$PACKAGE/usr/lib32
make DESTDIR=$PWD/DESTDIR install
cp -Rv DESTDIR/usr/lib32/* /pkgs/$PACKAGE/usr/lib32
rm -rf DESTDIR
cp -rpv /pkgs/$PACKAGE/* /
cd /pkgs



sudo echo "lib32-glibc lib32-libgcc openssl" > /pkgs/$PACKAGE/depends
sudo echo "binutils coreutils gcc make perl" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


