#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2"

PKG_VER=5.4.1
URL=https://tukaani.org/xz/xz-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=lib32-$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
CC="gcc -m32" ./configure \
    --host=i686-pc-linux-gnu      \
    --prefix=/usr                 \
    --libdir=/usr/lib32           \
    --disable-static


make -j16


# Install
mkdir -p /pkgs/$PACKAGE/usr/lib32
make DESTDIR=$PWD/DESTDIR install
cp -Rv DESTDIR/usr/lib32/* /pkgs/$PACKAGE/usr/lib32
rm -rf DESTDIR
cp -rpv /pkgs/$PACKAGE/* /
cd /pkgs



sudo echo "lib32-glibc xz" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


