#!/bin/bash
PKG_VER=1.2.13
URL=https://zlib.net/zlib-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=lib32-$(echo $DIR | sed 's|-[^-]*$||g')

export CFLAGS+="-m32" 
export CXXFLAGS+="-m32"

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build


./configure --prefix=/usr  --libdir=/usr/lib32

make -j16


# Install
mkdir -p /pkgs/$PACKAGE/usr/lib32
make DESTDIR=$PWD/DESTDIR install
cp -Rv DESTDIR/usr/lib32/* /pkgs/$PACKAGE/usr/lib32
rm -rf DESTDIR
cp -rpv /pkgs/$PACKAGE/* /

#Strip Binary
strip /pkgs/$PACKAGE/usr/lib32/libz.so.$PKG_VER

cd /pkgs



sudo echo "lib32-glibc zlib" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


