#!/bin/bash
URL=https://github.com/facebook/zstd/releases/download/v1.5.2/zstd-1.5.2.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=lib32-$(echo $DIR | sed 's|-[^-]*$||g')
set -e

# Get Package

cd /blfs/builds
wget $URL
wget https://www.linuxfromscratch.org/patches/lfs/development/zstd-1.5.2-upstream_fixes-1.patch
tar -xvf $TAR
cd $DIR

# Build


patch -Np1 -i ../zstd-1.5.2-upstream_fixes-1.patch

CC="gcc -m32" make prefix=/usr -j16


# Install

mkdir -p /pkgs/$PACKAGE/usr/lib32
make prefix=/usr DESTDIR=$PWD/DESTDIR  install
sed -e "/^libdir/s/lib$/lib32/" -i DESTDIR/usr/lib/pkgconfig/libzstd.pc
cp -Rv DESTDIR/usr/lib/* /pkgs/$PACKAGE/usr/lib32
rm -rf DESTDIR
cp -rpv /pkgs/$PACKAGE/* /

rm -v /usr/lib32/libzstd.a
rm -v /pkgs/lib32-zstd/usr/lib32/libzstd.a
cd /pkgs



sudo echo "zstd lib32-glibc" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


