#!/bin/bash
export CFLAGS=-"O2"
export CXXFLAGS="-O2"



URL=https://ftp.gnu.org/gnu/binutils/binutils-2.40.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir -v build
cd       build


../configure --prefix=/usr       \
             --sysconfdir=/etc   \
             --enable-gold       \
             --enable-ld=default \
             --enable-plugins    \
             --enable-shared     \
             --disable-werror    \
             --enable-64-bit-bfd \
             --with-system-zlib
             --enable-multilib \
             --with-bugurl=https://github.com/xXTeraXx/Tucana/ \ 


make tooldir=/usr -j16


# Install
sudo make tooldir=/usr install
rm -fv /usr/lib/lib{bfd,ctf,ctf-nobfd,opcodes}.a
sudo make tooldir=/usr DESTDIR=/pkgs/$PACKAGE install
rm -fv /pkgs/binutils/usr/lib/lib{bfd,ctf,ctf-nobfd,opcodes}.a

cd /pkgs



sudo echo "" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


