#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


set -e
PKG_VER=14.1.0
TARGET=$(gcc -dumpmachine)
URL=https://ftp.gnu.org/gnu/gcc/gcc-$PKG_VER/gcc-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')
ALT_PACKAGE=libgcc
ALT_PACKAGE2=lib32-libgcc
# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build


sed -e '/m64=/s/lib64/lib/' \
    -e '/m32=/s/m32=.*/m32=..\/lib32$(call if_multiarch,:i386-linux-gnu)/' \
    -i.orig gcc/config/i386/t-linux64

    
mkdir -v build
cd       build
LD=ld
CFLAGS="-O2" ../configure --prefix=/usr            \
             LD=ld                    \
             --enable-languages=c,c++,go,ada \
             --enable-multilib       \
             --with-multilib-list=m32,m64 \
             --enable-libada \
             --enable-default-pie \
             --enable-default-ssp  \
             --enable-threads=posix \
             --with-system-zlib \

make BOOT_CFLAGS='-O2' STAGE1_CFLAGS='-O2' bootstrap -j20
#make check -j20



# Install




# GCC 

make DESTDIR=/pkgs/$PACKAGE install

mkdir -p /pkgs/$PACKAGE/usr/lib 

ln -v -sf ../usr/bin/cpp /pkgs/$PACKAGE/usr/lib
ln -v -sf gcc /pkgs/$PACKAGE/usr/bin/cc

# LTO
mkdir -p /pkgs/$PACKAGE/usr/lib/bfd-plugins/
ln -sfv ../../libexec/gcc/$(gcc -dumpmachine)/$PKG_VER/liblto_plugin.so \
        /pkgs/$PACKAGE/usr/lib/bfd-plugins/

chown -v -R root:root \
    /pkgs/$PACKAGE/usr/lib/gcc/*linux-gnu/$PKG_VER/include{,-fixed}

# LIBGCC (Gcc Libraries)
mkdir -p /pkgs/$ALT_PACKAGE/usr/lib

# Libatomic
mv /pkgs/$PACKAGE/usr/lib/libatomic.* /pkgs/$ALT_PACKAGE/usr/lib

#LibSTDCXX
mv /pkgs/$PACKAGE/usr/lib/libstdc* /pkgs/$ALT_PACKAGE/usr/lib

#Jit
#mv /pkgs/$PACKAGE/usr/lib/libgccjit* /pkgs/$ALT_PACKAGE/usr/lib

#libobjc (Currently Not In Tucana) 
#mv /pkgs/$PACKAGE/usr/lib/libobjc* /pkgs/$ALT_PACKAGE/usr/lib

# LibGCC Files
mv /pkgs/$PACKAGE/usr/lib/libgcc_s.so* /pkgs/$ALT_PACKAGE/usr/lib

#LibGOMP
mv /pkgs/$PACKAGE/usr/lib/libgomp.so* /pkgs/$ALT_PACKAGE/usr/lib

#LibGO
mv /pkgs/$PACKAGE/usr/lib/libgo.so* /pkgs/$ALT_PACKAGE/usr/lib

#Libquadmath
mv /pkgs/$PACKAGE/usr/lib/libquadmath.so* /pkgs/$ALT_PACKAGE/usr/lib
#Libtsan
mv /pkgs/$PACKAGE/usr/lib/libtsan.so* /pkgs/$ALT_PACKAGE/usr/lib
#UbSan
mv /pkgs/$PACKAGE/usr/lib/libubsan.so* /pkgs/$ALT_PACKAGE/usr/lib
#LibITM
mv /pkgs/$PACKAGE/usr/lib/libitm.so.* /pkgs/$ALT_PACKAGE/usr/lib
#LSAN
mv /pkgs/$PACKAGE/usr/lib/liblsan.so.* /pkgs/$ALT_PACKAGE/usr/lib
#LSAN
mv /pkgs/$PACKAGE/usr/lib/libasan.so.* /pkgs/$ALT_PACKAGE/usr/lib
#SSP
mv /pkgs/$PACKAGE/usr/lib/libssp.so.* /pkgs/$ALT_PACKAGE/usr/lib

# lib32-LibGCC


# LIBGCC (Gcc Libraries)
mkdir -p /pkgs/$ALT_PACKAGE2/usr/lib32

# Libatomic
mv /pkgs/$PACKAGE/usr/lib32/libatomic.* /pkgs/$ALT_PACKAGE2/usr/lib32
#LibSTDCXX
mv /pkgs/$PACKAGE/usr/lib32/libstdc* /pkgs/$ALT_PACKAGE2/usr/lib32

#Jit
#mv /pkgs/$PACKAGE/usr/lib32/libgccjit* /pkgs/$ALT_PACKAGE2/usr/lib32

#libobjc (Currently Not In Tucana) 
#mv /pkgs/$PACKAGE/usr/lib32/libobjc* /pkgs/$ALT_PACKAGE/usr/lib32

# LibGCC Files
mv /pkgs/$PACKAGE/usr/lib32/libgcc_s.so* /pkgs/$ALT_PACKAGE2/usr/lib32

#LibGOMP
mv /pkgs/$PACKAGE/usr/lib32/libgomp.so* /pkgs/$ALT_PACKAGE2/usr/lib32

#LibGO
#mv /pkgs/$PACKAGE/usr/lib32/libgo.so* /pkgs/$ALT_PACKAGE2/usr/lib32

#Libquadmath
mv /pkgs/$PACKAGE/usr/lib32/libquadmath.so* /pkgs/$ALT_PACKAGE2/usr/lib32
#UbSan
mv /pkgs/$PACKAGE/usr/lib32/libubsan.so* /pkgs/$ALT_PACKAGE2/usr/lib32
#LibITM
mv /pkgs/$PACKAGE/usr/lib32/libitm.so.* /pkgs/$ALT_PACKAGE2/usr/lib32
#ASAN
mv /pkgs/$PACKAGE/usr/lib32/libasan.so.* /pkgs/$ALT_PACKAGE2/usr/lib32
#SSP
mv /pkgs/$PACKAGE/usr/lib32/libssp.so.* /pkgs/$ALT_PACKAGE2/usr/lib32






# Package
cd /pkgs

echo "libgcc glibc zstd mpc mpfr gmp flex isl" > /pkgs/$PACKAGE/depends
tar -cvzpf $PACKAGE.tar.xz $PACKAGE
cp $PACKAGE.tar.xz /finished


echo "glibc isl" > /pkgs/$ALT_PACKAGE/depends
tar -cvzpf $ALT_PACKAGE.tar.xz $ALT_PACKAGE
cp $ALT_PACKAGE.tar.xz /finished

echo "lib32-glibc glibc" > /pkgs/$ALT_PACKAGE2/depends
tar -cvzpf $ALT_PACKAGE2.tar.xz $ALT_PACKAGE2
cp $ALT_PACKAGE2.tar.xz /finished
# Remove Temp Files

cd /blfs/builds
sudo rm -r $DIR


