#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

PKG_VER=2.40
# Build Only
set -e
URL=https://ftp.gnu.org/gnu/glibc/glibc-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=lib32-glibc

# Get Package
sudo ln -sfv /usr/lib32 /lib32
cd /blfs/builds
wget $URL
wget https://www.linuxfromscratch.org/patches/lfs/development/glibc-$PKG_VER-fhs-1.patch
tar -xvf $TAR
cd $DIR

# Build
patch -Np1 -i ../glibc-$PKG_VER-fhs-1.patch
mkdir -v build
cd       build
echo "rootsbindir=/usr/sbin" > configparms


CC="gcc -m32" CXX="g++ -m32" \
../configure                             \
      --prefix=/usr                      \
      --build=$(../scripts/config.guess) \
      --enable-kernel=3.2                \
      --with-headers=/usr/include \
      --host=i686-linux-gnu \
      --disable-nscd \
      --libexecdir=/usr/lib32            \
      --enable-multi-arch                \
      --libdir=/usr/lib32 libc_cv_slibdir=/usr/lib32 \


make -j20


# Install
sed '/test-installation/s@$(PERL)@echo not running@' -i ../Makefile
sudo make DESTDIR=$PWD/DESTDIR install
cp -a DESTDIR/usr/lib32 /usr/
install -vm644 DESTDIR/usr/include/gnu/{lib-names,stubs}-32.h \
               /usr/include/gnu/
ln -svf ../lib32/ld-linux.so.2  /lib/ld-linux.so.2


cd /blfs/builds
sudo rm -r $DIR


