#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

PKG_VER=6.4.12
URL=https://www.kernel.org/pub/linux/kernel/v6.x/linux-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=linux-api-headers

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build


make  headers -j16
find usr/include -type f ! -name '*.h' -delete


# Install
cp -rv usr/include /usr
mkdir -p /pkgs/$PACKAGE/usr
cp -rv usr/include /pkgs/$PACKAGE/usr

cd /pkgs



sudo echo "" > /pkgs/$PACKAGE/depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished



cd /blfs/builds
sudo rm -r $DIR


